#!/bin/bash
# Snapshot the pristine sources a mutation harness will restore from.
#
# The mutations rewrite the .py files IN PLACE, so every harness needs a
# baseline to put back.  It is a tarball rather than `git checkout` on purpose:
# a harness that reaches for git silently discards any uncommitted edit sitting
# in the tree, which has cost this project a working change once already.
#
# THE ENTRY COUNT IS CHECKED BEFORE ANY ARCHIVE IS TRUSTED.  A failed `tar czf`
# leaves a 45-byte EMPTY archive behind, and restoring from one deletes nothing
# and repairs nothing -- so every later probe in the table runs against the
# previous probe's mutation and the whole table is wrong.  That has happened.
cd "$(dirname "$0")"
A="${1:?usage: mkbase.sh <archive.tgz>}"
# Reuse an existing snapshot -- it is the pristine baseline of the run that made
# it -- but SAY SO with its age.  A leftover archive from an interrupted run
# will silently restore that run's code over any edit made since, which is
# exactly the "reverting by reaching for a saved copy discards your work" trap.
# A harness that finishes normally deletes its archive, so a surviving one means
# the previous run did not finish.
if [ -f "$A" ]; then
  # ON STDERR.  Every harness calls `./restore.sh >/dev/null`, so a notice on
  # stdout is discarded by exactly the caller that needs it -- which is how a
  # stale archive from an interrupted run silently restored the WRONG tree in
  # the middle of a table.
  echo "mkbase: reusing $A from $(date -r "$A" '+%H:%M:%S') -- delete it if the sources have moved since" >&2
  exit 0
fi
# EVERYTHING A MUTATION CAN WRITE, not just the sources.  Four of the twelve
# shared-memory probes mutate a FIXTURE (`smut/*.ptx`, `smut/*.sass`) rather
# than a .py, so an archive of `*.py` alone restores nothing for those and every
# later row of the table runs against the previous row's damaged fixture.  That
# is not hypothetical: narrowing this archive to `*.py` produced a table whose
# last five rows -- INCLUDING the restored baseline -- all reported the same
# `barrier counts differ`, which is the tell.  READ THE BASELINE ROW.
#
# corpus/ and o1/ are excluded: they are generated by build_corpus.sh, they are
# large, and no mutation touches them.
# EVERY .py and .sh except the restore machinery itself.  `restore.sh` extracts
# this archive while bash is executing it, so neither it nor `mkbase.sh` may be
# a member; every other script can be, and archiving them all is what makes the
# coverage check below mechanical instead of a list somebody maintains.
tar czf "$A" $(ls *.py *.sh | grep -vE '^(mkbase|restore)\.sh$') \
             muts smut fma div loop synth neg \
  || { echo "mkbase: tar failed"; rm -f "$A"; exit 1; }
n=$(tar tzf "$A" | wc -l)
[ "$n" -ge 40 ] || { echo "mkbase: $A has only $n entries -- refusing"; rm -f "$A"; exit 1; }
# AND THE COVERAGE IS CHECKED, because an entry COUNT cannot see a file that is
# missing.  A probe that writes something the archive does not hold is restored
# by nothing, so every row after it -- INCLUDING the restored baseline -- runs
# against that probe's mutation.  This has now happened twice from two different
# directions: once because the archive held only `*.py` and four probes mutate a
# FIXTURE, and once because a probe mutates `regress.sh`, which holds the
# standing assertions and is not a source file.  The rule is that every tracked
# .py and .sh under this directory must be in the archive, and the two
# exceptions are NAMED: `restore.sh` extracts the archive while bash is
# executing it, so neither it nor `mkbase.sh` may be overwritten mid-run.
if command -v git >/dev/null 2>&1 && git rev-parse --show-toplevel >/dev/null 2>&1; then
  miss=$(comm -23 \
    <(git ls-files . | grep -E '\.(py|sh)$' | grep -vE '^(mkbase|restore)\.sh$' | sort) \
    <(tar tzf "$A" | sed 's|^\./||' | sort))
  if [ -n "$miss" ]; then
    echo "mkbase: NOT IN THE ARCHIVE -- a probe that writes one of these is"
    echo "mkbase: restored by nothing, and every later row is contaminated:"
    echo "$miss" | sed 's/^/mkbase:   /'
    rm -f "$A"; exit 1
  fi
fi
echo "mkbase: $A snapshots $n files"
