#!/bin/bash
# Snapshot the pristine sources a mutation harness will restore from.
#
# The mutations rewrite the .py files IN PLACE, so every harness needs a
# baseline to put back.  It is a tarball rather than `git checkout` on purpose:
# a harness that reaches for git silently discards any uncommitted edit sitting
# in the tree, which has cost this project a working change once already.
#
# THE ENTRY COUNT IS CHECKED BEFORE ANY ARCHIVE IS TRUSTED.  A failed `tar czf`
# leaves a 45-byte EMPTY archive behind, and restoring from one deletes nothing
# and repairs nothing -- so every later probe in the table runs against the
# previous probe's mutation and the whole table is wrong.  That has happened.
cd "$(dirname "$0")"
A="${1:?usage: mkbase.sh <archive.tgz>}"
# Reuse an existing snapshot -- it is the pristine baseline of the run that made
# it -- but SAY SO with its age.  A leftover archive from an interrupted run
# will silently restore that run's code over any edit made since, which is
# exactly the "reverting by reaching for a saved copy discards your work" trap.
# A harness that finishes normally deletes its archive, so a surviving one means
# the previous run did not finish.
if [ -f "$A" ]; then
  echo "mkbase: reusing $A from $(date -r "$A" '+%H:%M:%S') -- delete it if the sources have moved since"
  exit 0
fi
# EVERYTHING A MUTATION CAN WRITE, not just the sources.  Four of the twelve
# shared-memory probes mutate a FIXTURE (`smut/*.ptx`, `smut/*.sass`) rather
# than a .py, so an archive of `*.py` alone restores nothing for those and every
# later row of the table runs against the previous row's damaged fixture.  That
# is not hypothetical: narrowing this archive to `*.py` produced a table whose
# last five rows -- INCLUDING the restored baseline -- all reported the same
# `barrier counts differ`, which is the tell.  READ THE BASELINE ROW.
#
# corpus/ and o1/ are excluded: they are generated by build_corpus.sh, they are
# large, and no mutation touches them.
tar czf "$A" *.py muts smut fma div loop synth \
  || { echo "mkbase: tar failed"; rm -f "$A"; exit 1; }
n=$(tar tzf "$A" | wc -l)
[ "$n" -ge 40 ] || { echo "mkbase: $A has only $n entries -- refusing"; rm -f "$A"; exit 1; }
echo "mkbase: $A snapshots $n files"
