; ================================================
;  Generated by Y Compiler — LLVM IR Backend
;  Hardware Profile: AVX=true, AVX512=true, L2 Line=64B
; ================================================

target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

attributes #0 = { "target-cpu"="skylake-avx512" "target-features"="+avx512f,+avx512cd,+avx512bw,+avx512dq,+avx512vl" }

; --- Struct Definitions ---
%Vec3 = type { float, float, float }
%AABB = type { %Vec3, %Vec3 }
%Sphere = type { %Vec3, float, i32 }
%BVHNode = type { %AABB, i64, i64, i64, i64 }
%Storage = type { i64 }
%BVH = type { %Storage, %Storage }

; --- Enum Definitions ---

; --- External Runtime Declarations ---
declare ptr @ystr_new(ptr)
declare void @ystr_push(ptr, i8)
declare void @ystr_push_str(ptr, ptr)
declare i1 @ystr_eq_cstr(ptr, ptr)
declare i64 @ystr_len(ptr)
declare i8 @ystr_char_at(ptr, i64)
declare ptr @ystr_clone(ptr)
declare ptr @yvec_new(i64)
declare void @yvec_push(ptr, ptr)
declare ptr @yvec_get(ptr, i64)
declare i64 @yvec_len(ptr)
declare ptr @yfile_read_to_string(ptr)
declare void @yfile_write(ptr, ptr)
declare i32 @printf(ptr, ...)
declare ptr @malloc(i64)
declare void @free(ptr)
declare void @exit(i32) noreturn
declare void @println(ptr)
declare void @print_int(i64)
declare void @llvm.prefetch.p0(ptr nocapture readonly, i32, i32, i32)
declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg)

; --- String Constants ---
@.str.0 = private unnamed_addr constant [38 x i8] c"BVH Structures Initialized in Y.\00"

@.fmt.sn = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt.s = private unnamed_addr constant [3 x i8] c"%s\00"
@.fmt.d = private unnamed_addr constant [4 x i8] c"%ld\00"

; impl Vec3
define %Vec3 @Vec3_new(float %x.arg, float %y.arg, float %z.arg) #0 {
entry:
  %x = alloca float
  store float %x.arg, ptr %x
  %y = alloca float
  store float %y.arg, ptr %y
  %z = alloca float
  store float %z.arg, ptr %z
  %t1 = load float, ptr %x
  %t2 = insertvalue %Vec3 undef, float %t1, 0
  %t3 = load float, ptr %y
  %t4 = insertvalue %Vec3 %t2, float %t3, 1
  %t5 = load float, ptr %z
  %t6 = insertvalue %Vec3 %t4, float %t5, 2
  ret %Vec3 %t6
}

define %Vec3 @Vec3_add(%Vec3 %a.arg, %Vec3 %b.arg) #0 {
entry:
  %a = alloca %Vec3
  store %Vec3 %a.arg, ptr %a
  %b = alloca %Vec3
  store %Vec3 %b.arg, ptr %b
  ; lvalue .x
  %t1 = getelementptr %Vec3, ptr %a, i32 0, i32 0
  %t2 = load float, ptr %t1
  ; lvalue .x
  %t3 = getelementptr %Vec3, ptr %b, i32 0, i32 0
  %t4 = load float, ptr %t3
  %t5 = fadd float %t2, %t4
  %t6 = insertvalue %Vec3 undef, float %t5, 0
  ; lvalue .y
  %t7 = getelementptr %Vec3, ptr %a, i32 0, i32 1
  %t8 = load float, ptr %t7
  ; lvalue .y
  %t9 = getelementptr %Vec3, ptr %b, i32 0, i32 1
  %t10 = load float, ptr %t9
  %t11 = fadd float %t8, %t10
  %t12 = insertvalue %Vec3 %t6, float %t11, 1
  ; lvalue .z
  %t13 = getelementptr %Vec3, ptr %a, i32 0, i32 2
  %t14 = load float, ptr %t13
  ; lvalue .z
  %t15 = getelementptr %Vec3, ptr %b, i32 0, i32 2
  %t16 = load float, ptr %t15
  %t17 = fadd float %t14, %t16
  %t18 = insertvalue %Vec3 %t12, float %t17, 2
  ret %Vec3 %t18
}

define %Vec3 @Vec3_sub(%Vec3 %a.arg, %Vec3 %b.arg) #0 {
entry:
  %a = alloca %Vec3
  store %Vec3 %a.arg, ptr %a
  %b = alloca %Vec3
  store %Vec3 %b.arg, ptr %b
  ; lvalue .x
  %t1 = getelementptr %Vec3, ptr %a, i32 0, i32 0
  %t2 = load float, ptr %t1
  ; lvalue .x
  %t3 = getelementptr %Vec3, ptr %b, i32 0, i32 0
  %t4 = load float, ptr %t3
  %t5 = fsub float %t2, %t4
  %t6 = insertvalue %Vec3 undef, float %t5, 0
  ; lvalue .y
  %t7 = getelementptr %Vec3, ptr %a, i32 0, i32 1
  %t8 = load float, ptr %t7
  ; lvalue .y
  %t9 = getelementptr %Vec3, ptr %b, i32 0, i32 1
  %t10 = load float, ptr %t9
  %t11 = fsub float %t8, %t10
  %t12 = insertvalue %Vec3 %t6, float %t11, 1
  ; lvalue .z
  %t13 = getelementptr %Vec3, ptr %a, i32 0, i32 2
  %t14 = load float, ptr %t13
  ; lvalue .z
  %t15 = getelementptr %Vec3, ptr %b, i32 0, i32 2
  %t16 = load float, ptr %t15
  %t17 = fsub float %t14, %t16
  %t18 = insertvalue %Vec3 %t12, float %t17, 2
  ret %Vec3 %t18
}

define %Vec3 @Vec3_mul(%Vec3 %a.arg, float %t.arg) #0 {
entry:
  %a = alloca %Vec3
  store %Vec3 %a.arg, ptr %a
  %t = alloca float
  store float %t.arg, ptr %t
  ; lvalue .x
  %t1 = getelementptr %Vec3, ptr %a, i32 0, i32 0
  %t2 = load float, ptr %t1
  %t3 = load float, ptr %t
  %t4 = fmul float %t2, %t3
  %t5 = insertvalue %Vec3 undef, float %t4, 0
  ; lvalue .y
  %t6 = getelementptr %Vec3, ptr %a, i32 0, i32 1
  %t7 = load float, ptr %t6
  %t8 = load float, ptr %t
  %t9 = fmul float %t7, %t8
  %t10 = insertvalue %Vec3 %t5, float %t9, 1
  ; lvalue .z
  %t11 = getelementptr %Vec3, ptr %a, i32 0, i32 2
  %t12 = load float, ptr %t11
  %t13 = load float, ptr %t
  %t14 = fmul float %t12, %t13
  %t15 = insertvalue %Vec3 %t10, float %t14, 2
  ret %Vec3 %t15
}

define %Vec3 @Vec3_min(%Vec3 %a.arg, %Vec3 %b.arg) #0 {
entry:
  %a = alloca %Vec3
  store %Vec3 %a.arg, ptr %a
  %b = alloca %Vec3
  store %Vec3 %b.arg, ptr %b
  %x = alloca float
  %y = alloca float
  %z = alloca float
  ; lvalue .x
  %t1 = getelementptr %Vec3, ptr %a, i32 0, i32 0
  %t2 = load float, ptr %t1
  store float %t2, ptr %x
  ; lvalue .x
  %t3 = getelementptr %Vec3, ptr %b, i32 0, i32 0
  %t4 = load float, ptr %t3
  %t5 = load float, ptr %x
  %t6 = fcmp olt float %t4, %t5
  br i1 %t6, label %then.1, label %merge.3
then.1:
  ; lvalue .x
  %t7 = getelementptr %Vec3, ptr %b, i32 0, i32 0
  %t8 = load float, ptr %t7
  store float %t8, ptr %x
  br label %merge.3
merge.3:
  ; lvalue .y
  %t9 = getelementptr %Vec3, ptr %a, i32 0, i32 1
  %t10 = load float, ptr %t9
  store float %t10, ptr %y
  ; lvalue .y
  %t11 = getelementptr %Vec3, ptr %b, i32 0, i32 1
  %t12 = load float, ptr %t11
  %t13 = load float, ptr %y
  %t14 = fcmp olt float %t12, %t13
  br i1 %t14, label %then.4, label %merge.6
then.4:
  ; lvalue .y
  %t15 = getelementptr %Vec3, ptr %b, i32 0, i32 1
  %t16 = load float, ptr %t15
  store float %t16, ptr %y
  br label %merge.6
merge.6:
  ; lvalue .z
  %t17 = getelementptr %Vec3, ptr %a, i32 0, i32 2
  %t18 = load float, ptr %t17
  store float %t18, ptr %z
  ; lvalue .z
  %t19 = getelementptr %Vec3, ptr %b, i32 0, i32 2
  %t20 = load float, ptr %t19
  %t21 = load float, ptr %z
  %t22 = fcmp olt float %t20, %t21
  br i1 %t22, label %then.7, label %merge.9
then.7:
  ; lvalue .z
  %t23 = getelementptr %Vec3, ptr %b, i32 0, i32 2
  %t24 = load float, ptr %t23
  store float %t24, ptr %z
  br label %merge.9
merge.9:
  %t25 = load float, ptr %x
  %t26 = insertvalue %Vec3 undef, float %t25, 0
  %t27 = load float, ptr %y
  %t28 = insertvalue %Vec3 %t26, float %t27, 1
  %t29 = load float, ptr %z
  %t30 = insertvalue %Vec3 %t28, float %t29, 2
  ret %Vec3 %t30
}

define %Vec3 @Vec3_max(%Vec3 %a.arg, %Vec3 %b.arg) #0 {
entry:
  %a = alloca %Vec3
  store %Vec3 %a.arg, ptr %a
  %b = alloca %Vec3
  store %Vec3 %b.arg, ptr %b
  %x = alloca float
  %y = alloca float
  %z = alloca float
  ; lvalue .x
  %t1 = getelementptr %Vec3, ptr %a, i32 0, i32 0
  %t2 = load float, ptr %t1
  store float %t2, ptr %x
  ; lvalue .x
  %t3 = getelementptr %Vec3, ptr %b, i32 0, i32 0
  %t4 = load float, ptr %t3
  %t5 = load float, ptr %x
  %t6 = fcmp ogt float %t4, %t5
  br i1 %t6, label %then.10, label %merge.12
then.10:
  ; lvalue .x
  %t7 = getelementptr %Vec3, ptr %b, i32 0, i32 0
  %t8 = load float, ptr %t7
  store float %t8, ptr %x
  br label %merge.12
merge.12:
  ; lvalue .y
  %t9 = getelementptr %Vec3, ptr %a, i32 0, i32 1
  %t10 = load float, ptr %t9
  store float %t10, ptr %y
  ; lvalue .y
  %t11 = getelementptr %Vec3, ptr %b, i32 0, i32 1
  %t12 = load float, ptr %t11
  %t13 = load float, ptr %y
  %t14 = fcmp ogt float %t12, %t13
  br i1 %t14, label %then.13, label %merge.15
then.13:
  ; lvalue .y
  %t15 = getelementptr %Vec3, ptr %b, i32 0, i32 1
  %t16 = load float, ptr %t15
  store float %t16, ptr %y
  br label %merge.15
merge.15:
  ; lvalue .z
  %t17 = getelementptr %Vec3, ptr %a, i32 0, i32 2
  %t18 = load float, ptr %t17
  store float %t18, ptr %z
  ; lvalue .z
  %t19 = getelementptr %Vec3, ptr %b, i32 0, i32 2
  %t20 = load float, ptr %t19
  %t21 = load float, ptr %z
  %t22 = fcmp ogt float %t20, %t21
  br i1 %t22, label %then.16, label %merge.18
then.16:
  ; lvalue .z
  %t23 = getelementptr %Vec3, ptr %b, i32 0, i32 2
  %t24 = load float, ptr %t23
  store float %t24, ptr %z
  br label %merge.18
merge.18:
  %t25 = load float, ptr %x
  %t26 = insertvalue %Vec3 undef, float %t25, 0
  %t27 = load float, ptr %y
  %t28 = insertvalue %Vec3 %t26, float %t27, 1
  %t29 = load float, ptr %z
  %t30 = insertvalue %Vec3 %t28, float %t29, 2
  ret %Vec3 %t30
}

; impl AABB
define %AABB @AABB_surrounding(%AABB %box0.arg, %AABB %box1.arg) #0 {
entry:
  %box0 = alloca %AABB
  store %AABB %box0.arg, ptr %box0
  %box1 = alloca %AABB
  store %AABB %box1.arg, ptr %box1
  %small = alloca %Vec3
  %big = alloca %Vec3
  ; lvalue .minimum
  %t1 = getelementptr %AABB, ptr %box0, i32 0, i32 0
  %t2 = load %Vec3, ptr %t1
  ; lvalue .minimum
  %t3 = getelementptr %AABB, ptr %box1, i32 0, i32 0
  %t4 = load %Vec3, ptr %t3
  %t5 = call %Vec3 @Vec3_min(%Vec3 %t2, %Vec3 %t4)
  %t6 = getelementptr %Vec3, ptr null, i32 1
  %t7 = ptrtoint ptr %t6 to i64
  %t8 = alloca %Vec3
  store %Vec3 %t5, ptr %t8
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %small, ptr align 8 %t8, i64 %t7, i1 false)
  ; lvalue .maximum
  %t9 = getelementptr %AABB, ptr %box0, i32 0, i32 1
  %t10 = load %Vec3, ptr %t9
  ; lvalue .maximum
  %t11 = getelementptr %AABB, ptr %box1, i32 0, i32 1
  %t12 = load %Vec3, ptr %t11
  %t13 = call %Vec3 @Vec3_max(%Vec3 %t10, %Vec3 %t12)
  %t14 = getelementptr %Vec3, ptr null, i32 1
  %t15 = ptrtoint ptr %t14 to i64
  %t16 = alloca %Vec3
  store %Vec3 %t13, ptr %t16
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %big, ptr align 8 %t16, i64 %t15, i1 false)
  %t17 = load %Vec3, ptr %small
  %t18 = insertvalue %AABB undef, %Vec3 %t17, 0
  %t19 = load %Vec3, ptr %big
  %t20 = insertvalue %AABB %t18, %Vec3 %t19, 1
  ret %AABB %t20
}

define i1 @AABB_hit(ptr %box.arg, %Vec3 %r_orig.arg, %Vec3 %r_dir.arg, float %t_min.arg, float %t_max.arg) #0 {
entry:
  %box = alloca ptr
  store ptr %box.arg, ptr %box
  %r_orig = alloca %Vec3
  store %Vec3 %r_orig.arg, ptr %r_orig
  %r_dir = alloca %Vec3
  store %Vec3 %r_dir.arg, ptr %r_dir
  %t_min = alloca float
  store float %t_min.arg, ptr %t_min
  %t_max = alloca float
  store float %t_max.arg, ptr %t_max
  %invD = alloca float
  %t0 = alloca float
  %t1 = alloca float
  %tmp = alloca float
  %t_near = alloca float
  %t_far = alloca float
  ; lvalue .x
  %t1 = getelementptr %Vec3, ptr %r_dir, i32 0, i32 0
  %t2 = load float, ptr %t1
  %t3 = fpext float %t2 to double
  %t4 = fdiv double 1.000000e0, %t3
  %t5 = fptrunc double %t4 to float
  store float %t5, ptr %invD
  ; lvalue .minimum
  %t6 = getelementptr %AABB, ptr %box, i32 0, i32 0
  ; lvalue .x
  %t7 = getelementptr %Vec3, ptr %t6, i32 0, i32 0
  %t8 = load float, ptr %t7
  ; lvalue .x
  %t9 = getelementptr %Vec3, ptr %r_orig, i32 0, i32 0
  %t10 = load float, ptr %t9
  %t11 = fsub float %t8, %t10
  %t12 = load float, ptr %invD
  %t13 = fmul float %t11, %t12
  store float %t13, ptr %t0
  ; lvalue .maximum
  %t14 = getelementptr %AABB, ptr %box, i32 0, i32 1
  ; lvalue .x
  %t15 = getelementptr %Vec3, ptr %t14, i32 0, i32 0
  %t16 = load float, ptr %t15
  ; lvalue .x
  %t17 = getelementptr %Vec3, ptr %r_orig, i32 0, i32 0
  %t18 = load float, ptr %t17
  %t19 = fsub float %t16, %t18
  %t20 = load float, ptr %invD
  %t21 = fmul float %t19, %t20
  store float %t21, ptr %t1
  %t22 = load float, ptr %invD
  %t23 = fpext float %t22 to double
  %t24 = fcmp olt double %t23, 0.000000e0
  br i1 %t24, label %then.19, label %merge.21
then.19:
  %t25 = load float, ptr %t0
  store float %t25, ptr %tmp
  %t26 = load float, ptr %t1
  store float %t26, ptr %t0
  %t27 = load float, ptr %tmp
  store float %t27, ptr %t1
  br label %merge.21
merge.21:
  %t28 = load float, ptr %t_min
  store float %t28, ptr %t_near
  %t29 = load float, ptr %t0
  %t30 = load float, ptr %t_near
  %t31 = fcmp ogt float %t29, %t30
  br i1 %t31, label %then.22, label %merge.24
then.22:
  %t32 = load float, ptr %t0
  store float %t32, ptr %t_near
  br label %merge.24
merge.24:
  %t33 = load float, ptr %t_max
  store float %t33, ptr %t_far
  %t34 = load float, ptr %t1
  %t35 = load float, ptr %t_far
  %t36 = fcmp olt float %t34, %t35
  br i1 %t36, label %then.25, label %merge.27
then.25:
  %t37 = load float, ptr %t1
  store float %t37, ptr %t_far
  br label %merge.27
merge.27:
  %t38 = load float, ptr %t_far
  %t39 = load float, ptr %t_near
  %t40 = fcmp ole float %t38, %t39
  br i1 %t40, label %then.28, label %merge.30
then.28:
  ret i1 0
merge.30:
  ; lvalue .y
  %t41 = getelementptr %Vec3, ptr %r_dir, i32 0, i32 1
  %t42 = load float, ptr %t41
  %t43 = fpext float %t42 to double
  %t44 = fdiv double 1.000000e0, %t43
  %t45 = fptrunc double %t44 to float
  store float %t45, ptr %invD
  ; lvalue .minimum
  %t46 = getelementptr %AABB, ptr %box, i32 0, i32 0
  ; lvalue .y
  %t47 = getelementptr %Vec3, ptr %t46, i32 0, i32 1
  %t48 = load float, ptr %t47
  ; lvalue .y
  %t49 = getelementptr %Vec3, ptr %r_orig, i32 0, i32 1
  %t50 = load float, ptr %t49
  %t51 = fsub float %t48, %t50
  %t52 = load float, ptr %invD
  %t53 = fmul float %t51, %t52
  store float %t53, ptr %t0
  ; lvalue .maximum
  %t54 = getelementptr %AABB, ptr %box, i32 0, i32 1
  ; lvalue .y
  %t55 = getelementptr %Vec3, ptr %t54, i32 0, i32 1
  %t56 = load float, ptr %t55
  ; lvalue .y
  %t57 = getelementptr %Vec3, ptr %r_orig, i32 0, i32 1
  %t58 = load float, ptr %t57
  %t59 = fsub float %t56, %t58
  %t60 = load float, ptr %invD
  %t61 = fmul float %t59, %t60
  store float %t61, ptr %t1
  %t62 = load float, ptr %invD
  %t63 = fpext float %t62 to double
  %t64 = fcmp olt double %t63, 0.000000e0
  br i1 %t64, label %then.31, label %merge.33
then.31:
  %t65 = load float, ptr %t0
  store float %t65, ptr %tmp
  %t66 = load float, ptr %t1
  store float %t66, ptr %t0
  %t67 = load float, ptr %tmp
  store float %t67, ptr %t1
  br label %merge.33
merge.33:
  %t68 = load float, ptr %t0
  %t69 = load float, ptr %t_near
  %t70 = fcmp ogt float %t68, %t69
  br i1 %t70, label %then.34, label %merge.36
then.34:
  %t71 = load float, ptr %t0
  store float %t71, ptr %t_near
  br label %merge.36
merge.36:
  %t72 = load float, ptr %t1
  %t73 = load float, ptr %t_far
  %t74 = fcmp olt float %t72, %t73
  br i1 %t74, label %then.37, label %merge.39
then.37:
  %t75 = load float, ptr %t1
  store float %t75, ptr %t_far
  br label %merge.39
merge.39:
  %t76 = load float, ptr %t_far
  %t77 = load float, ptr %t_near
  %t78 = fcmp ole float %t76, %t77
  br i1 %t78, label %then.40, label %merge.42
then.40:
  ret i1 0
merge.42:
  ; lvalue .z
  %t79 = getelementptr %Vec3, ptr %r_dir, i32 0, i32 2
  %t80 = load float, ptr %t79
  %t81 = fpext float %t80 to double
  %t82 = fdiv double 1.000000e0, %t81
  %t83 = fptrunc double %t82 to float
  store float %t83, ptr %invD
  ; lvalue .minimum
  %t84 = getelementptr %AABB, ptr %box, i32 0, i32 0
  ; lvalue .z
  %t85 = getelementptr %Vec3, ptr %t84, i32 0, i32 2
  %t86 = load float, ptr %t85
  ; lvalue .z
  %t87 = getelementptr %Vec3, ptr %r_orig, i32 0, i32 2
  %t88 = load float, ptr %t87
  %t89 = fsub float %t86, %t88
  %t90 = load float, ptr %invD
  %t91 = fmul float %t89, %t90
  store float %t91, ptr %t0
  ; lvalue .maximum
  %t92 = getelementptr %AABB, ptr %box, i32 0, i32 1
  ; lvalue .z
  %t93 = getelementptr %Vec3, ptr %t92, i32 0, i32 2
  %t94 = load float, ptr %t93
  ; lvalue .z
  %t95 = getelementptr %Vec3, ptr %r_orig, i32 0, i32 2
  %t96 = load float, ptr %t95
  %t97 = fsub float %t94, %t96
  %t98 = load float, ptr %invD
  %t99 = fmul float %t97, %t98
  store float %t99, ptr %t1
  %t100 = load float, ptr %invD
  %t101 = fpext float %t100 to double
  %t102 = fcmp olt double %t101, 0.000000e0
  br i1 %t102, label %then.43, label %merge.45
then.43:
  %t103 = load float, ptr %t0
  store float %t103, ptr %tmp
  %t104 = load float, ptr %t1
  store float %t104, ptr %t0
  %t105 = load float, ptr %tmp
  store float %t105, ptr %t1
  br label %merge.45
merge.45:
  %t106 = load float, ptr %t0
  %t107 = load float, ptr %t_near
  %t108 = fcmp ogt float %t106, %t107
  br i1 %t108, label %then.46, label %merge.48
then.46:
  %t109 = load float, ptr %t0
  store float %t109, ptr %t_near
  br label %merge.48
merge.48:
  %t110 = load float, ptr %t1
  %t111 = load float, ptr %t_far
  %t112 = fcmp olt float %t110, %t111
  br i1 %t112, label %then.49, label %merge.51
then.49:
  %t113 = load float, ptr %t1
  store float %t113, ptr %t_far
  br label %merge.51
merge.51:
  %t114 = load float, ptr %t_far
  %t115 = load float, ptr %t_near
  %t116 = fcmp ole float %t114, %t115
  br i1 %t116, label %then.52, label %merge.54
then.52:
  ret i1 0
merge.54:
  ret i1 1
}

; impl Storage
define %BVHNode @Storage_get_BVHNode(ptr %v.arg, i64 %i.arg) #0 {
entry:
  %v = alloca ptr
  store ptr %v.arg, ptr %v
  %i = alloca i64
  store i64 %i.arg, ptr %i
  %d = alloca %BVHNode
  %t1 = getelementptr %BVHNode, ptr null, i32 1
  %t2 = ptrtoint ptr %t1 to i64
  call void @llvm.memset.p0.i64(ptr %d, i8 0, i64 %t2, i1 false)
  %t3 = load %BVHNode, ptr %d
  ret %BVHNode %t3
}

define %Sphere @Storage_get_Sphere(ptr %v.arg, i64 %i.arg) #0 {
entry:
  %v = alloca ptr
  store ptr %v.arg, ptr %v
  %i = alloca i64
  store i64 %i.arg, ptr %i
  %d = alloca %Sphere
  %t1 = getelementptr %Sphere, ptr null, i32 1
  %t2 = ptrtoint ptr %t1 to i64
  call void @llvm.memset.p0.i64(ptr %d, i8 0, i64 %t2, i1 false)
  %t3 = load %Sphere, ptr %d
  ret %Sphere %t3
}

define void @Storage_set_BVHNode(ptr %v.arg, i64 %i.arg, %BVHNode %n.arg) #0 {
entry:
  %v = alloca ptr
  store ptr %v.arg, ptr %v
  %i = alloca i64
  store i64 %i.arg, ptr %i
  %n = alloca %BVHNode
  store %BVHNode %n.arg, ptr %n
  ret void
}

define void @Storage_push_BVHNode(ptr %v.arg, %BVHNode %n.arg) #0 {
entry:
  %v = alloca ptr
  store ptr %v.arg, ptr %v
  %n = alloca %BVHNode
  store %BVHNode %n.arg, ptr %n
  ret void
}

define i64 @Storage_len(ptr %v.arg) #0 {
entry:
  %v = alloca ptr
  store ptr %v.arg, ptr %v
  %t1 = sext i32 0 to i64
  ret i64 %t1
}

define i64 @build_bvh_recursive(ptr %nodes.arg, ptr %spheres.arg, i64 %start.arg, i64 %end.arg) #0 {
entry:
  %nodes = alloca ptr
  store ptr %nodes.arg, ptr %nodes
  %spheres = alloca ptr
  store ptr %spheres.arg, ptr %spheres
  %start = alloca i64
  store i64 %start.arg, ptr %start
  %end = alloca i64
  store i64 %end.arg, ptr %end
  %span = alloca i64
  %node = alloca %BVHNode
  %main_box = alloca %AABB
  %i = alloca i64
  %s = alloca %Sphere
  %r = alloca %Vec3
  %s_box = alloca %AABB
  %diff = alloca %Vec3
  %axis = alloca i32
  %max_val = alloca float
  %mid = alloca i64
  %node_idx_usize = alloca i64
  %left_idx = alloca i64
  %right_idx = alloca i64
  %updated_node = alloca %BVHNode
  %t1 = load i64, ptr %end
  %t2 = load i64, ptr %start
  %t3 = sub i64 %t1, %t2
  store i64 %t3, ptr %span
  %t4 = getelementptr %BVHNode, ptr null, i32 1
  %t5 = ptrtoint ptr %t4 to i64
  call void @llvm.memset.p0.i64(ptr %node, i8 0, i64 %t5, i1 false)
  ; lvalue .left
  %t6 = getelementptr %BVHNode, ptr %node, i32 0, i32 1
  %t7 = sub i32 0, 1
  %t8 = sext i32 %t7 to i64
  store i64 %t8, ptr %t6
  ; lvalue .right
  %t9 = getelementptr %BVHNode, ptr %node, i32 0, i32 2
  %t10 = sub i32 0, 1
  %t11 = sext i32 %t10 to i64
  store i64 %t11, ptr %t9
  ; lvalue .start
  %t12 = getelementptr %BVHNode, ptr %node, i32 0, i32 3
  %t13 = sext i32 0 to i64
  store i64 %t13, ptr %t12
  ; lvalue .count
  %t14 = getelementptr %BVHNode, ptr %node, i32 0, i32 4
  %t15 = sext i32 0 to i64
  store i64 %t15, ptr %t14
  %t16 = getelementptr %AABB, ptr null, i32 1
  %t17 = ptrtoint ptr %t16 to i64
  call void @llvm.memset.p0.i64(ptr %main_box, i8 0, i64 %t17, i1 false)
  %t18 = load i64, ptr %start
  store i64 %t18, ptr %i
  br label %while.cond.55
while.cond.55:
  %t19 = load i64, ptr %i
  %t20 = load i64, ptr %end
  %t21 = icmp slt i64 %t19, %t20
  br i1 %t21, label %while.body.56, label %while.end.57
while.body.56:
  %t22 = load ptr, ptr %spheres
  %t23 = load i64, ptr %i
  %t24 = call %Sphere @Storage_get_Sphere(ptr %t22, i64 %t23)
  %t25 = getelementptr %Sphere, ptr null, i32 1
  %t26 = ptrtoint ptr %t25 to i64
  %t27 = alloca %Sphere
  store %Sphere %t24, ptr %t27
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %s, ptr align 8 %t27, i64 %t26, i1 false)
  ; lvalue .radius
  %t28 = getelementptr %Sphere, ptr %s, i32 0, i32 1
  %t29 = load float, ptr %t28
  ; lvalue .radius
  %t30 = getelementptr %Sphere, ptr %s, i32 0, i32 1
  %t31 = load float, ptr %t30
  ; lvalue .radius
  %t32 = getelementptr %Sphere, ptr %s, i32 0, i32 1
  %t33 = load float, ptr %t32
  %t34 = call %Vec3 @Vec3_new(%F32 %t29, %F32 %t31, %F32 %t33)
  %t35 = getelementptr %Vec3, ptr null, i32 1
  %t36 = ptrtoint ptr %t35 to i64
  %t37 = alloca %Vec3
  store %Vec3 %t34, ptr %t37
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %r, ptr align 8 %t37, i64 %t36, i1 false)
  ; lvalue .center
  %t38 = getelementptr %Sphere, ptr %s, i32 0, i32 0
  %t39 = load %Vec3, ptr %t38
  %t40 = load %Vec3, ptr %r
  %t41 = call %Vec3 @Vec3_sub(%Vec3 %t39, %Vec3 %t40)
  %t42 = insertvalue %AABB undef, %Vec3 %t41, 0
  ; lvalue .center
  %t43 = getelementptr %Sphere, ptr %s, i32 0, i32 0
  %t44 = load %Vec3, ptr %t43
  %t45 = load %Vec3, ptr %r
  %t46 = call %Vec3 @Vec3_add(%Vec3 %t44, %Vec3 %t45)
  %t47 = insertvalue %AABB %t42, %Vec3 %t46, 1
  %t48 = getelementptr %AABB, ptr null, i32 1
  %t49 = ptrtoint ptr %t48 to i64
  %t50 = alloca %AABB
  store %AABB %t47, ptr %t50
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %s_box, ptr align 8 %t50, i64 %t49, i1 false)
  %t51 = load i64, ptr %i
  %t52 = load i64, ptr %start
  %t53 = icmp eq i64 %t51, %t52
  br i1 %t53, label %then.58, label %else.59
then.58:
  %t54 = load %AABB, ptr %s_box
  %t55 = getelementptr %AABB, ptr null, i32 1
  %t56 = ptrtoint ptr %t55 to i64
  %t57 = alloca %AABB
  store %AABB %t54, ptr %t57
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %main_box, ptr align 8 %t57, i64 %t56, i1 false)
  br label %merge.60
else.59:
  %t58 = load %AABB, ptr %main_box
  %t59 = load %AABB, ptr %s_box
  %t60 = call %AABB @AABB_surrounding(%AABB %t58, %AABB %t59)
  %t61 = getelementptr %AABB, ptr null, i32 1
  %t62 = ptrtoint ptr %t61 to i64
  %t63 = alloca %AABB
  store %AABB %t60, ptr %t63
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %main_box, ptr align 8 %t63, i64 %t62, i1 false)
  br label %merge.60
merge.60:
  %t64 = load i64, ptr %i
  %t65 = sext i32 1 to i64
  %t66 = add i64 %t64, %t65
  store i64 %t66, ptr %i
  br label %while.cond.55
while.end.57:
  ; lvalue .box
  %t67 = getelementptr %BVHNode, ptr %node, i32 0, i32 0
  %t68 = load %AABB, ptr %main_box
  %t69 = getelementptr %AABB, ptr null, i32 1
  %t70 = ptrtoint ptr %t69 to i64
  %t71 = alloca %AABB
  store %AABB %t68, ptr %t71
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %t67, ptr align 8 %t71, i64 %t70, i1 false)
  %t72 = load i64, ptr %span
  %t73 = sext i32 2 to i64
  %t74 = icmp sle i64 %t72, %t73
  br i1 %t74, label %then.61, label %else.62
then.61:
  ; lvalue .left
  %t75 = getelementptr %BVHNode, ptr %node, i32 0, i32 1
  %t76 = sub i32 0, 1
  %t77 = sext i32 %t76 to i64
  store i64 %t77, ptr %t75
  ; lvalue .right
  %t78 = getelementptr %BVHNode, ptr %node, i32 0, i32 2
  %t79 = sub i32 0, 1
  %t80 = sext i32 %t79 to i64
  store i64 %t80, ptr %t78
  ; lvalue .start
  %t81 = getelementptr %BVHNode, ptr %node, i32 0, i32 3
  %t82 = load i64, ptr %start
  store i64 %t82, ptr %t81
  ; lvalue .count
  %t83 = getelementptr %BVHNode, ptr %node, i32 0, i32 4
  %t84 = load i64, ptr %span
  store i64 %t84, ptr %t83
  %t85 = load ptr, ptr %nodes
  %t86 = load %BVHNode, ptr %node
  call void @Storage_push_BVHNode(ptr %t85, %BVHNode %t86)
  %t88 = sext i32 0 to i64
  ret i64 %t88
else.62:
  ; lvalue .maximum
  %t89 = getelementptr %AABB, ptr %main_box, i32 0, i32 1
  %t90 = load %Vec3, ptr %t89
  ; lvalue .minimum
  %t91 = getelementptr %AABB, ptr %main_box, i32 0, i32 0
  %t92 = load %Vec3, ptr %t91
  %t93 = call %Vec3 @Vec3_sub(%Vec3 %t90, %Vec3 %t92)
  %t94 = getelementptr %Vec3, ptr null, i32 1
  %t95 = ptrtoint ptr %t94 to i64
  %t96 = alloca %Vec3
  store %Vec3 %t93, ptr %t96
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %diff, ptr align 8 %t96, i64 %t95, i1 false)
  store i32 0, ptr %axis
  ; lvalue .y
  %t97 = getelementptr %Vec3, ptr %diff, i32 0, i32 1
  %t98 = load float, ptr %t97
  ; lvalue .x
  %t99 = getelementptr %Vec3, ptr %diff, i32 0, i32 0
  %t100 = load float, ptr %t99
  %t101 = fcmp ogt float %t98, %t100
  br i1 %t101, label %then.64, label %merge.66
then.64:
  store i32 1, ptr %axis
  br label %merge.66
merge.66:
  ; lvalue .x
  %t102 = getelementptr %Vec3, ptr %diff, i32 0, i32 0
  %t103 = load float, ptr %t102
  store float %t103, ptr %max_val
  %t104 = load i32, ptr %axis
  %t105 = icmp eq i32 %t104, 1
  br i1 %t105, label %then.67, label %merge.69
then.67:
  ; lvalue .y
  %t106 = getelementptr %Vec3, ptr %diff, i32 0, i32 1
  %t107 = load float, ptr %t106
  store float %t107, ptr %max_val
  br label %merge.69
merge.69:
  ; lvalue .z
  %t108 = getelementptr %Vec3, ptr %diff, i32 0, i32 2
  %t109 = load float, ptr %t108
  %t110 = load float, ptr %max_val
  %t111 = fcmp ogt float %t109, %t110
  br i1 %t111, label %then.70, label %merge.72
then.70:
  store i32 2, ptr %axis
  br label %merge.72
merge.72:
  %t112 = load i64, ptr %start
  %t113 = load i64, ptr %span
  %t114 = sext i32 2 to i64
  %t115 = sdiv i64 %t113, %t114
  %t116 = add i64 %t112, %t115
  store i64 %t116, ptr %mid
  %t117 = load ptr, ptr %nodes
  %t118 = call i64 @Storage_len(ptr %t117)
  store i64 %t118, ptr %node_idx_usize
  %t119 = load ptr, ptr %nodes
  %t120 = load %BVHNode, ptr %node
  call void @Storage_push_BVHNode(ptr %t119, %BVHNode %t120)
  %t122 = load ptr, ptr %nodes
  %t123 = load ptr, ptr %spheres
  %t124 = load i64, ptr %start
  %t125 = load i64, ptr %mid
  %t126 = call i64 @build_bvh_recursive(ptr %t122, ptr %t123, i64 %t124, i64 %t125)
  store i64 %t126, ptr %left_idx
  %t127 = load ptr, ptr %nodes
  %t128 = load ptr, ptr %spheres
  %t129 = load i64, ptr %mid
  %t130 = load i64, ptr %end
  %t131 = call i64 @build_bvh_recursive(ptr %t127, ptr %t128, i64 %t129, i64 %t130)
  store i64 %t131, ptr %right_idx
  %t132 = load ptr, ptr %nodes
  %t133 = load i64, ptr %node_idx_usize
  %t134 = call %BVHNode @Storage_get_BVHNode(ptr %t132, i64 %t133)
  %t135 = getelementptr %BVHNode, ptr null, i32 1
  %t136 = ptrtoint ptr %t135 to i64
  %t137 = alloca %BVHNode
  store %BVHNode %t134, ptr %t137
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %updated_node, ptr align 8 %t137, i64 %t136, i1 false)
  ; lvalue .left
  %t138 = getelementptr %BVHNode, ptr %updated_node, i32 0, i32 1
  %t139 = load i64, ptr %left_idx
  store i64 %t139, ptr %t138
  ; lvalue .right
  %t140 = getelementptr %BVHNode, ptr %updated_node, i32 0, i32 2
  %t141 = load i64, ptr %right_idx
  store i64 %t141, ptr %t140
  ; lvalue .count
  %t142 = getelementptr %BVHNode, ptr %updated_node, i32 0, i32 4
  %t143 = sext i32 0 to i64
  store i64 %t143, ptr %t142
  %t144 = load ptr, ptr %nodes
  %t145 = load i64, ptr %node_idx_usize
  %t146 = load %BVHNode, ptr %updated_node
  call void @Storage_set_BVHNode(ptr %t144, i64 %t145, %BVHNode %t146)
  %t148 = sext i32 0 to i64
  ret i64 %t148
merge.63:
  ret i64 0
}

define i1 @bvh_hit(ptr %nodes.arg, ptr %spheres.arg, i64 %node_idx.arg, %Vec3 %r_orig.arg, %Vec3 %r_dir.arg, float %t_min.arg, float %t_max.arg) #0 {
entry:
  %nodes = alloca ptr
  store ptr %nodes.arg, ptr %nodes
  %spheres = alloca ptr
  store ptr %spheres.arg, ptr %spheres
  %node_idx = alloca i64
  store i64 %node_idx.arg, ptr %node_idx
  %r_orig = alloca %Vec3
  store %Vec3 %r_orig.arg, ptr %r_orig
  %r_dir = alloca %Vec3
  store %Vec3 %r_dir.arg, ptr %r_dir
  %t_min = alloca float
  store float %t_min.arg, ptr %t_min
  %t_max = alloca float
  store float %t_max.arg, ptr %t_max
  %node_idx_usize = alloca i64
  %node = alloca %BVHNode
  %hit_anything = alloca i1
  %i = alloca i64
  %s = alloca %Sphere
  %hit_left = alloca i1
  %hit_right = alloca i1
  %t1 = load i64, ptr %node_idx
  %t2 = sub i32 0, 1
  %t3 = sext i32 %t2 to i64
  %t4 = icmp eq i64 %t1, %t3
  br i1 %t4, label %then.73, label %merge.75
then.73:
  ret i1 0
merge.75:
  %t5 = sext i32 0 to i64
  store i64 %t5, ptr %node_idx_usize
  %t6 = load ptr, ptr %nodes
  %t7 = load i64, ptr %node_idx_usize
  %t8 = call %BVHNode @Storage_get_BVHNode(ptr %t6, i64 %t7)
  %t9 = getelementptr %BVHNode, ptr null, i32 1
  %t10 = ptrtoint ptr %t9 to i64
  %t11 = alloca %BVHNode
  store %BVHNode %t8, ptr %t11
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %node, ptr align 8 %t11, i64 %t10, i1 false)
  ; lvalue .box
  %t12 = getelementptr %BVHNode, ptr %node, i32 0, i32 0
  %t13 = load %AABB, ptr %t12
  ; lvalue .box
  %t15 = getelementptr %BVHNode, ptr %node, i32 0, i32 0
  %t16 = load %Vec3, ptr %r_orig
  %t17 = load %Vec3, ptr %r_dir
  %t18 = load float, ptr %t_min
  %t19 = load float, ptr %t_max
  %t20 = call i1 @AABB_hit(ptr %t15, %Vec3 %t16, %Vec3 %t17, %F32 %t18, %F32 %t19)
  %t21 = xor i1 %t20, 1
  br i1 %t21, label %then.76, label %merge.78
then.76:
  ret i1 0
merge.78:
  ; lvalue .count
  %t22 = getelementptr %BVHNode, ptr %node, i32 0, i32 4
  %t23 = load i64, ptr %t22
  %t24 = sext i32 0 to i64
  %t25 = icmp sgt i64 %t23, %t24
  br i1 %t25, label %then.79, label %else.80
then.79:
  store i1 0, ptr %hit_anything
  %t26 = sext i32 0 to i64
  store i64 %t26, ptr %i
  br label %while.cond.82
while.cond.82:
  %t27 = load i64, ptr %i
  ; lvalue .count
  %t28 = getelementptr %BVHNode, ptr %node, i32 0, i32 4
  %t29 = load i64, ptr %t28
  %t30 = icmp slt i64 %t27, %t29
  br i1 %t30, label %while.body.83, label %while.end.84
while.body.83:
  %t31 = load ptr, ptr %spheres
  ; lvalue .start
  %t32 = getelementptr %BVHNode, ptr %node, i32 0, i32 3
  %t33 = load i64, ptr %t32
  %t34 = load i64, ptr %i
  %t35 = add i64 %t33, %t34
  %t36 = call %Sphere @Storage_get_Sphere(ptr %t31, i64 %t35)
  %t37 = getelementptr %Sphere, ptr null, i32 1
  %t38 = ptrtoint ptr %t37 to i64
  %t39 = alloca %Sphere
  store %Sphere %t36, ptr %t39
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %s, ptr align 8 %t39, i64 %t38, i1 false)
  %t40 = load i64, ptr %i
  %t41 = sext i32 1 to i64
  %t42 = add i64 %t40, %t41
  store i64 %t42, ptr %i
  br label %while.cond.82
while.end.84:
  %t43 = load i1, ptr %hit_anything
  ret i1 %t43
else.80:
  %t44 = load ptr, ptr %nodes
  %t45 = load ptr, ptr %spheres
  ; lvalue .left
  %t46 = getelementptr %BVHNode, ptr %node, i32 0, i32 1
  %t47 = load i64, ptr %t46
  %t48 = load %Vec3, ptr %r_orig
  %t49 = load %Vec3, ptr %r_dir
  %t50 = load float, ptr %t_min
  %t51 = load float, ptr %t_max
  %t52 = call i1 @bvh_hit(ptr %t44, ptr %t45, i64 %t47, %Vec3 %t48, %Vec3 %t49, %F32 %t50, %F32 %t51)
  store i1 %t52, ptr %hit_left
  %t53 = load ptr, ptr %nodes
  %t54 = load ptr, ptr %spheres
  ; lvalue .right
  %t55 = getelementptr %BVHNode, ptr %node, i32 0, i32 2
  %t56 = load i64, ptr %t55
  %t57 = load %Vec3, ptr %r_orig
  %t58 = load %Vec3, ptr %r_dir
  %t59 = load float, ptr %t_min
  %t60 = load float, ptr %t_max
  %t61 = call i1 @bvh_hit(ptr %t53, ptr %t54, i64 %t56, %Vec3 %t57, %Vec3 %t58, %F32 %t59, %F32 %t60)
  store i1 %t61, ptr %hit_right
  %t62 = load i1, ptr %hit_left
  %t63 = load i1, ptr %hit_right
  %t64 = or i1 %t62, %t63
  ret i1 %t64
merge.81:
  ret i1 0
}

define void @main() #0 {
entry:
  %t1 = call ptr @ystr_new(ptr @.str.0)
  call void @println(ptr %t1)
  ret void
}

!0 = !{i32 1}
