/* ============================================== */
/*  Generated by Y Compiler — C11 Backend   */
/* ============================================== */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ── Y Runtime: String ──────────────────── */
typedef struct {
  char *data;
  size_t len;
  size_t cap;
} YStr;

static YStr ystr_new(const char *s) {
  size_t len = s ? strlen(s) : 0;
  size_t cap = len + 1;
  char *data = (char *)malloc(cap);
  if (s)
    memcpy(data, s, len);
  data[len] = '\0';
  return (YStr){data, len, cap};
}

static YStr ystr_clone(const YStr *s) { return ystr_new(s->data); }

static void ystr_push(YStr *s, char c) {
  if (s->len + 1 >= s->cap) {
    s->cap = s->cap * 2 + 1;
    s->data = (char *)realloc(s->data, s->cap);
  }
  s->data[s->len++] = c;
  s->data[s->len] = '\0';
}

static void ystr_push_str(YStr *s, const YStr *other) {
  size_t olen = other->len;
  while (s->len + olen >= s->cap) {
    s->cap = s->cap * 2 + 1;
    s->data = (char *)realloc(s->data, s->cap);
  }
  memcpy(s->data + s->len, other->data, olen);
  s->len += olen;
  s->data[s->len] = '\0';
}

static bool ystr_eq(const YStr *a, const YStr *b) {
  if (a->len != b->len)
    return false;
  return memcmp(a->data, b->data, a->len) == 0;
}

static bool ystr_eq_cstr(const YStr *a, const char *b) {
  return strcmp(a->data, b) == 0;
}
static bool ystr_eq_val(const YStr *a, const YStr *b) {
  if (a->len != b->len)
    return false;
  return memcmp(a->data, b->data, a->len) == 0;
}

static char ystr_char_at(const YStr *s, size_t i) {
  return (i < s->len) ? s->data[i] : '\0';
}

static void ystr_free(YStr *s) {
  free(s->data);
  s->data = NULL;
  s->len = 0;
  s->cap = 0;
}

/* ── Y Runtime: Dynamic Vector ──────────── */
typedef struct {
  void *data;
  size_t len;
  size_t cap;
  size_t elem_size;
} YVec;

static YVec yvec_new(size_t elem_size) { return (YVec){NULL, 0, 0, elem_size}; }

static void yvec_push(YVec *v, const void *elem) {
  if (v->len >= v->cap) {
    v->cap = v->cap == 0 ? 8 : v->cap * 2;
    v->data = realloc(v->data, v->cap * v->elem_size);
  }
  memcpy((char *)v->data + v->len * v->elem_size, elem, v->elem_size);
  v->len++;
}

static void *yvec_get(const YVec *v, size_t i) {
  return (char *)v->data + i * v->elem_size;
}

static char yvec_get_char(const YVec *v, size_t i) {
  return *((char *)yvec_get(v, i));
}

static size_t yvec_len(const YVec *v) { return v->len; }

static size_t ystr_len(const YStr *s) { return s->len; }

static void yvec_free(YVec *v) {
  free(v->data);
  v->data = NULL;
  v->len = 0;
  v->cap = 0;
}

/* ── Y Runtime: Print ───────────────────── */
static void yprint_str(const YStr *s) { printf("%s", s->data); }

static void yprint_int(int64_t v) { printf("%lld", (long long)v); }

static void yprint_float(double v) { printf("%f", v); }

static void yprintln_str(const YStr *s) { printf("%s\n", s->data); }

/* ── Y Runtime: File I/O ────────────────── */
static YStr yfile_read_to_string(const YStr *path_str) {
  const char *path = path_str->data;
  FILE *f = fopen(path, "rb");
  if (!f) {
    fprintf(stderr, "Error: Cannot open file '%s'\n", path);
    exit(1);
  }
  fseek(f, 0, SEEK_END);
  long len = ftell(f);
  fseek(f, 0, SEEK_SET);
  char *buf = (char *)malloc(len + 1);
  fread(buf, 1, len, f);
  buf[len] = '\0';
  fclose(f);
  YStr result = {buf, (size_t)len, (size_t)(len + 1)};
  return result;
}

static void yfile_write(const YStr *path_str, const YStr *content) {
  const char *path = path_str->data;
  FILE *f = fopen(path, "wb");
  if (!f) {
    fprintf(stderr, "Error: Cannot write file '%s'\n", path);
    exit(1);
  }
  fwrite(content->data, 1, content->len, f);
  fclose(f);
}

/* ── User Code ───────────────────────────────── */

typedef struct Vec3 Vec3;
typedef struct AABB AABB;
typedef struct Sphere Sphere;
typedef struct BVHNode BVHNode;
typedef struct Storage Storage;
typedef struct BVH BVH;

struct Vec3 {
  float x;
  float y;
  float z;
};

struct AABB {
  Vec3 minimum;
  Vec3 maximum;
};

struct Sphere {
  Vec3 center;
  float radius;
  int32_t id;
};

struct BVHNode {
  AABB box;
  int64_t left;
  int64_t right;
  size_t start;
  size_t count;
};

struct Storage {
  size_t data;
};

struct BVH {
  Storage nodes;
  Storage spheres;
};

Vec3 Vec3_new(float x, float y, float z);
Vec3 Vec3_add(Vec3 a, Vec3 b);
Vec3 Vec3_sub(Vec3 a, Vec3 b);
Vec3 Vec3_mul(Vec3 a, float t);
Vec3 Vec3_min(Vec3 a, Vec3 b);
Vec3 Vec3_max(Vec3 a, Vec3 b);
AABB AABB_surrounding(AABB box0, AABB box1);
bool AABB_hit(const AABB *box, Vec3 r_orig, Vec3 r_dir, float t_min,
              float t_max);
BVHNode Storage_get_BVHNode(const Storage *v, size_t i);
Sphere Storage_get_Sphere(const Storage *v, size_t i);
void Storage_set_BVHNode(Storage *v, size_t i, BVHNode n);
void Storage_push_BVHNode(Storage *v, BVHNode n);
size_t Storage_len(const Storage *v);
int64_t build_bvh_recursive(Storage *nodes, Storage *spheres, size_t start,
                            size_t end);
bool bvh_hit(const Storage *nodes, const Storage *spheres, int64_t node_idx,
             Vec3 r_orig, Vec3 r_dir, float t_min, float t_max);
void main(void);

/* impl Vec3 */
Vec3 Vec3_new(float x, float y, float z) {
  return (Vec3){.x = x, .y = y, .z = z};
}

Vec3 Vec3_add(Vec3 a, Vec3 b) {
  return (Vec3){.x = (a.x + b.x), .y = (a.y + b.y), .z = (a.z + b.z)};
}

Vec3 Vec3_sub(Vec3 a, Vec3 b) {
  return (Vec3){.x = (a.x - b.x), .y = (a.y - b.y), .z = (a.z - b.z)};
}

Vec3 Vec3_mul(Vec3 a, float t) {
  return (Vec3){.x = (a.x * t), .y = (a.y * t), .z = (a.z * t)};
}

Vec3 Vec3_min(Vec3 a, Vec3 b) {
  float x = a.x;
  if ((b.x < x)) {
    x = b.x;
  }
  float y = a.y;
  if ((b.y < y)) {
    y = b.y;
  }
  float z = a.z;
  if ((b.z < z)) {
    z = b.z;
  }
  return (Vec3){.x = x, .y = y, .z = z};
}

Vec3 Vec3_max(Vec3 a, Vec3 b) {
  float x = a.x;
  if ((b.x > x)) {
    x = b.x;
  }
  float y = a.y;
  if ((b.y > y)) {
    y = b.y;
  }
  float z = a.z;
  if ((b.z > z)) {
    z = b.z;
  }
  return (Vec3){.x = x, .y = y, .z = z};
}

/* impl AABB */
AABB AABB_surrounding(AABB box0, AABB box1) {
  Vec3 small = Vec3_min(box0.minimum, box1.minimum);
  Vec3 big = Vec3_max(box0.maximum, box1.maximum);
  return (AABB){.minimum = small, .maximum = big};
}

bool AABB_hit(const AABB *box, Vec3 r_orig, Vec3 r_dir, float t_min,
              float t_max) {
  float invD = (1.0 / r_dir.x);
  float t0 = ((box.minimum.x - r_orig.x) * invD);
  float t1 = ((box.maximum.x - r_orig.x) * invD);
  if ((invD < 0.0)) {
    float tmp = t0;
    t0 = t1;
    t1 = tmp;
  }
  float t_near = t_min;
  if ((t0 > t_near)) {
    t_near = t0;
  }
  float t_far = t_max;
  if ((t1 < t_far)) {
    t_far = t1;
  }
  if ((t_far <= t_near)) {
    return false;
  }
  invD = (1.0 / r_dir.y);
  t0 = ((box.minimum.y - r_orig.y) * invD);
  t1 = ((box.maximum.y - r_orig.y) * invD);
  if ((invD < 0.0)) {
    float tmp = t0;
    t0 = t1;
    t1 = tmp;
  }
  if ((t0 > t_near)) {
    t_near = t0;
  }
  if ((t1 < t_far)) {
    t_far = t1;
  }
  if ((t_far <= t_near)) {
    return false;
  }
  invD = (1.0 / r_dir.z);
  t0 = ((box.minimum.z - r_orig.z) * invD);
  t1 = ((box.maximum.z - r_orig.z) * invD);
  if ((invD < 0.0)) {
    float tmp = t0;
    t0 = t1;
    t1 = tmp;
  }
  if ((t0 > t_near)) {
    t_near = t0;
  }
  if ((t1 < t_far)) {
    t_far = t1;
  }
  if ((t_far <= t_near)) {
    return false;
  }
  return true;
}

/* impl Storage */
BVHNode Storage_get_BVHNode(const Storage *v, size_t i) {
  BVHNode d = {0};
  return d;
}

Sphere Storage_get_Sphere(const Storage *v, size_t i) {
  Sphere d = {0};
  return d;
}

void Storage_set_BVHNode(Storage *v, size_t i, BVHNode n) {}

void Storage_push_BVHNode(Storage *v, BVHNode n) {}

size_t Storage_len(const Storage *v) { return 0; }

int64_t build_bvh_recursive(Storage *nodes, Storage *spheres, size_t start,
                            size_t end) {
  size_t span = (end - start);
  BVHNode node = {0};
  node.left = (0 - 1);
  node.right = (0 - 1);
  node.start = 0;
  node.count = 0;
  AABB main_box = {0};
  size_t i = start;
  while ((i < end)) {
    int32_t s = Storage_get_Sphere(spheres, i);
    int32_t r = Vec3_new(s.radius, s.radius, s.radius);
    int32_t s_box = (AABB){.minimum = Vec3_sub(s.center, r),
                           .maximum = Vec3_add(s.center, r)};
    if ((i == start)) {
      main_box = s_box;
    } else {
      main_box = AABB_surrounding(main_box, s_box);
    }
    i = (i + 1);
  }
  node.box = main_box;
  if ((span <= 2)) {
    node.left = (0 - 1);
    node.right = (0 - 1);
    node.start = start;
    node.count = span;
    Storage_push_BVHNode(nodes, node);
    return 0;
  } else {
    int32_t diff = Vec3_sub(main_box.maximum, main_box.minimum);
    int32_t axis = 0;
    if ((diff.y > diff.x)) {
      axis = 1;
    }
    float max_val = diff.x;
    if ((axis == 1)) {
      max_val = diff.y;
    }
    if ((diff.z > max_val)) {
      axis = 2;
    }
    size_t mid = (start + (span / 2));
    int32_t node_idx_usize = Storage_len(nodes);
    Storage_push_BVHNode(nodes, node);
    int32_t left_idx = build_bvh_recursive(nodes, spheres, start, mid);
    int32_t right_idx = build_bvh_recursive(nodes, spheres, mid, end);
    int32_t updated_node = Storage_get_BVHNode(nodes, node_idx_usize);
    updated_node.left = left_idx;
    updated_node.right = right_idx;
    updated_node.count = 0;
    Storage_set_BVHNode(nodes, node_idx_usize, updated_node);
    return 0;
  }
}

bool bvh_hit(const Storage *nodes, const Storage *spheres, int64_t node_idx,
             Vec3 r_orig, Vec3 r_dir, float t_min, float t_max) {
  if ((node_idx == (0 - 1))) {
    return false;
  }
  size_t node_idx_usize = 0;
  int32_t node = Storage_get_BVHNode(nodes, node_idx_usize);
  if ((!AABB_hit((&node.box), r_orig, r_dir, t_min, t_max))) {
    return false;
  }
  if ((node.count > 0)) {
    bool hit_anything = false;
    size_t i = 0;
    while ((i < node.count)) {
      int32_t s = Storage_get_Sphere(spheres, (node.start + i));
      i = (i + 1);
    }
    return hit_anything;
  } else {
    int32_t hit_left =
        bvh_hit(nodes, spheres, node.left, r_orig, r_dir, t_min, t_max);
    int32_t hit_right =
        bvh_hit(nodes, spheres, node.right, r_orig, r_dir, t_min, t_max);
    return (hit_left || hit_right);
  }
}

void main(void) {
  printf("%s\n", (ystr_new("BVH Structures Initialized in Y.")).data);
}

