[package]
name = "Y-compiler"
version = "1.0.0"
edition = "2021"
description = "Y compiler with LLVM IR, PTX, CPU, ZK (R1CS), and Co-Processor backends."

[lib]
name = "y"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "Y"
path = "src/main.rs"

[[bin]]
name = "ysu_gpu_probe"
path = "src/ysu_gpu_probe.rs"

[[bin]]
name = "ypm"
path = "src/ypm.rs"

[[bin]]
name = "autotune_verify"
path = "src/bin/autotune_verify.rs"



[dependencies]

[features]
default = []
zk = []

