; ================================================
;  Generated by Y Compiler — LLVM IR Backend
;  Hardware Profile: AVX=true, AVX512=true, L2 Line=64B
; ================================================

target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

attributes #0 = { "target-cpu"="skylake-avx512" "target-features"="+avx512f,+avx512cd,+avx512bw,+avx512dq,+avx512vl" }

; --- Struct Definitions ---
%Vec3 = type { float, float, float }
%AABB = type { %Vec3, %Vec3 }
%Sphere = type { %Vec3, float, i32 }
%BVHNode = type { %AABB, i64, i64, i64, i64, i64 }
%Storage = type { i64 }
%BVH = type { %Storage, %Storage }

; --- Enum Definitions ---

; --- External Runtime Declarations ---
declare ptr @ystr_new(ptr)
declare void @ystr_push(ptr, i8)
declare void @ystr_push_str(ptr, ptr)
declare i1 @ystr_eq_cstr(ptr, ptr)
declare i64 @ystr_len(ptr)
declare i8 @ystr_char_at(ptr, i64)
declare ptr @ystr_clone(ptr)
declare ptr @yvec_new(i64)
declare void @yvec_push(ptr, ptr)
declare ptr @yvec_get(ptr, i64)
declare i64 @yvec_len(ptr)
declare ptr @yfile_read_to_string(ptr)
declare void @yfile_write(ptr, ptr)
declare i32 @printf(ptr, ...)
declare ptr @malloc(i64)
declare void @free(ptr)
declare void @exit(i32) noreturn
declare void @println(ptr)
declare void @print_int(i64)
declare void @llvm.prefetch.p0(ptr nocapture readonly, i32, i32, i32)
declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg)

; --- String Constants ---
@.str.0 = private unnamed_addr constant [38 x i8] c"BVH Structures Initialized in Y.\00"

@.fmt.sn = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt.s = private unnamed_addr constant [3 x i8] c"%s\00"
@.fmt.d = private unnamed_addr constant [4 x i8] c"%ld\00"

; impl Vec3
define %Vec3 @Vec3_new(float %x.arg, float %y.arg, float %z.arg) #0 {
entry:
  %x = alloca float
  store float %x.arg, ptr %x
  %y = alloca float
  store float %y.arg, ptr %y
  %z = alloca float
  store float %z.arg, ptr %z
  %_t1 = load float, ptr %x
  %_t2 = insertvalue %Vec3 undef, float %_t1, 0
  %_t3 = load float, ptr %y
  %_t4 = insertvalue %Vec3 %_t2, float %_t3, 1
  %_t5 = load float, ptr %z
  %_t6 = insertvalue %Vec3 %_t4, float %_t5, 2
  ret %Vec3 %_t6
}

define %Vec3 @Vec3_add(%Vec3 %a.arg, %Vec3 %b.arg) #0 {
entry:
  %a = alloca %Vec3
  store %Vec3 %a.arg, ptr %a
  %b = alloca %Vec3
  store %Vec3 %b.arg, ptr %b
  ; lvalue .x
  %_t1 = getelementptr %Vec3, ptr %a, i32 0, i32 0
  %_t2 = load float, ptr %_t1
  ; lvalue .x
  %_t3 = getelementptr %Vec3, ptr %b, i32 0, i32 0
  %_t4 = load float, ptr %_t3
  %_t5 = fadd float %_t2, %_t4
  %_t6 = insertvalue %Vec3 undef, float %_t5, 0
  ; lvalue .y
  %_t7 = getelementptr %Vec3, ptr %a, i32 0, i32 1
  %_t8 = load float, ptr %_t7
  ; lvalue .y
  %_t9 = getelementptr %Vec3, ptr %b, i32 0, i32 1
  %_t10 = load float, ptr %_t9
  %_t11 = fadd float %_t8, %_t10
  %_t12 = insertvalue %Vec3 %_t6, float %_t11, 1
  ; lvalue .z
  %_t13 = getelementptr %Vec3, ptr %a, i32 0, i32 2
  %_t14 = load float, ptr %_t13
  ; lvalue .z
  %_t15 = getelementptr %Vec3, ptr %b, i32 0, i32 2
  %_t16 = load float, ptr %_t15
  %_t17 = fadd float %_t14, %_t16
  %_t18 = insertvalue %Vec3 %_t12, float %_t17, 2
  ret %Vec3 %_t18
}

define %Vec3 @Vec3_sub(%Vec3 %a.arg, %Vec3 %b.arg) #0 {
entry:
  %a = alloca %Vec3
  store %Vec3 %a.arg, ptr %a
  %b = alloca %Vec3
  store %Vec3 %b.arg, ptr %b
  ; lvalue .x
  %_t1 = getelementptr %Vec3, ptr %a, i32 0, i32 0
  %_t2 = load float, ptr %_t1
  ; lvalue .x
  %_t3 = getelementptr %Vec3, ptr %b, i32 0, i32 0
  %_t4 = load float, ptr %_t3
  %_t5 = fsub float %_t2, %_t4
  %_t6 = insertvalue %Vec3 undef, float %_t5, 0
  ; lvalue .y
  %_t7 = getelementptr %Vec3, ptr %a, i32 0, i32 1
  %_t8 = load float, ptr %_t7
  ; lvalue .y
  %_t9 = getelementptr %Vec3, ptr %b, i32 0, i32 1
  %_t10 = load float, ptr %_t9
  %_t11 = fsub float %_t8, %_t10
  %_t12 = insertvalue %Vec3 %_t6, float %_t11, 1
  ; lvalue .z
  %_t13 = getelementptr %Vec3, ptr %a, i32 0, i32 2
  %_t14 = load float, ptr %_t13
  ; lvalue .z
  %_t15 = getelementptr %Vec3, ptr %b, i32 0, i32 2
  %_t16 = load float, ptr %_t15
  %_t17 = fsub float %_t14, %_t16
  %_t18 = insertvalue %Vec3 %_t12, float %_t17, 2
  ret %Vec3 %_t18
}

define %Vec3 @Vec3_mul(%Vec3 %a.arg, float %t.arg) #0 {
entry:
  %a = alloca %Vec3
  store %Vec3 %a.arg, ptr %a
  %t = alloca float
  store float %t.arg, ptr %t
  ; lvalue .x
  %_t1 = getelementptr %Vec3, ptr %a, i32 0, i32 0
  %_t2 = load float, ptr %_t1
  %_t3 = load float, ptr %t
  %_t4 = fmul float %_t2, %_t3
  %_t5 = insertvalue %Vec3 undef, float %_t4, 0
  ; lvalue .y
  %_t6 = getelementptr %Vec3, ptr %a, i32 0, i32 1
  %_t7 = load float, ptr %_t6
  %_t8 = load float, ptr %t
  %_t9 = fmul float %_t7, %_t8
  %_t10 = insertvalue %Vec3 %_t5, float %_t9, 1
  ; lvalue .z
  %_t11 = getelementptr %Vec3, ptr %a, i32 0, i32 2
  %_t12 = load float, ptr %_t11
  %_t13 = load float, ptr %t
  %_t14 = fmul float %_t12, %_t13
  %_t15 = insertvalue %Vec3 %_t10, float %_t14, 2
  ret %Vec3 %_t15
}

define %Vec3 @Vec3_min(%Vec3 %a.arg, %Vec3 %b.arg) #0 {
entry:
  %a = alloca %Vec3
  store %Vec3 %a.arg, ptr %a
  %b = alloca %Vec3
  store %Vec3 %b.arg, ptr %b
  %x = alloca float
  %y = alloca float
  %z = alloca float
  ; lvalue .x
  %_t1 = getelementptr %Vec3, ptr %a, i32 0, i32 0
  %_t2 = load float, ptr %_t1
  store float %_t2, ptr %x
  ; lvalue .x
  %_t3 = getelementptr %Vec3, ptr %b, i32 0, i32 0
  %_t4 = load float, ptr %_t3
  %_t5 = load float, ptr %x
  %_t6 = fcmp olt float %_t4, %_t5
  br i1 %_t6, label %then.1, label %merge.3
then.1:
  ; lvalue .x
  %_t7 = getelementptr %Vec3, ptr %b, i32 0, i32 0
  %_t8 = load float, ptr %_t7
  store float %_t8, ptr %x
  br label %merge.3
merge.3:
  ; lvalue .y
  %_t9 = getelementptr %Vec3, ptr %a, i32 0, i32 1
  %_t10 = load float, ptr %_t9
  store float %_t10, ptr %y
  ; lvalue .y
  %_t11 = getelementptr %Vec3, ptr %b, i32 0, i32 1
  %_t12 = load float, ptr %_t11
  %_t13 = load float, ptr %y
  %_t14 = fcmp olt float %_t12, %_t13
  br i1 %_t14, label %then.4, label %merge.6
then.4:
  ; lvalue .y
  %_t15 = getelementptr %Vec3, ptr %b, i32 0, i32 1
  %_t16 = load float, ptr %_t15
  store float %_t16, ptr %y
  br label %merge.6
merge.6:
  ; lvalue .z
  %_t17 = getelementptr %Vec3, ptr %a, i32 0, i32 2
  %_t18 = load float, ptr %_t17
  store float %_t18, ptr %z
  ; lvalue .z
  %_t19 = getelementptr %Vec3, ptr %b, i32 0, i32 2
  %_t20 = load float, ptr %_t19
  %_t21 = load float, ptr %z
  %_t22 = fcmp olt float %_t20, %_t21
  br i1 %_t22, label %then.7, label %merge.9
then.7:
  ; lvalue .z
  %_t23 = getelementptr %Vec3, ptr %b, i32 0, i32 2
  %_t24 = load float, ptr %_t23
  store float %_t24, ptr %z
  br label %merge.9
merge.9:
  %_t25 = load float, ptr %x
  %_t26 = insertvalue %Vec3 undef, float %_t25, 0
  %_t27 = load float, ptr %y
  %_t28 = insertvalue %Vec3 %_t26, float %_t27, 1
  %_t29 = load float, ptr %z
  %_t30 = insertvalue %Vec3 %_t28, float %_t29, 2
  ret %Vec3 %_t30
}

define %Vec3 @Vec3_max(%Vec3 %a.arg, %Vec3 %b.arg) #0 {
entry:
  %a = alloca %Vec3
  store %Vec3 %a.arg, ptr %a
  %b = alloca %Vec3
  store %Vec3 %b.arg, ptr %b
  %x = alloca float
  %y = alloca float
  %z = alloca float
  ; lvalue .x
  %_t1 = getelementptr %Vec3, ptr %a, i32 0, i32 0
  %_t2 = load float, ptr %_t1
  store float %_t2, ptr %x
  ; lvalue .x
  %_t3 = getelementptr %Vec3, ptr %b, i32 0, i32 0
  %_t4 = load float, ptr %_t3
  %_t5 = load float, ptr %x
  %_t6 = fcmp ogt float %_t4, %_t5
  br i1 %_t6, label %then.10, label %merge.12
then.10:
  ; lvalue .x
  %_t7 = getelementptr %Vec3, ptr %b, i32 0, i32 0
  %_t8 = load float, ptr %_t7
  store float %_t8, ptr %x
  br label %merge.12
merge.12:
  ; lvalue .y
  %_t9 = getelementptr %Vec3, ptr %a, i32 0, i32 1
  %_t10 = load float, ptr %_t9
  store float %_t10, ptr %y
  ; lvalue .y
  %_t11 = getelementptr %Vec3, ptr %b, i32 0, i32 1
  %_t12 = load float, ptr %_t11
  %_t13 = load float, ptr %y
  %_t14 = fcmp ogt float %_t12, %_t13
  br i1 %_t14, label %then.13, label %merge.15
then.13:
  ; lvalue .y
  %_t15 = getelementptr %Vec3, ptr %b, i32 0, i32 1
  %_t16 = load float, ptr %_t15
  store float %_t16, ptr %y
  br label %merge.15
merge.15:
  ; lvalue .z
  %_t17 = getelementptr %Vec3, ptr %a, i32 0, i32 2
  %_t18 = load float, ptr %_t17
  store float %_t18, ptr %z
  ; lvalue .z
  %_t19 = getelementptr %Vec3, ptr %b, i32 0, i32 2
  %_t20 = load float, ptr %_t19
  %_t21 = load float, ptr %z
  %_t22 = fcmp ogt float %_t20, %_t21
  br i1 %_t22, label %then.16, label %merge.18
then.16:
  ; lvalue .z
  %_t23 = getelementptr %Vec3, ptr %b, i32 0, i32 2
  %_t24 = load float, ptr %_t23
  store float %_t24, ptr %z
  br label %merge.18
merge.18:
  %_t25 = load float, ptr %x
  %_t26 = insertvalue %Vec3 undef, float %_t25, 0
  %_t27 = load float, ptr %y
  %_t28 = insertvalue %Vec3 %_t26, float %_t27, 1
  %_t29 = load float, ptr %z
  %_t30 = insertvalue %Vec3 %_t28, float %_t29, 2
  ret %Vec3 %_t30
}

; impl AABB
define %AABB @AABB_surrounding(%AABB %box0.arg, %AABB %box1.arg) #0 {
entry:
  %box0 = alloca %AABB
  store %AABB %box0.arg, ptr %box0
  %box1 = alloca %AABB
  store %AABB %box1.arg, ptr %box1
  %small = alloca %Vec3
  %big = alloca %Vec3
  ; lvalue .minimum
  %_t1 = getelementptr %AABB, ptr %box0, i32 0, i32 0
  %_t2 = load %Vec3, ptr %_t1
  ; lvalue .minimum
  %_t3 = getelementptr %AABB, ptr %box1, i32 0, i32 0
  %_t4 = load %Vec3, ptr %_t3
  %_t5 = call %Vec3 @Vec3_min(%Vec3 %_t2, %Vec3 %_t4)
  %_t6 = getelementptr %Vec3, ptr null, i32 1
  %_t7 = ptrtoint ptr %_t6 to i64
  %_t8 = alloca %Vec3
  store %Vec3 %_t5, ptr %_t8
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %small, ptr align 8 %_t8, i64 %_t7, i1 false)
  ; lvalue .maximum
  %_t9 = getelementptr %AABB, ptr %box0, i32 0, i32 1
  %_t10 = load %Vec3, ptr %_t9
  ; lvalue .maximum
  %_t11 = getelementptr %AABB, ptr %box1, i32 0, i32 1
  %_t12 = load %Vec3, ptr %_t11
  %_t13 = call %Vec3 @Vec3_max(%Vec3 %_t10, %Vec3 %_t12)
  %_t14 = getelementptr %Vec3, ptr null, i32 1
  %_t15 = ptrtoint ptr %_t14 to i64
  %_t16 = alloca %Vec3
  store %Vec3 %_t13, ptr %_t16
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %big, ptr align 8 %_t16, i64 %_t15, i1 false)
  %_t17 = load %Vec3, ptr %small
  %_t18 = insertvalue %AABB undef, %Vec3 %_t17, 0
  %_t19 = load %Vec3, ptr %big
  %_t20 = insertvalue %AABB %_t18, %Vec3 %_t19, 1
  ret %AABB %_t20
}

define i1 @AABB_hit(ptr %box.arg, %Vec3 %r_orig.arg, %Vec3 %r_dir.arg, float %t_min.arg, float %t_max.arg) #0 {
entry:
  %box = alloca ptr
  store ptr %box.arg, ptr %box
  %r_orig = alloca %Vec3
  store %Vec3 %r_orig.arg, ptr %r_orig
  %r_dir = alloca %Vec3
  store %Vec3 %r_dir.arg, ptr %r_dir
  %t_min = alloca float
  store float %t_min.arg, ptr %t_min
  %t_max = alloca float
  store float %t_max.arg, ptr %t_max
  %invD_x = alloca float
  %t0_x_raw = alloca float
  %t1_x_raw = alloca float
  %t0_x = alloca float
  %t1_x = alloca float
  %t_near = alloca float
  %t_far = alloca float
  %invD_y = alloca float
  %t0_y_raw = alloca float
  %t1_y_raw = alloca float
  %t0_y = alloca float
  %t1_y = alloca float
  %invD_z = alloca float
  %t0_z_raw = alloca float
  %t1_z_raw = alloca float
  %t0_z = alloca float
  %t1_z = alloca float
  ; lvalue .x
  %_t1 = getelementptr %Vec3, ptr %r_dir, i32 0, i32 0
  %_t2 = load float, ptr %_t1
  %_t3 = fpext float %_t2 to double
  %_t4 = fdiv double 1.000000e0, %_t3
  %_t5 = fptrunc double %_t4 to float
  store float %_t5, ptr %invD_x
  ; lvalue .minimum
  %_t6 = getelementptr %AABB, ptr %box, i32 0, i32 0
  ; lvalue .x
  %_t7 = getelementptr %Vec3, ptr %_t6, i32 0, i32 0
  %_t8 = load float, ptr %_t7
  ; lvalue .x
  %_t9 = getelementptr %Vec3, ptr %r_orig, i32 0, i32 0
  %_t10 = load float, ptr %_t9
  %_t11 = fsub float %_t8, %_t10
  %_t12 = load float, ptr %invD_x
  %_t13 = fmul float %_t11, %_t12
  store float %_t13, ptr %t0_x_raw
  ; lvalue .maximum
  %_t14 = getelementptr %AABB, ptr %box, i32 0, i32 1
  ; lvalue .x
  %_t15 = getelementptr %Vec3, ptr %_t14, i32 0, i32 0
  %_t16 = load float, ptr %_t15
  ; lvalue .x
  %_t17 = getelementptr %Vec3, ptr %r_orig, i32 0, i32 0
  %_t18 = load float, ptr %_t17
  %_t19 = fsub float %_t16, %_t18
  %_t20 = load float, ptr %invD_x
  %_t21 = fmul float %_t19, %_t20
  store float %_t21, ptr %t1_x_raw
  %_t22 = load float, ptr %t0_x_raw
  store float %_t22, ptr %t0_x
  %_t23 = load float, ptr %t1_x_raw
  %_t24 = load float, ptr %t0_x
  %_t25 = fcmp olt float %_t23, %_t24
  br i1 %_t25, label %then.19, label %merge.21
then.19:
  %_t26 = load float, ptr %t1_x_raw
  store float %_t26, ptr %t0_x
  br label %merge.21
merge.21:
  %_t27 = load float, ptr %t1_x_raw
  store float %_t27, ptr %t1_x
  %_t28 = load float, ptr %t0_x_raw
  %_t29 = load float, ptr %t1_x
  %_t30 = fcmp ogt float %_t28, %_t29
  br i1 %_t30, label %then.22, label %merge.24
then.22:
  %_t31 = load float, ptr %t0_x_raw
  store float %_t31, ptr %t1_x
  br label %merge.24
merge.24:
  %_t32 = load float, ptr %t_min
  store float %_t32, ptr %t_near
  %_t33 = load float, ptr %t0_x
  %_t34 = load float, ptr %t_near
  %_t35 = fcmp ogt float %_t33, %_t34
  br i1 %_t35, label %then.25, label %merge.27
then.25:
  %_t36 = load float, ptr %t0_x
  store float %_t36, ptr %t_near
  br label %merge.27
merge.27:
  %_t37 = load float, ptr %t_max
  store float %_t37, ptr %t_far
  %_t38 = load float, ptr %t1_x
  %_t39 = load float, ptr %t_far
  %_t40 = fcmp olt float %_t38, %_t39
  br i1 %_t40, label %then.28, label %merge.30
then.28:
  %_t41 = load float, ptr %t1_x
  store float %_t41, ptr %t_far
  br label %merge.30
merge.30:
  %_t42 = load float, ptr %t_far
  %_t43 = load float, ptr %t_near
  %_t44 = fcmp ole float %_t42, %_t43
  br i1 %_t44, label %then.31, label %merge.33
then.31:
  ret i1 0
merge.33:
  ; lvalue .y
  %_t45 = getelementptr %Vec3, ptr %r_dir, i32 0, i32 1
  %_t46 = load float, ptr %_t45
  %_t47 = fpext float %_t46 to double
  %_t48 = fdiv double 1.000000e0, %_t47
  %_t49 = fptrunc double %_t48 to float
  store float %_t49, ptr %invD_y
  ; lvalue .minimum
  %_t50 = getelementptr %AABB, ptr %box, i32 0, i32 0
  ; lvalue .y
  %_t51 = getelementptr %Vec3, ptr %_t50, i32 0, i32 1
  %_t52 = load float, ptr %_t51
  ; lvalue .y
  %_t53 = getelementptr %Vec3, ptr %r_orig, i32 0, i32 1
  %_t54 = load float, ptr %_t53
  %_t55 = fsub float %_t52, %_t54
  %_t56 = load float, ptr %invD_y
  %_t57 = fmul float %_t55, %_t56
  store float %_t57, ptr %t0_y_raw
  ; lvalue .maximum
  %_t58 = getelementptr %AABB, ptr %box, i32 0, i32 1
  ; lvalue .y
  %_t59 = getelementptr %Vec3, ptr %_t58, i32 0, i32 1
  %_t60 = load float, ptr %_t59
  ; lvalue .y
  %_t61 = getelementptr %Vec3, ptr %r_orig, i32 0, i32 1
  %_t62 = load float, ptr %_t61
  %_t63 = fsub float %_t60, %_t62
  %_t64 = load float, ptr %invD_y
  %_t65 = fmul float %_t63, %_t64
  store float %_t65, ptr %t1_y_raw
  %_t66 = load float, ptr %t0_y_raw
  store float %_t66, ptr %t0_y
  %_t67 = load float, ptr %t1_y_raw
  %_t68 = load float, ptr %t0_y
  %_t69 = fcmp olt float %_t67, %_t68
  br i1 %_t69, label %then.34, label %merge.36
then.34:
  %_t70 = load float, ptr %t1_y_raw
  store float %_t70, ptr %t0_y
  br label %merge.36
merge.36:
  %_t71 = load float, ptr %t1_y_raw
  store float %_t71, ptr %t1_y
  %_t72 = load float, ptr %t0_y_raw
  %_t73 = load float, ptr %t1_y
  %_t74 = fcmp ogt float %_t72, %_t73
  br i1 %_t74, label %then.37, label %merge.39
then.37:
  %_t75 = load float, ptr %t0_y_raw
  store float %_t75, ptr %t1_y
  br label %merge.39
merge.39:
  %_t76 = load float, ptr %t0_y
  %_t77 = load float, ptr %t_near
  %_t78 = fcmp ogt float %_t76, %_t77
  br i1 %_t78, label %then.40, label %merge.42
then.40:
  %_t79 = load float, ptr %t0_y
  store float %_t79, ptr %t_near
  br label %merge.42
merge.42:
  %_t80 = load float, ptr %t1_y
  %_t81 = load float, ptr %t_far
  %_t82 = fcmp olt float %_t80, %_t81
  br i1 %_t82, label %then.43, label %merge.45
then.43:
  %_t83 = load float, ptr %t1_y
  store float %_t83, ptr %t_far
  br label %merge.45
merge.45:
  %_t84 = load float, ptr %t_far
  %_t85 = load float, ptr %t_near
  %_t86 = fcmp ole float %_t84, %_t85
  br i1 %_t86, label %then.46, label %merge.48
then.46:
  ret i1 0
merge.48:
  ; lvalue .z
  %_t87 = getelementptr %Vec3, ptr %r_dir, i32 0, i32 2
  %_t88 = load float, ptr %_t87
  %_t89 = fpext float %_t88 to double
  %_t90 = fdiv double 1.000000e0, %_t89
  %_t91 = fptrunc double %_t90 to float
  store float %_t91, ptr %invD_z
  ; lvalue .minimum
  %_t92 = getelementptr %AABB, ptr %box, i32 0, i32 0
  ; lvalue .z
  %_t93 = getelementptr %Vec3, ptr %_t92, i32 0, i32 2
  %_t94 = load float, ptr %_t93
  ; lvalue .z
  %_t95 = getelementptr %Vec3, ptr %r_orig, i32 0, i32 2
  %_t96 = load float, ptr %_t95
  %_t97 = fsub float %_t94, %_t96
  %_t98 = load float, ptr %invD_z
  %_t99 = fmul float %_t97, %_t98
  store float %_t99, ptr %t0_z_raw
  ; lvalue .maximum
  %_t100 = getelementptr %AABB, ptr %box, i32 0, i32 1
  ; lvalue .z
  %_t101 = getelementptr %Vec3, ptr %_t100, i32 0, i32 2
  %_t102 = load float, ptr %_t101
  ; lvalue .z
  %_t103 = getelementptr %Vec3, ptr %r_orig, i32 0, i32 2
  %_t104 = load float, ptr %_t103
  %_t105 = fsub float %_t102, %_t104
  %_t106 = load float, ptr %invD_z
  %_t107 = fmul float %_t105, %_t106
  store float %_t107, ptr %t1_z_raw
  %_t108 = load float, ptr %t0_z_raw
  store float %_t108, ptr %t0_z
  %_t109 = load float, ptr %t1_z_raw
  %_t110 = load float, ptr %t0_z
  %_t111 = fcmp olt float %_t109, %_t110
  br i1 %_t111, label %then.49, label %merge.51
then.49:
  %_t112 = load float, ptr %t1_z_raw
  store float %_t112, ptr %t0_z
  br label %merge.51
merge.51:
  %_t113 = load float, ptr %t1_z_raw
  store float %_t113, ptr %t1_z
  %_t114 = load float, ptr %t0_z_raw
  %_t115 = load float, ptr %t1_z
  %_t116 = fcmp ogt float %_t114, %_t115
  br i1 %_t116, label %then.52, label %merge.54
then.52:
  %_t117 = load float, ptr %t0_z_raw
  store float %_t117, ptr %t1_z
  br label %merge.54
merge.54:
  %_t118 = load float, ptr %t0_z
  %_t119 = load float, ptr %t_near
  %_t120 = fcmp ogt float %_t118, %_t119
  br i1 %_t120, label %then.55, label %merge.57
then.55:
  %_t121 = load float, ptr %t0_z
  store float %_t121, ptr %t_near
  br label %merge.57
merge.57:
  %_t122 = load float, ptr %t1_z
  %_t123 = load float, ptr %t_far
  %_t124 = fcmp olt float %_t122, %_t123
  br i1 %_t124, label %then.58, label %merge.60
then.58:
  %_t125 = load float, ptr %t1_z
  store float %_t125, ptr %t_far
  br label %merge.60
merge.60:
  %_t126 = load float, ptr %t_far
  %_t127 = load float, ptr %t_near
  %_t128 = fcmp ole float %_t126, %_t127
  br i1 %_t128, label %then.61, label %merge.63
then.61:
  ret i1 0
merge.63:
  ret i1 1
}

; impl Storage
define %BVHNode @Storage_get_BVHNode(ptr %v.arg, i64 %i.arg) #0 {
entry:
  %v = alloca ptr
  store ptr %v.arg, ptr %v
  %i = alloca i64
  store i64 %i.arg, ptr %i
  %d = alloca %BVHNode
  %_t1 = getelementptr %BVHNode, ptr null, i32 1
  %_t2 = ptrtoint ptr %_t1 to i64
  call void @llvm.memset.p0.i64(ptr %d, i8 0, i64 %_t2, i1 false)
  %_t3 = load %BVHNode, ptr %d
  ret %BVHNode %_t3
}

define %Sphere @Storage_get_Sphere(ptr %v.arg, i64 %i.arg) #0 {
entry:
  %v = alloca ptr
  store ptr %v.arg, ptr %v
  %i = alloca i64
  store i64 %i.arg, ptr %i
  %d = alloca %Sphere
  %_t1 = getelementptr %Sphere, ptr null, i32 1
  %_t2 = ptrtoint ptr %_t1 to i64
  call void @llvm.memset.p0.i64(ptr %d, i8 0, i64 %_t2, i1 false)
  %_t3 = load %Sphere, ptr %d
  ret %Sphere %_t3
}

define void @Storage_set_BVHNode(ptr %v.arg, i64 %i.arg, %BVHNode %n.arg) #0 {
entry:
  %v = alloca ptr
  store ptr %v.arg, ptr %v
  %i = alloca i64
  store i64 %i.arg, ptr %i
  %n = alloca %BVHNode
  store %BVHNode %n.arg, ptr %n
  ret void
}

define void @Storage_push_BVHNode(ptr %v.arg, %BVHNode %n.arg) #0 {
entry:
  %v = alloca ptr
  store ptr %v.arg, ptr %v
  %n = alloca %BVHNode
  store %BVHNode %n.arg, ptr %n
  ret void
}

define i64 @Storage_len(ptr %v.arg) #0 {
entry:
  %v = alloca ptr
  store ptr %v.arg, ptr %v
  %_t1 = sext i32 0 to i64
  ret i64 %_t1
}

define i64 @build_bvh_recursive(ptr %nodes.arg, ptr %spheres.arg, i64 %start.arg, i64 %end.arg) #0 {
entry:
  %nodes = alloca ptr
  store ptr %nodes.arg, ptr %nodes
  %spheres = alloca ptr
  store ptr %spheres.arg, ptr %spheres
  %start = alloca i64
  store i64 %start.arg, ptr %start
  %end = alloca i64
  store i64 %end.arg, ptr %end
  %span = alloca i64
  %node = alloca %BVHNode
  %main_box = alloca %AABB
  %i = alloca i64
  %s = alloca %Sphere
  %r = alloca %Vec3
  %s_box = alloca %AABB
  %diff = alloca %Vec3
  %axis = alloca i32
  %max_val = alloca float
  %mid = alloca i64
  %node_idx_usize = alloca i64
  %left_idx = alloca i64
  %right_idx = alloca i64
  %updated_node = alloca %BVHNode
  %_t1 = load i64, ptr %end
  %_t2 = load i64, ptr %start
  %_t3 = sub i64 %_t1, %_t2
  store i64 %_t3, ptr %span
  %_t4 = getelementptr %BVHNode, ptr null, i32 1
  %_t5 = ptrtoint ptr %_t4 to i64
  call void @llvm.memset.p0.i64(ptr %node, i8 0, i64 %_t5, i1 false)
  ; lvalue .left
  %_t6 = getelementptr %BVHNode, ptr %node, i32 0, i32 1
  %_t7 = sub i32 0, 1
  %_t8 = sext i32 %_t7 to i64
  store i64 %_t8, ptr %_t6
  ; lvalue .right
  %_t9 = getelementptr %BVHNode, ptr %node, i32 0, i32 2
  %_t10 = sub i32 0, 1
  %_t11 = sext i32 %_t10 to i64
  store i64 %_t11, ptr %_t9
  ; lvalue .start
  %_t12 = getelementptr %BVHNode, ptr %node, i32 0, i32 3
  %_t13 = sext i32 0 to i64
  store i64 %_t13, ptr %_t12
  ; lvalue .count
  %_t14 = getelementptr %BVHNode, ptr %node, i32 0, i32 4
  %_t15 = sext i32 0 to i64
  store i64 %_t15, ptr %_t14
  %_t16 = getelementptr %AABB, ptr null, i32 1
  %_t17 = ptrtoint ptr %_t16 to i64
  call void @llvm.memset.p0.i64(ptr %main_box, i8 0, i64 %_t17, i1 false)
  %_t18 = load i64, ptr %start
  store i64 %_t18, ptr %i
  br label %while.cond.64
while.cond.64:
  %_t19 = load i64, ptr %i
  %_t20 = load i64, ptr %end
  %_t21 = icmp slt i64 %_t19, %_t20
  br i1 %_t21, label %while.body.65, label %while.end.66
while.body.65:
  %_t22 = load ptr, ptr %spheres
  %_t23 = load i64, ptr %i
  %_t24 = call %Sphere @Storage_get_Sphere(ptr %_t22, i64 %_t23)
  %_t25 = getelementptr %Sphere, ptr null, i32 1
  %_t26 = ptrtoint ptr %_t25 to i64
  %_t27 = alloca %Sphere
  store %Sphere %_t24, ptr %_t27
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %s, ptr align 8 %_t27, i64 %_t26, i1 false)
  ; lvalue .radius
  %_t28 = getelementptr %Sphere, ptr %s, i32 0, i32 1
  %_t29 = load float, ptr %_t28
  ; lvalue .radius
  %_t30 = getelementptr %Sphere, ptr %s, i32 0, i32 1
  %_t31 = load float, ptr %_t30
  ; lvalue .radius
  %_t32 = getelementptr %Sphere, ptr %s, i32 0, i32 1
  %_t33 = load float, ptr %_t32
  %_t34 = call %Vec3 @Vec3_new(%F32 %_t29, %F32 %_t31, %F32 %_t33)
  %_t35 = getelementptr %Vec3, ptr null, i32 1
  %_t36 = ptrtoint ptr %_t35 to i64
  %_t37 = alloca %Vec3
  store %Vec3 %_t34, ptr %_t37
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %r, ptr align 8 %_t37, i64 %_t36, i1 false)
  ; lvalue .center
  %_t38 = getelementptr %Sphere, ptr %s, i32 0, i32 0
  %_t39 = load %Vec3, ptr %_t38
  %_t40 = load %Vec3, ptr %r
  %_t41 = call %Vec3 @Vec3_sub(%Vec3 %_t39, %Vec3 %_t40)
  %_t42 = insertvalue %AABB undef, %Vec3 %_t41, 0
  ; lvalue .center
  %_t43 = getelementptr %Sphere, ptr %s, i32 0, i32 0
  %_t44 = load %Vec3, ptr %_t43
  %_t45 = load %Vec3, ptr %r
  %_t46 = call %Vec3 @Vec3_add(%Vec3 %_t44, %Vec3 %_t45)
  %_t47 = insertvalue %AABB %_t42, %Vec3 %_t46, 1
  %_t48 = getelementptr %AABB, ptr null, i32 1
  %_t49 = ptrtoint ptr %_t48 to i64
  %_t50 = alloca %AABB
  store %AABB %_t47, ptr %_t50
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %s_box, ptr align 8 %_t50, i64 %_t49, i1 false)
  %_t51 = load i64, ptr %i
  %_t52 = load i64, ptr %start
  %_t53 = icmp eq i64 %_t51, %_t52
  br i1 %_t53, label %then.67, label %else.68
then.67:
  %_t54 = load %AABB, ptr %s_box
  %_t55 = getelementptr %AABB, ptr null, i32 1
  %_t56 = ptrtoint ptr %_t55 to i64
  %_t57 = alloca %AABB
  store %AABB %_t54, ptr %_t57
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %main_box, ptr align 8 %_t57, i64 %_t56, i1 false)
  br label %merge.69
else.68:
  %_t58 = load %AABB, ptr %main_box
  %_t59 = load %AABB, ptr %s_box
  %_t60 = call %AABB @AABB_surrounding(%AABB %_t58, %AABB %_t59)
  %_t61 = getelementptr %AABB, ptr null, i32 1
  %_t62 = ptrtoint ptr %_t61 to i64
  %_t63 = alloca %AABB
  store %AABB %_t60, ptr %_t63
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %main_box, ptr align 8 %_t63, i64 %_t62, i1 false)
  br label %merge.69
merge.69:
  %_t64 = load i64, ptr %i
  %_t65 = sext i32 1 to i64
  %_t66 = add i64 %_t64, %_t65
  store i64 %_t66, ptr %i
  br label %while.cond.64
while.end.66:
  ; lvalue .box
  %_t67 = getelementptr %BVHNode, ptr %node, i32 0, i32 0
  %_t68 = load %AABB, ptr %main_box
  %_t69 = getelementptr %AABB, ptr null, i32 1
  %_t70 = ptrtoint ptr %_t69 to i64
  %_t71 = alloca %AABB
  store %AABB %_t68, ptr %_t71
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %_t67, ptr align 8 %_t71, i64 %_t70, i1 false)
  %_t72 = load i64, ptr %span
  %_t73 = sext i32 2 to i64
  %_t74 = icmp sle i64 %_t72, %_t73
  br i1 %_t74, label %then.70, label %else.71
then.70:
  ; lvalue .left
  %_t75 = getelementptr %BVHNode, ptr %node, i32 0, i32 1
  %_t76 = sub i32 0, 1
  %_t77 = sext i32 %_t76 to i64
  store i64 %_t77, ptr %_t75
  ; lvalue .right
  %_t78 = getelementptr %BVHNode, ptr %node, i32 0, i32 2
  %_t79 = sub i32 0, 1
  %_t80 = sext i32 %_t79 to i64
  store i64 %_t80, ptr %_t78
  ; lvalue .start
  %_t81 = getelementptr %BVHNode, ptr %node, i32 0, i32 3
  %_t82 = load i64, ptr %start
  store i64 %_t82, ptr %_t81
  ; lvalue .count
  %_t83 = getelementptr %BVHNode, ptr %node, i32 0, i32 4
  %_t84 = load i64, ptr %span
  store i64 %_t84, ptr %_t83
  %_t85 = load ptr, ptr %nodes
  %_t86 = load %BVHNode, ptr %node
  call void @Storage_push_BVHNode(ptr %_t85, %BVHNode %_t86)
  %_t88 = sext i32 0 to i64
  ret i64 %_t88
else.71:
  ; lvalue .maximum
  %_t89 = getelementptr %AABB, ptr %main_box, i32 0, i32 1
  %_t90 = load %Vec3, ptr %_t89
  ; lvalue .minimum
  %_t91 = getelementptr %AABB, ptr %main_box, i32 0, i32 0
  %_t92 = load %Vec3, ptr %_t91
  %_t93 = call %Vec3 @Vec3_sub(%Vec3 %_t90, %Vec3 %_t92)
  %_t94 = getelementptr %Vec3, ptr null, i32 1
  %_t95 = ptrtoint ptr %_t94 to i64
  %_t96 = alloca %Vec3
  store %Vec3 %_t93, ptr %_t96
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %diff, ptr align 8 %_t96, i64 %_t95, i1 false)
  store i32 0, ptr %axis
  ; lvalue .y
  %_t97 = getelementptr %Vec3, ptr %diff, i32 0, i32 1
  %_t98 = load float, ptr %_t97
  ; lvalue .x
  %_t99 = getelementptr %Vec3, ptr %diff, i32 0, i32 0
  %_t100 = load float, ptr %_t99
  %_t101 = fcmp ogt float %_t98, %_t100
  br i1 %_t101, label %then.73, label %merge.75
then.73:
  store i32 1, ptr %axis
  br label %merge.75
merge.75:
  ; lvalue .x
  %_t102 = getelementptr %Vec3, ptr %diff, i32 0, i32 0
  %_t103 = load float, ptr %_t102
  store float %_t103, ptr %max_val
  %_t104 = load i32, ptr %axis
  %_t105 = icmp eq i32 %_t104, 1
  br i1 %_t105, label %then.76, label %merge.78
then.76:
  ; lvalue .y
  %_t106 = getelementptr %Vec3, ptr %diff, i32 0, i32 1
  %_t107 = load float, ptr %_t106
  store float %_t107, ptr %max_val
  br label %merge.78
merge.78:
  ; lvalue .z
  %_t108 = getelementptr %Vec3, ptr %diff, i32 0, i32 2
  %_t109 = load float, ptr %_t108
  %_t110 = load float, ptr %max_val
  %_t111 = fcmp ogt float %_t109, %_t110
  br i1 %_t111, label %then.79, label %merge.81
then.79:
  store i32 2, ptr %axis
  br label %merge.81
merge.81:
  %_t112 = load i64, ptr %start
  %_t113 = load i64, ptr %span
  %_t114 = sext i32 2 to i64
  %_t115 = sdiv i64 %_t113, %_t114
  %_t116 = add i64 %_t112, %_t115
  store i64 %_t116, ptr %mid
  %_t117 = load ptr, ptr %nodes
  %_t118 = call i64 @Storage_len(ptr %_t117)
  store i64 %_t118, ptr %node_idx_usize
  %_t119 = load ptr, ptr %nodes
  %_t120 = load %BVHNode, ptr %node
  call void @Storage_push_BVHNode(ptr %_t119, %BVHNode %_t120)
  %_t122 = load ptr, ptr %nodes
  %_t123 = load ptr, ptr %spheres
  %_t124 = load i64, ptr %start
  %_t125 = load i64, ptr %mid
  %_t126 = call i64 @build_bvh_recursive(ptr %_t122, ptr %_t123, i64 %_t124, i64 %_t125)
  store i64 %_t126, ptr %left_idx
  %_t127 = load ptr, ptr %nodes
  %_t128 = load ptr, ptr %spheres
  %_t129 = load i64, ptr %mid
  %_t130 = load i64, ptr %end
  %_t131 = call i64 @build_bvh_recursive(ptr %_t127, ptr %_t128, i64 %_t129, i64 %_t130)
  store i64 %_t131, ptr %right_idx
  %_t132 = load ptr, ptr %nodes
  %_t133 = load i64, ptr %node_idx_usize
  %_t134 = call %BVHNode @Storage_get_BVHNode(ptr %_t132, i64 %_t133)
  %_t135 = getelementptr %BVHNode, ptr null, i32 1
  %_t136 = ptrtoint ptr %_t135 to i64
  %_t137 = alloca %BVHNode
  store %BVHNode %_t134, ptr %_t137
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %updated_node, ptr align 8 %_t137, i64 %_t136, i1 false)
  ; lvalue .left
  %_t138 = getelementptr %BVHNode, ptr %updated_node, i32 0, i32 1
  %_t139 = load i64, ptr %left_idx
  store i64 %_t139, ptr %_t138
  ; lvalue .right
  %_t140 = getelementptr %BVHNode, ptr %updated_node, i32 0, i32 2
  %_t141 = load i64, ptr %right_idx
  store i64 %_t141, ptr %_t140
  ; lvalue .count
  %_t142 = getelementptr %BVHNode, ptr %updated_node, i32 0, i32 4
  %_t143 = sext i32 0 to i64
  store i64 %_t143, ptr %_t142
  %_t144 = load ptr, ptr %nodes
  %_t145 = load i64, ptr %node_idx_usize
  %_t146 = load %BVHNode, ptr %updated_node
  call void @Storage_set_BVHNode(ptr %_t144, i64 %_t145, %BVHNode %_t146)
  %_t148 = sext i32 0 to i64
  ret i64 %_t148
merge.72:
  ret i64 0
}

define i1 @bvh_hit(ptr %nodes.arg, ptr %spheres.arg, i64 %node_idx.arg, %Vec3 %r_orig.arg, %Vec3 %r_dir.arg, float %t_min.arg, float %t_max.arg) #0 {
entry:
  %nodes = alloca ptr
  store ptr %nodes.arg, ptr %nodes
  %spheres = alloca ptr
  store ptr %spheres.arg, ptr %spheres
  %node_idx = alloca i64
  store i64 %node_idx.arg, ptr %node_idx
  %r_orig = alloca %Vec3
  store %Vec3 %r_orig.arg, ptr %r_orig
  %r_dir = alloca %Vec3
  store %Vec3 %r_dir.arg, ptr %r_dir
  %t_min = alloca float
  store float %t_min.arg, ptr %t_min
  %t_max = alloca float
  store float %t_max.arg, ptr %t_max
  %node_idx_usize = alloca i64
  %node = alloca %BVHNode
  %hit_anything = alloca i1
  %i = alloca i64
  %s = alloca %Sphere
  %hit_left = alloca i1
  %hit_right = alloca i1
  %_t1 = load i64, ptr %node_idx
  %_t2 = sub i32 0, 1
  %_t3 = sext i32 %_t2 to i64
  %_t4 = icmp eq i64 %_t1, %_t3
  br i1 %_t4, label %then.82, label %merge.84
then.82:
  ret i1 0
merge.84:
  %_t5 = sext i32 0 to i64
  store i64 %_t5, ptr %node_idx_usize
  %_t6 = load ptr, ptr %nodes
  %_t7 = load i64, ptr %node_idx_usize
  %_t8 = call %BVHNode @Storage_get_BVHNode(ptr %_t6, i64 %_t7)
  %_t9 = getelementptr %BVHNode, ptr null, i32 1
  %_t10 = ptrtoint ptr %_t9 to i64
  %_t11 = alloca %BVHNode
  store %BVHNode %_t8, ptr %_t11
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %node, ptr align 8 %_t11, i64 %_t10, i1 false)
  ; lvalue .box
  %_t12 = getelementptr %BVHNode, ptr %node, i32 0, i32 0
  %_t13 = load %AABB, ptr %_t12
  ; lvalue .box
  %_t15 = getelementptr %BVHNode, ptr %node, i32 0, i32 0
  %_t16 = load %Vec3, ptr %r_orig
  %_t17 = load %Vec3, ptr %r_dir
  %_t18 = load float, ptr %t_min
  %_t19 = load float, ptr %t_max
  %_t20 = call i1 @AABB_hit(ptr %_t15, %Vec3 %_t16, %Vec3 %_t17, %F32 %_t18, %F32 %_t19)
  %_t21 = xor i1 %_t20, 1
  br i1 %_t21, label %then.85, label %merge.87
then.85:
  ret i1 0
merge.87:
  ; lvalue .count
  %_t22 = getelementptr %BVHNode, ptr %node, i32 0, i32 4
  %_t23 = load i64, ptr %_t22
  %_t24 = sext i32 0 to i64
  %_t25 = icmp sgt i64 %_t23, %_t24
  br i1 %_t25, label %then.88, label %else.89
then.88:
  store i1 0, ptr %hit_anything
  %_t26 = sext i32 0 to i64
  store i64 %_t26, ptr %i
  br label %while.cond.91
while.cond.91:
  %_t27 = load i64, ptr %i
  ; lvalue .count
  %_t28 = getelementptr %BVHNode, ptr %node, i32 0, i32 4
  %_t29 = load i64, ptr %_t28
  %_t30 = icmp slt i64 %_t27, %_t29
  br i1 %_t30, label %while.body.92, label %while.end.93
while.body.92:
  %_t31 = load ptr, ptr %spheres
  ; lvalue .start
  %_t32 = getelementptr %BVHNode, ptr %node, i32 0, i32 3
  %_t33 = load i64, ptr %_t32
  %_t34 = load i64, ptr %i
  %_t35 = add i64 %_t33, %_t34
  %_t36 = call %Sphere @Storage_get_Sphere(ptr %_t31, i64 %_t35)
  %_t37 = getelementptr %Sphere, ptr null, i32 1
  %_t38 = ptrtoint ptr %_t37 to i64
  %_t39 = alloca %Sphere
  store %Sphere %_t36, ptr %_t39
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %s, ptr align 8 %_t39, i64 %_t38, i1 false)
  %_t40 = load i64, ptr %i
  %_t41 = sext i32 1 to i64
  %_t42 = add i64 %_t40, %_t41
  store i64 %_t42, ptr %i
  br label %while.cond.91
while.end.93:
  %_t43 = load i1, ptr %hit_anything
  ret i1 %_t43
else.89:
  %_t44 = load ptr, ptr %nodes
  %_t45 = load ptr, ptr %spheres
  ; lvalue .left
  %_t46 = getelementptr %BVHNode, ptr %node, i32 0, i32 1
  %_t47 = load i64, ptr %_t46
  %_t48 = load %Vec3, ptr %r_orig
  %_t49 = load %Vec3, ptr %r_dir
  %_t50 = load float, ptr %t_min
  %_t51 = load float, ptr %t_max
  %_t52 = call i1 @bvh_hit(ptr %_t44, ptr %_t45, i64 %_t47, %Vec3 %_t48, %Vec3 %_t49, %F32 %_t50, %F32 %_t51)
  store i1 %_t52, ptr %hit_left
  %_t53 = load ptr, ptr %nodes
  %_t54 = load ptr, ptr %spheres
  ; lvalue .right
  %_t55 = getelementptr %BVHNode, ptr %node, i32 0, i32 2
  %_t56 = load i64, ptr %_t55
  %_t57 = load %Vec3, ptr %r_orig
  %_t58 = load %Vec3, ptr %r_dir
  %_t59 = load float, ptr %t_min
  %_t60 = load float, ptr %t_max
  %_t61 = call i1 @bvh_hit(ptr %_t53, ptr %_t54, i64 %_t56, %Vec3 %_t57, %Vec3 %_t58, %F32 %_t59, %F32 %_t60)
  store i1 %_t61, ptr %hit_right
  %_t62 = load i1, ptr %hit_left
  %_t63 = load i1, ptr %hit_right
  %_t64 = or i1 %_t62, %_t63
  ret i1 %_t64
merge.90:
  ret i1 0
}

; @kernel
define void @bvh_kernel(ptr %nodes.arg, ptr %spheres.arg, %Vec3 %ray_orig.arg, %Vec3 %ray_dir.arg) #0 {
entry:
  %nodes = alloca ptr
  store ptr %nodes.arg, ptr %nodes
  %spheres = alloca ptr
  store ptr %spheres.arg, ptr %spheres
  %ray_orig = alloca %Vec3
  store %Vec3 %ray_orig.arg, ptr %ray_orig
  %ray_dir = alloca %Vec3
  store %Vec3 %ray_dir.arg, ptr %ray_dir
  %hit = alloca i1
  %_t1 = load ptr, ptr %nodes
  %_t2 = load ptr, ptr %spheres
  %_t3 = sext i32 0 to i64
  %_t4 = load %Vec3, ptr %ray_orig
  %_t5 = load %Vec3, ptr %ray_dir
  %_t6 = call i1 @bvh_hit(ptr %_t1, ptr %_t2, i64 %_t3, %Vec3 %_t4, %Vec3 %_t5, %F32 0.000000e0, %F32 1.000000e3)
  store i1 %_t6, ptr %hit
  ret void
}

define void @main() #0 {
entry:
  %_t1 = call ptr @ystr_new(ptr @.str.0)
  call void @println(ptr %_t1)
  ret void
}

!0 = !{i32 1}
