; ================================================
;  Generated by Y Compiler — LLVM IR Backend
;  Hardware Profile: AVX=true, AVX512=true, L2 Line=64B
; ================================================

target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

attributes #0 = { "target-cpu"="skylake-avx512" "target-features"="+avx512f,+avx512cd,+avx512bw,+avx512dq,+avx512vl" }

; --- Struct Definitions ---

; --- Enum Definitions ---

; --- External Runtime Declarations ---
declare i32 @block_idx_y(...)
declare i32 @thread_idx_y(...)
declare i32 @block_idx_x(...)
declare i32 @thread_idx_x(...)
declare i32 @block_ptr2d_load(...)
declare i32 @block_ptr2d_store(...)
declare ptr @ystr_new(ptr)
declare void @ystr_push(ptr, i8)
declare void @ystr_push_str(ptr, ptr)
declare i1 @ystr_eq_cstr(ptr, ptr)
declare i64 @ystr_len(ptr)
declare i8 @ystr_char_at(ptr, i64)
declare ptr @ystr_clone(ptr)
declare ptr @yvec_new(i64)
declare void @yvec_push(ptr, ptr)
declare ptr @yvec_get(ptr, i64)
declare i64 @yvec_len(ptr)
declare ptr @yfile_read_to_string(ptr)
declare void @yfile_write(ptr, ptr)
declare i32 @printf(ptr, ...)
declare ptr @malloc(i64)
declare void @free(ptr)
declare void @exit(i32) noreturn
declare void @println(ptr)
declare void @print_int(i64)
declare void @llvm.prefetch.p0(ptr nocapture readonly, i32, i32, i32)
declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg)

@.fmt.sn = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt.s = private unnamed_addr constant [3 x i8] c"%s\00"
@.fmt.d = private unnamed_addr constant [4 x i8] c"%ld\00"
@.str.bounds_err = private unnamed_addr constant [54 x i8] c"Index out of bounds panic: index %ld, array size %ld\0A\00"

; @kernel
define void @naive_gemm_f32(ptr %A.arg, ptr %B.arg, ptr %C.arg, i32 %M.arg, i32 %N.arg, i32 %K.arg) #0 {
entry:
  %A = alloca ptr
  store ptr %A.arg, ptr %A
  %B = alloca ptr
  store ptr %B.arg, ptr %B
  %C = alloca ptr
  store ptr %C.arg, ptr %C
  %M = alloca i32
  store i32 %M.arg, ptr %M
  %N = alloca i32
  store i32 %N.arg, ptr %N
  %K = alloca i32
  store i32 %K.arg, ptr %K
  %row = alloca i32
  %col = alloca i32
  %acc = alloca float
  %k = alloca i32
  %a_val = alloca float
  %b_val = alloca float
  %_t1 = call i32 @block_idx_y()
  %_t2 = mul i32 %_t1, 16
  %_t3 = call i32 @thread_idx_y()
  %_t4 = add i32 %_t2, %_t3
  store i32 %_t4, ptr %row
  %_t5 = call i32 @block_idx_x()
  %_t6 = mul i32 %_t5, 16
  %_t7 = call i32 @thread_idx_x()
  %_t8 = add i32 %_t6, %_t7
  store i32 %_t8, ptr %col
  %_t9 = fptrunc double 0.000000e0 to float
  store float %_t9, ptr %acc
  %_t10 = load i32, ptr %K
  store i32 0, ptr %k
  br label %for.cond.1
for.cond.1:
  %_t11 = load i32, ptr %k
  %_t12 = icmp slt i32 %_t11, %_t10
  br i1 %_t12, label %for.body.2, label %for.end.3
for.body.2:
  %_t13 = load ptr, ptr %A
  %_t14 = ptrtoint ptr %_t13 to i32
  %_t15 = load i32, ptr %row
  %_t16 = load i32, ptr %k
  %_t17 = load i32, ptr %K
  %_t18 = load i32, ptr %M
  %_t19 = load i32, ptr %K
  %_t20 = call i32 @block_ptr2d_load(i32 %_t14, i32 %_t15, i32 %_t16, i32 %_t17, i32 %_t18, i32 %_t19)
  %_t21 = sitofp i32 %_t20 to float
  store float %_t21, ptr %a_val
  %_t22 = load ptr, ptr %B
  %_t23 = ptrtoint ptr %_t22 to i32
  %_t24 = load i32, ptr %k
  %_t25 = load i32, ptr %col
  %_t26 = load i32, ptr %N
  %_t27 = load i32, ptr %K
  %_t28 = load i32, ptr %N
  %_t29 = call i32 @block_ptr2d_load(i32 %_t23, i32 %_t24, i32 %_t25, i32 %_t26, i32 %_t27, i32 %_t28)
  %_t30 = sitofp i32 %_t29 to float
  store float %_t30, ptr %b_val
  %_t31 = load float, ptr %acc
  %_t32 = load float, ptr %a_val
  %_t33 = load float, ptr %b_val
  %_t34 = fmul float %_t32, %_t33
  %_t35 = fadd float %_t31, %_t34
  store float %_t35, ptr %acc
  %_t36 = load i32, ptr %k
  %_t37 = add i32 %_t36, 1
  store i32 %_t37, ptr %k
  br label %for.cond.1
for.end.3:
  %_t38 = load ptr, ptr %C
  %_t39 = ptrtoint ptr %_t38 to i32
  %_t40 = load i32, ptr %row
  %_t41 = load i32, ptr %col
  %_t42 = load i32, ptr %N
  %_t43 = load i32, ptr %M
  %_t44 = load i32, ptr %N
  %_t45 = load float, ptr %acc
  %_t46 = fptosi float %_t45 to i32
  %_t47 = call i32 @block_ptr2d_store(i32 %_t39, i32 %_t40, i32 %_t41, i32 %_t42, i32 %_t43, i32 %_t44, i32 %_t46)
  ret void
}

define void @ysu_main() #0 {
entry:
  ret void
}

!0 = !{i32 1}
