"""Nested induction must preserve effects, including discarded accesses.

Fresh ptxas output supplies a real two-loop control. Hand-edited disassembly
is deliberately a proposed translation, not an assembled executable artifact.
The controls exercise instruction omission, width/address/guard changes and
effects the per-thread induction cannot compose.
"""
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import unittest

from verification_unittest import main as verification_main

ROOT = Path(__file__).resolve().parents[1]
TVAL = ROOT / 'tools' / 'ptxas_tval'
sys.path.insert(0, str(TVAL))

try:
    import z3
except ImportError:
    HAS_Z3 = False
else:
    HAS_Z3 = True
    import nestval


NESTED = '''.version 7.8
.target sm_89
.address_size 64
.visible .entry nested_effects(.param .u64 I, .param .u64 O,
                               .param .u32 N, .param .u32 M)
{
 .reg .b32 %r<12>;
 .reg .b64 %rd<8>;
 .reg .pred %p<4>;
 ld.param.u64 %rd0, [I];
 ld.param.u64 %rd1, [O];
 ld.param.u32 %r0, [N];
 ld.param.u32 %r1, [M];
 mov.u32 %r2, 0;
 outer:
 setp.ge.u32 %p0, %r2, %r0;
 @%p0 bra outer_end;
 mov.u32 %r4, 0;
 mov.u32 %r3, 0;
 inner:
 setp.ge.u32 %p1, %r3, %r1;
 @%p1 bra inner_end;
 mul.lo.u32 %r5, %r2, %r1;
 add.u32 %r6, %r5, %r3;
 cvt.u64.u32 %rd2, %r6;
 shl.b64 %rd3, %rd2, 2;
 add.u64 %rd4, %rd0, %rd3;
 ld.global.u32 %r7, [%rd4];
 add.u32 %r4, %r4, %r7;
 add.u32 %r3, %r3, 1;
 bra inner;
 inner_end:
 cvt.u64.u32 %rd5, %r2;
 shl.b64 %rd6, %rd5, 2;
 add.u64 %rd7, %rd1, %rd6;
 st.global.u32 [%rd7], %r4;
 add.u32 %r2, %r2, 1;
 bra outer;
 outer_end:
 ret;
}
'''


def edit_instructions(text, transform):
    """Transform decoded instructions while keeping symbolic branch labels."""
    result, index = [], 0
    for line in text.splitlines():
        match = re.fullmatch(r'\s*/\*[0-9a-fA-F]+\*/\s*(.*?)\s*;\s*', line)
        if not match:
            result.append(line)
            continue
        for instruction in transform(match.group(1)):
            result.append(f'/*{16*index:04x}*/ {instruction} ;')
            index += 1
    return '\n'.join(result) + '\n'


_O1 = {}


def o1_fixture(kernel):
    """`tools/ptxas_tval/o1/<kernel>` is GENERATED by `build_corpus.sh` and
    gitignored, so a fresh checkout does not have it. Build it here with that
    script's recipe - the committed `tests/<kernel>.ptx`, `ptxas -O1` at the
    file's OWN `.target`, then `nvdisasm -c` - so the suite reads no untracked
    state and always checks the PTX the repository ships."""
    if kernel in _O1:
        return _O1[kernel]
    for tool in ('ptxas', 'nvdisasm'):
        if shutil.which(tool) is None:
            raise unittest.SkipTest(f'{tool} is required to rebuild o1/{kernel}')
    source_path = ROOT / 'tests' / (kernel + '.ptx')
    source = source_path.read_text()
    target = re.search(r'(?m)^\.target\s+(sm_\w+)', source)
    if target is None:
        raise AssertionError(f'{source_path} declares no .target')
    with tempfile.TemporaryDirectory(prefix='y-o1-fixture-') as work:
        cubin = Path(work) / (kernel + '.cubin')
        subprocess.run(['ptxas', '-O1', '-arch=' + target.group(1), '-o', str(cubin),
                        str(source_path)], check=True, capture_output=True)
        machine = subprocess.run(['nvdisasm', '-c', str(cubin)], check=True,
                                 capture_output=True, text=True).stdout
    _O1[kernel] = (source, machine)
    return _O1[kernel]


@unittest.skipUnless(HAS_Z3, 'nested effect regressions require z3-solver')
class NestedEffects(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix='y-nested-effects-')
        self.directory = Path(self.temporary.name)
        self.addCleanup(self.temporary.cleanup)

    def validate(self, source, machine):
        ptx, sass = self.directory / 'subject.ptx', self.directory / 'subject.sass'
        ptx.write_text(source)
        sass.write_text(machine)
        return nestval.validate(str(ptx), str(sass), budget=3, verbose=False)

    def fixture(self, stem):
        if stem.startswith('o1/'):
            return o1_fixture(stem[len('o1/'):])
        return ((TVAL / (stem + '.ptx')).read_text(),
                (TVAL / (stem + '.sass')).read_text())

    def accepted(self, source, machine):
        result = self.validate(source, machine)
        self.assertEqual(result[0], 'VALIDATED', result)
        self.assertGreater(result[2], 0)

    def unproved(self, source, machine, diagnostic):
        result = self.validate(source, machine)
        self.assertEqual(result[0], 'UNPROVED', result)
        self.assertIn(diagnostic, result[1])
        return result

    def test_genuine_nested_and_iteration_readback_controls(self):
        for stem in ('o1/y_cpu_matmul', 'mem/nest_accum', 'mem/loop_ls'):
            with self.subTest(stem=stem):
                self.accepted(*self.fixture(stem))

    def test_hoisted_iteration_readback_is_rejected(self):
        source, _ = self.fixture('mem/nest_accum')
        _, stale = self.fixture('mem/nest_accum_stale')
        self.unproved(source, stale, 'load counts')

    def test_header_register_effect_is_refused_before_it_can_be_discarded(self):
        source, machine = self.fixture('mem/nest_accum')
        source = source.replace('    setp.ge.u32 %p0,',
                                '    add.u32 %r6, %r6, 1;\n    setp.ge.u32 %p0,', 1)
        with self.assertRaisesRegex(Exception, 'loop header effect'):
            self.validate(source, machine)

    def test_child_header_register_effect_is_also_refused(self):
        source, machine = self.fixture('o1/y_cpu_matmul')
        # The loop test is SIGNED since the emitter tests I32 bounds signed; an
        # anchor that no longer matches leaves the kernel unmutated, so assert it.
        anchor = '    setp.ge.s32 %p2,'
        self.assertEqual(source.count(anchor), 1, 'the child loop test moved')
        source = source.replace(anchor, '    mov.f32 %f0, 7.0;\n' + anchor, 1)
        with self.assertRaisesRegex(Exception, 'loop header effect'):
            self.validate(source, machine)

    def test_supported_header_predicate_is_executed_in_the_body(self):
        source, machine = self.fixture('mem/nest_accum')
        # The entering path makes p0 false. A discarded load guarded by !p0
        # observes the header's freshly computed predicate, not an old value.
        source = source.replace('    ld.global.u32 %r3, [%rd1];',
                                '    @!%p0 ld.global.u32 %r7, [%rd1];\n'
                                '    ld.global.u32 %r3, [%rd1];')
        machine = edit_instructions(machine, lambda ins:
                                    ['LDG.E RZ, [R2.64]', ins]
                                    if ins == 'LDG.E R7, [R2.64]' else [ins])
        self.accepted(source, machine)

    def discarded_iteration_load(self):
        source, machine = self.fixture('mem/nest_accum')
        source = source.replace('    ld.global.u32 %r3, [%rd1];',
                                '    ld.global.u32 %r7, [%rd1];\n'
                                '    ld.global.u32 %r3, [%rd1];')
        machine = edit_instructions(machine, lambda ins:
                                    ['LDG.E RZ, [R2.64]', ins]
                                    if ins == 'LDG.E R7, [R2.64]' else [ins])
        return source, machine

    def test_discarded_iteration_load_count_address_width_and_guard(self):
        source, machine = self.discarded_iteration_load()
        self.accepted(source, machine)
        mutants = (
            ('LDG.E RZ, [R2.64]', None, 'load counts'),
            ('LDG.E RZ, [R2.64]', 'LDG.E RZ, [R2.64+0x4]', 'address'),
            ('LDG.E RZ, [R2.64]', 'LDG.E.U8 RZ, [R2.64]', 'width'),
            ('LDG.E RZ, [R2.64]', '@P0 LDG.E RZ, [R2.64]', 'guard'),
        )
        for old, new, diagnostic in mutants:
            with self.subTest(diagnostic=diagnostic):
                changed = edit_instructions(machine, lambda ins:
                                            ([] if new is None else [new])
                                            if ins == old else [ins])
                self.unproved(source, changed, diagnostic)

    def test_discarded_prologue_load_is_observable(self):
        source, machine = self.fixture('mem/nest_accum')
        source = source.replace('    mov.u32 %r1, 0;',
                                '    ld.global.u32 %r7, [%rd1];\n    mov.u32 %r1, 0;')
        machine = edit_instructions(machine, lambda ins:
            [ins, 'MOV R2, c[0x0][0x168]', 'MOV R3, c[0x0][0x16c]',
             'LDG.E RZ, [R2.64]'] if ins == 'ULDC.64 UR4, c[0x0][0x118]' else [ins])
        self.accepted(source, machine)
        wrong = edit_instructions(machine, lambda ins:
                                  [] if ins == 'LDG.E RZ, [R2.64]' else [ins])
        self.unproved(source, wrong, 'prologue load counts')

    def test_discarded_epilogue_load_preserves_count_address_width_and_guard(self):
        source, machine = self.fixture('mem/nest_accum')
        source = source.replace('    $LOOP_END_1:',
                                '    $LOOP_END_1:\n    ld.global.u32 %r7, [%rd1];')
        # A branching zero-trip guard reaches the epilogue on both paths.
        # Define its address in the epilogue so it is valid on zero trips and
        # independent of the opaque summary's forgotten temporary registers.
        machine = machine.replace('@!P0 EXIT', '@!P0 BRA `(.L_access_exit)')
        machine = re.sub(r'(\s*/\*0100\*/\s*)EXIT\s*;',
                         '\n.L_access_exit:\n/*0100*/ MOV R2, c[0x0][0x168] ;\n'
                         '/*0101*/ MOV R3, c[0x0][0x16c] ;\n'
                         '/*0102*/ LDG.E RZ, [R2.64] ;\n/*0103*/ EXIT ;', machine)
        machine = edit_instructions(machine, lambda ins: [ins])
        self.accepted(source, machine)
        for replacement, diagnostic in ((None, 'load counts'),
                ('LDG.E RZ, [R2.64+0x4]', 'address'),
                ('LDG.E.U8 RZ, [R2.64]', 'width'),
                ('@!P0 LDG.E RZ, [R2.64]', 'guard')):
            with self.subTest(diagnostic=diagnostic):
                wrong = edit_instructions(machine, lambda ins:
                    ([] if replacement is None else [replacement])
                    if ins == 'LDG.E RZ, [R2.64]' else [ins])
                result = self.unproved(source, wrong, 'epilogue load')
                self.assertIn(diagnostic, result[1])

    def test_exit_zero_trip_guard_cannot_skip_an_epilogue_load(self):
        source, machine = self.fixture('mem/nest_accum')
        source = source.replace('    $LOOP_END_1:',
                                '    $LOOP_END_1:\n    ld.global.u32 %r7, [%rd1];')
        with self.assertRaisesRegex(Exception, 'EXITs.*loads or stores'):
            self.validate(source, machine)

    def test_uncomposed_shared_barrier_and_reconvergence_effects_are_refused(self):
        source, machine = self.fixture('o1/y_cpu_matmul')
        for effect in ('bar.sync 0;', 'st.shared.u32 [%rd0], %r0;'):
            with self.subTest(effect=effect):
                changed = source.replace('    fma.rn.f32', f'    {effect}\n    fma.rn.f32', 1)
                with self.assertRaisesRegex(Exception, 'cross-thread effect'):
                    self.validate(changed, machine)
        for effect in ('BAR.SYNC 0x0', 'STS [RZ], RZ', 'BSSY B0, `(.L_x_0)', 'BSYNC B0'):
            with self.subTest(effect=effect):
                changed = edit_instructions(machine, lambda ins:
                                            [effect, ins] if ins.startswith('FFMA ') else [ins])
                with self.assertRaisesRegex(Exception, 'cross-thread/reconvergence effect'):
                    self.validate(source, changed)

    def test_reachable_selfbranch_and_malformed_sass_are_refused(self):
        source, machine = self.fixture('mem/nest_accum')
        # Existing trailing trap is unreachable and the positive still checks.
        self.accepted(source, machine)
        wrong = machine.replace('@!P0 BRA `(.L_x_0)', '@!P0 BRA `(.L_x_1)')
        with self.assertRaisesRegex(Exception, 'reachable.*self'):
            self.validate(source, wrong)
        wrong = machine.replace('LDG.E R7, [R2.64] ;', 'LDG.E R7, [R2.64]')
        with self.assertRaisesRegex(Exception, 'SASS instruction'):
            self.validate(source, wrong)

    @unittest.skipUnless(shutil.which('ptxas') and shutil.which('nvdisasm'),
                         'fresh nested translation requires ptxas and nvdisasm')
    def test_fresh_nested_translation_and_child_load_mutation(self):
        source = self.directory / 'fresh.ptx'
        cubin = self.directory / 'fresh.cubin'
        source.write_text(NESTED)
        subprocess.run(['ptxas', '-O1', '-arch=sm_89', str(source), '-o', str(cubin)],
                       check=True, capture_output=True)
        machine = subprocess.run(['nvdisasm', '-c', str(cubin)], check=True,
                                 capture_output=True, text=True).stdout
        self.accepted(NESTED, machine)
        self.assertIn('LDG.E ', machine)
        changed = edit_instructions(machine, lambda ins:
                                    [ins.replace('LDG.E ', 'LDG.E.U8 ', 1)]
                                    if ins.startswith('LDG.E ') else [ins])
        self.unproved(NESTED, changed, 'width')


if __name__ == '__main__':
    verification_main()
