"""Fresh loop translations must preserve entry, termination, and all effects.

The negative controls edit source or disassembly after a genuine PTXAS build;
they do not claim that PTXAS emits the deliberately broken translations.
"""
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import unittest

from verification_unittest import main as verification_main

ROOT = Path(__file__).resolve().parents[1]
TVAL = ROOT / 'tools' / 'ptxas_tval'
sys.path.insert(0, str(TVAL))
import loopcfg

try:
    import z3
    import loopval
    import sassexec
except ImportError:
    HAS_Z3 = False
else:
    HAS_Z3 = True


def renumber(text):
    addresses = iter(range(0, 1 << 20, 16))
    return re.sub(r'/\*[0-9a-fA-F]+\*/',
                  lambda _: f'/*{next(addresses):04x}*/', text)


class TemporarySass(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(prefix='y-loop-parser-')
        self.addCleanup(temporary.cleanup)
        self.directory = Path(temporary.name)

    def write(self, name, text):
        path = self.directory / name
        path.write_text(text)
        return str(path)


class ParserControls(TemporarySass):
    def test_only_unreachable_self_branches_are_traps(self):
        for prefix, unreachable in (('EXIT', True), ('@P0 EXIT', False), ('NOP', False)):
            with self.subTest(prefix=prefix):
                source = f'/*0000*/ {prefix};\n.L_spin:\n/*0010*/ BRA `(.L_spin);\n'
                path = self.write('self.sass', source)
                if unreachable:
                    _, _, traps, backs = loopcfg.sass_back_edges(path)
                    self.assertEqual(traps, {16})
                    self.assertEqual(backs, [])
                else:
                    with self.assertRaisesRegex(Exception, 'reachable self-branch'):
                        loopcfg.sass_back_edges(path)

    def test_branch_can_reach_a_self_loop_past_an_exit(self):
        source = ('/*0000*/ @P0 BRA `(.L_spin);\n/*0010*/ EXIT;\n'
                  '.L_spin:\n/*0020*/ BRA `(.L_spin);\n')
        with self.assertRaisesRegex(Exception, 'reachable self-branch'):
            loopcfg.sass_back_edges(self.write('past_exit.sass', source))

    def test_pc_tagged_malformed_and_duplicate_instructions_refuse(self):
        for instruction in ('/*0010*/ ATOM.E.ADD R0, [R2.64], RZ',
                            '/*not-a-pc*/ MOV R0, RZ;', '/*0010*/ ;',
                            '/*0000*/ MOV R0, RZ;', '/*0010 MOV R0, RZ;',
                            '/*00a0 @P0 STG.E [R2.64], R0;',
                            '/*abcd MOV R0, RZ;', '/*0010', '/*0010*',
                            '/*0010/ MOV R0, RZ;', '/*0010 mov R0, RZ;',
                            '/*00x0 MOV R0, RZ;', '/* 0010 MOV R0, RZ;'):
            with self.subTest(instruction=instruction):
                with self.assertRaisesRegex(Exception, 'UNMODELLED SASS'):
                    loopcfg.sass_back_edges(self.write('bad.sass',
                        '/*0000*/ NOP;\n' + instruction + '\n/*0020*/ EXIT;\n'))

    def test_uppercase_pc_and_label_aliases_parse_without_dropping_instructions(self):
        path = self.write('uppercase.sass',
            '.L_a:\n.L_b:\n/*00A0*/ MOV R0, RZ;\n/*00B0*/ EXIT;\n')
        instructions, labels = loopcfg.sass_instructions(path)
        self.assertEqual(instructions, [(160, 'MOV R0, RZ'), (176, 'EXIT')])
        self.assertEqual(labels, {'.L_a': 160, '.L_b': 160})

    def test_metadata_and_complete_prose_comments_remain_parseable(self):
        path = self.write('comments.sass',
            '.target sm_89\n// generated disassembly\n/* metadata */\n'
            '/*dead code annotation*/\n/* Generated by a disassembler */\n'
            '/*0000*/ MOV R0, RZ;\n/*0010*/ EXIT;\n')
        self.assertEqual(loopcfg.sass_instructions(path)[0],
                         [(0, 'MOV R0, RZ'), (16, 'EXIT')])


class HeaderPredicateControls(TemporarySass):
    def test_topologically_defined_header_predicates_are_supported(self):
        lines = ['setp.lt.u32 %p0, %r0, %r1',
                 'setp.ne.u32 %p1, %r2, 0',
                 'and.pred %p2, %p0, %p1',
                 'and.pred %p2, %p2, %p3']
        self.assertEqual(loopcfg.require_ptx_guard_only(lines), {0, 1, 2})

    def test_header_written_predicates_cannot_be_read_before_local_definition(self):
        controls = (
            ['and.pred %p0, %p0, %p1'],
            ['and.pred %p0, %p1, %p2', 'setp.lt.u32 %p1, %r0, %r1'],
            ['and.pred %p0, %p1, %p2', 'and.pred %p1, %p0, %p2'],
        )
        for lines in controls:
            with self.subTest(lines=lines):
                with self.assertRaisesRegex(Exception, 'header predicate read before definition'):
                    loopcfg.require_ptx_guard_only(lines)

    @unittest.skipUnless(HAS_Z3, 'nested predicate regression requires z3-solver')
    def test_loop_carried_header_predicate_cannot_hide_a_wrong_exit_store(self):
        import nestval
        # This deliberate translation formerly VALIDATED: PTX's final top
        # test clears p1 and skips the store; SASS retains P1 and writes 1.
        # The pair is synthetic disassembly, not a claim about PTXAS output.
        source = (
            '.version 7.8\n'
            '.target sm_89\n'
            '.address_size 64\n'
            '.visible .entry probe(.param .u64 O, .param .u32 N)\n'
            '{\n'
            ' .reg .b32 %r<4>;\n'
            ' .reg .b64 %rd<2>;\n'
            ' .reg .pred %p<3>;\n'
            ' ld.param.u64 %rd0, [O];\n'
            ' ld.param.u32 %r1, [N];\n'
            ' mov.u32 %r0, 0;\n'
            ' setp.lt.u32 %p1, %r0, %r1;\n'
            ' header:\n'
            ' setp.lt.u32 %p0, %r0, %r1;\n'
            ' and.pred %p1, %p1, %p0;\n'
            ' @!%p1 bra done;\n'
            ' add.u32 %r0, %r0, 1;\n'
            ' bra header;\n'
            ' done:\n'
            ' @%p1 st.global.u32 [%rd0], 1;\n'
            ' ret;\n'
            '}\n'
        )
        machine = (
            '.target sm_89\n'
            'probe:\n'
            '/*0000*/ MOV R2, c[0x0][0x160] ;\n'
            '/*0010*/ MOV R3, c[0x0][0x164] ;\n'
            '/*0020*/ MOV R0, RZ ;\n'
            '/*0030*/ MOV R4, c[0x0][0x168] ;\n'
            '/*0040*/ ISETP.LT.U32.AND P1, PT, R0, R4, PT ;\n'
            '/*0050*/ @!P1 BRA `(.L_done) ;\n'
            '.L_body:\n'
            '/*0060*/ ISETP.LT.U32.AND P1, PT, R0, R4, P1 ;\n'
            '/*0070*/ IADD3 R0, R0, 0x1, RZ ;\n'
            '/*0080*/ ISETP.LT.U32.AND P0, PT, R0, R4, PT ;\n'
            '/*0090*/ @P0 BRA `(.L_body) ;\n'
            '.L_done:\n'
            '/*00a0*/ MOV R5, 0x1 ;\n'
            '/*00b0*/ @P1 STG.E [R2.64], R5 ;\n'
            '/*00c0*/ EXIT ;\n'
        )
        with self.assertRaisesRegex(Exception, 'header predicate read before definition'):
            nestval.validate(self.write('carried_header.ptx', source),
                             self.write('carried_header.sass', machine),
                             budget=3, verbose=False)


@unittest.skipUnless(HAS_Z3, 'full-executor parser controls require z3-solver')
class FullExecutorParserControls(TemporarySass):
    def test_full_executor_refuses_malformed_prefixes_and_ambiguous_sections(self):
        for malformed in ('/*0010 MOV R0, RZ;', '/*0010 @P0 MOV R0, RZ;',
                          '/*0010/ MOV R0, RZ;', '/*0010 mov R0, RZ;',
                          '/*00x0 MOV R0, RZ;', '/* 0010 MOV R0, RZ;', '/*0010'):
            with self.subTest(malformed=malformed):
                path = self.write('full_bad.sass',
                    '/*0000*/ MOV R0, RZ;\n' + malformed + '\n/*0020*/ EXIT;\n')
                with self.assertRaisesRegex(Exception, 'UNMODELLED SASS instruction line'):
                    sassexec.run_sass(path, {})
        path = self.write('two_sections.sass',
            '.text.a:\n/*0000*/ EXIT;\n.text.b:\n/*0010*/ EXIT;\n')
        with self.assertRaisesRegex(Exception, 'multiple .text sections'):
            sassexec.run_sass(path, {})

    def test_full_executor_preserves_labels_and_forward_branch_path_merging(self):
        path = self.write('forward.sass',
            '/*0000*/ MOV R0, 0x3;\n/*0010*/ BRA `(.L_join);\n'
            '/*0020*/ MOV R0, 0x4;\n.L_join:\n/*0030*/ EXIT;\n')
        state = sassexec.run_sass(path, {})
        self.assertEqual(state.count, 4)
        self.assertTrue(z3.is_true(z3.simplify(state.R[0] == z3.BitVecVal(3, 32))))


@unittest.skipUnless(HAS_Z3, 'loop controls require z3-solver')
class FreshLoopControls(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        if not all(shutil.which(tool) for tool in ('ptxas', 'nvdisasm')):
            raise unittest.SkipTest('fresh loop controls require ptxas and nvdisasm')
        temporary = tempfile.TemporaryDirectory(prefix='y-loop-controls-')
        cls.addClassCleanup(temporary.cleanup)
        cls.directory = Path(temporary.name)
        cls.artifacts = {}
        for name, source in (('swap', TVAL / 'mem/loop_swap.ptx'),
                             ('exact_pv', ROOT / 'tests/exact_pv.ptx')):
            ptx = cls.directory / (name + '.ptx')
            ptx.write_bytes(source.read_bytes())
            cubin = cls.directory / (name + '.cubin')
            subprocess.run(['ptxas', '-O1', '-arch=sm_89', str(ptx), '-o', str(cubin)],
                           capture_output=True, check=True, timeout=30)
            disassembly = subprocess.run(['nvdisasm', '-c', str(cubin)],
                                         capture_output=True, check=True, timeout=30).stdout.decode()
            sass = cls.directory / (name + '.sass')
            sass.write_text(disassembly)
            cls.artifacts[name] = (ptx, sass)

    def write(self, name, text):
        path = self.directory / name
        path.write_text(text)
        return str(path)

    def validate(self, ptx, sass):
        return loopval.validate(str(ptx), str(sass), budget=3, samples=8, verbose=False)

    def test_genuine_loop_translations_and_trailing_traps_validate(self):
        for name, (ptx, sass) in self.artifacts.items():
            with self.subTest(kernel=name):
                result = self.validate(ptx, sass)
                self.assertEqual(result[0], 'VALIDATED', result)
                self.assertGreater(result[2], 0)
                self.assertTrue(loopcfg.sass_back_edges(str(sass))[2])

    def test_omitted_header_value_updates_refuse_at_zero_and_positive_trip_counts(self):
        ptx, sass = self.artifacts['swap']
        source = ptx.read_text().replace('    setp.ge.u32 %p0, %r1, %r0;',
            '    add.u32 %r2, %r2, 1;\n    setp.ge.u32 %p0, %r1, %r0;')
        for trips in (None, 0, 1):
            with self.subTest(trips=trips):
                changed = source if trips is None else source.replace(
                    '    ld.param.u32 %r0, [N_2];', f'    mov.u32 %r0, {trips};')
                with self.assertRaisesRegex(Exception, 'PTX loop header effect'):
                    self.validate(self.write('header.ptx', changed), sass)

    def test_header_predicates_consumed_outside_the_guard_refuse(self):
        ptx, sass = self.artifacts['swap']
        source = ptx.read_text().replace('    xor.b32 %r3, %r2, %r1;',
            '    @%p0 xor.b32 %r3, %r2, %r1;')
        with self.assertRaisesRegex(Exception, 'header predicate is consumed'):
            self.validate(self.write('header_predicate.ptx', source), sass)

    def test_missing_zero_trip_guard_is_unproved(self):
        ptx, sass = self.artifacts['exact_pv']
        machine, count = re.subn(r'@!P0 BRA `\(\.L_x_0\)', 'NOP', sass.read_text(), count=1)
        self.assertEqual(count, 1)
        result = self.validate(ptx, self.write('missing_guard.sass', machine))
        self.assertEqual(result[0], 'UNPROVED', result)
        self.assertRegex(result[1], 'ENTRY: missing SASS zero-trip guard: sat')

    def test_missing_guard_validates_when_zero_iterations_are_impossible(self):
        ptx, sass = self.artifacts['swap']
        source = ptx.read_text().replace('    ld.param.u32 %r0, [N_2];', '    mov.u32 %r0, 1;')
        machine = sass.read_text().replace('c[0x0][0x170]', '0x1')
        machine, count = re.subn(r'@!P0 BRA `\(\.L_x_0\)', 'NOP', machine, count=1)
        self.assertEqual(count, 1)
        result = self.validate(self.write('positive_trip.ptx', source),
                               self.write('positive_trip.sass', machine))
        self.assertEqual(result[0], 'VALIDATED', result)

    def test_reachable_self_loop_before_output_refuses(self):
        ptx, sass = self.artifacts['exact_pv']
        machine, count = re.subn(r'(?m)^(\s*/\*[0-9a-f]+\*/\s+STG\.E\.64)',
            '.L_audit_spin:\n/*fff0*/ BRA `(.L_audit_spin);\n\\1', sass.read_text(), count=1)
        self.assertEqual(count, 1)
        with self.assertRaisesRegex(Exception, 'reachable self-branch'):
            self.validate(ptx, self.write('self_loop.sass', renumber(machine)))

    def test_malformed_pc_instruction_inside_a_fresh_loop_refuses(self):
        ptx, sass = self.artifacts['exact_pv']
        machine = sass.read_text().replace('.L_x_1:\n',
            '.L_x_1:\n/*00a8*/ ATOM.E.ADD R20, [R2.64], RZ\n', 1)
        self.assertNotEqual(machine, sass.read_text())
        with self.assertRaisesRegex(Exception, 'UNMODELLED SASS instruction line'):
            self.validate(ptx, self.write('malformed.sass', machine))

    def test_sass_shared_barrier_and_reconvergence_effects_refuse_every_region(self):
        ptx, sass = self.artifacts['exact_pv']
        for operation in ('STS [RZ], RZ', 'LDS R20, [RZ]', 'BAR.SYNC 0',
                          'BSSY B0, `(.L_x_0)', 'BSYNC B0'):
            for region, anchor in (('prologue', '.L_x_1:\n'),
                                   ('body', '/*01a0*/'), ('epilogue', '.L_x_0:\n')):
                with self.subTest(operation=operation, region=region):
                    effect = '/*fff0*/ ' + operation + ';\n'
                    insertion = anchor + effect if region == 'epilogue' else effect + anchor
                    machine = sass.read_text().replace(anchor, insertion, 1)
                    self.assertNotEqual(machine, sass.read_text())
                    with self.assertRaisesRegex(Exception, 'cross-thread/reconvergence effect'):
                        self.validate(ptx, self.write('effect.sass', renumber(machine)))

    def test_ptx_shared_and_barrier_effects_refuse(self):
        ptx, sass = self.artifacts['swap']
        for operation in ('st.shared.u32 [0], %r2;', 'ld.shared.u32 %r6, [0];', 'bar.sync 0;'):
            with self.subTest(operation=operation):
                source = ptx.read_text().replace('    xor.b32 %r3, %r2, %r1;',
                    '    ' + operation + '\n    xor.b32 %r3, %r2, %r1;')
                with self.assertRaisesRegex(Exception, 'PTX loop cross-thread effect'):
                    self.validate(self.write('effect.ptx', source), sass)


if __name__ == '__main__':
    verification_main()
