; ================================================
;  Generated by Y Compiler — LLVM IR Backend
;  Hardware Profile: AVX=true, AVX512=true, L2 Line=64B
; ================================================

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

attributes #0 = { "target-cpu"="znver5" "target-features"="+avx512f,+avx512cd,+avx512bw,+avx512dq,+avx512vl,+fma,+avx512vnni,+avx512bf16" }

; --- Struct Definitions ---

; --- Enum Definitions ---

; --- External Runtime Declarations ---
declare ptr @ystr_new(ptr)
declare void @ystr_push(ptr, i8)
declare void @ystr_push_str(ptr, ptr)
declare i1 @ystr_eq_cstr(ptr, ptr)
declare i64 @ystr_len(ptr)
declare i8 @ystr_char_at(ptr, i64)
declare ptr @ystr_clone(ptr)
declare ptr @yvec_new(i64)
declare void @yvec_push(ptr, ptr)
declare ptr @yvec_get(ptr, i64)
declare i64 @yvec_len(ptr)
declare ptr @yfile_read_to_string(ptr)
declare void @yfile_write(ptr, ptr)
declare i32 @printf(ptr, ...)
declare ptr @malloc(i64)
declare void @free(ptr)
declare void @exit(i32) noreturn
declare void @println(ptr)
declare void @print_int(i64)
declare void @llvm.prefetch.p0(ptr nocapture readonly, i32, i32, i32)
declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg)

@.fmt.sn = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt.s = private unnamed_addr constant [3 x i8] c"%s\00"
@.fmt.d = private unnamed_addr constant [4 x i8] c"%ld\00"
@.str.bounds_err = private unnamed_addr constant [54 x i8] c"Index out of bounds panic: index %ld, array size %ld\0A\00"

; @kernel
define void @y_cpu_matmul_kernel(ptr %A.arg, ptr %B.arg, ptr %C.arg, i32 %M.arg, i32 %N.arg, i32 %K.arg) #0 {
entry:
  %A = alloca ptr
  store ptr %A.arg, ptr %A
  %B = alloca ptr
  store ptr %B.arg, ptr %B
  %C = alloca ptr
  store ptr %C.arg, ptr %C
  %M = alloca i32
  store i32 %M.arg, ptr %M
  %N = alloca i32
  store i32 %N.arg, ptr %N
  %K = alloca i32
  store i32 %K.arg, ptr %K
  %.y_oob_sink = alloca [8 x i8], align 8
  %_t1 = load i32, ptr %M
  %_t2 = sext i32 %_t1 to i64
  %_t3 = load i32, ptr %N
  %_t4 = sext i32 %_t3 to i64
  %_t5 = load i32, ptr %K
  %_t6 = sext i32 %_t5 to i64
  %_t7 = load ptr, ptr %A
  %_t8 = load ptr, ptr %B
  %_t9 = load ptr, ptr %C
  call void @__y_sgemm_f32_avx512(ptr %_t7, ptr %_t8, ptr %_t9, i64 %_t2, i64 %_t4, i64 %_t6)
  ; [Y CPU GEMM] GemmShape { a: "A", b: "B", c: "C", m: "M", n: "N", k: "K" }
  ret void
}

define void @ysu_main() #0 {
entry:
  %.y_oob_sink = alloca [8 x i8], align 8
  ret void
}


; --- Y CPU GEMM: shared state ---
%y_gemm_task = type { ptr, ptr, ptr, i64, i64, i64, i64, i64, i64, i64, ptr, i64, i64, i64 }
@__y_gemm_scratch = internal global ptr null, align 8   ; per-thread packing scratch
@__y_gemm_scratch_threads = internal global i64 0, align 8      ; threads the scratch was sized for
@__y_gemm_nthreads = internal global i64 0, align 8      ; 0 = not yet resolved
@__y_gemm_fallback = internal global [2572288 x float] zeroinitializer, align 64  ; malloc-failure panel
@.y_gemm_env = private unnamed_addr constant [15 x i8] c"Y_NUM_THREADS\00\00"
declare <16 x float> @llvm.fmuladd.v16f32(<16 x float>, <16 x float>, <16 x float>)
declare void @llvm.masked.store.v16f32.p0(<16 x float>, ptr, i32 immarg, <16 x i1>)
declare <16 x float> @llvm.masked.load.v16f32.p0(ptr, i32 immarg, <16 x i1>, <16 x float>)
declare ptr @getenv(ptr)
declare i32 @atoi(ptr)
declare i64 @sysconf(i32)
declare i32 @pthread_create(ptr, ptr, ptr, ptr)
declare i32 @pthread_join(i64, ptr)
declare i32 @pthread_mutex_init(ptr, ptr)
declare i32 @pthread_mutex_lock(ptr)
declare i32 @pthread_mutex_unlock(ptr)
declare i32 @pthread_cond_init(ptr, ptr)
declare i32 @pthread_cond_wait(ptr, ptr)
declare i32 @pthread_cond_broadcast(ptr)
declare i32 @pthread_barrier_init(ptr, ptr, i32)
declare i32 @pthread_barrier_destroy(ptr)
declare i32 @pthread_barrier_wait(ptr)
@__y_pool_barrier = internal global [64 x i8] zeroinitializer, align 16
@__y_barrier_n = internal global i64 0, align 8   ; barrier width, 0 = uninitialised
@__y_shared_b = internal global [540672 x float] zeroinitializer, align 64
@__y_pool_mutex = internal global [64 x i8] zeroinitializer, align 16
@__y_pool_cond = internal global [64 x i8] zeroinitializer, align 16
declare void @llvm.x86.sse2.pause()
@__y_pool_n = internal global i64 0, align 8   ; workers running (0 = pool not started)
@__y_pool_gen = internal global i64 0, align 8   ; bumped once per dispatch
@__y_pool_done = internal global [16 x i64] zeroinitializer, align 64  ; generation each worker finished
@__y_pool_task = internal global [16 x %y_gemm_task] zeroinitializer, align 64
@__y_pool_ids = internal global [16 x i64] zeroinitializer, align 8    ; each worker's index

define internal void @__y_gemm_pack_b(ptr noalias %src, i64 %ldb, i64 %kc, i64 %nc, ptr noalias %dst, i64 %tid, i64 %nthr) #0 {
entry:
  %iv3 = alloca i64, align 8
  %iv15 = alloca i64, align 8
  %g1 = mul nsw i64 %tid, 64
  %g2 = mul nsw i64 %nthr, 64
  store i64 %g1, ptr %iv3
  br label %pb.j.cond.4
pb.j.cond.4:
  %g7 = load i64, ptr %iv3
  %g8 = icmp slt i64 %g7, %nc
  br i1 %g8, label %pb.j.body.5, label %pb.j.end.6
pb.j.body.5:
  %g9 = load i64, ptr %iv3
  %g10 = sub nsw i64 %nc, %g9
  %g11 = icmp slt i64 %g10, 64
  %g12 = select i1 %g11, i64 %g10, i64 64
  %g13 = mul nsw i64 %g9, %kc
  %g14 = getelementptr inbounds float, ptr %dst, i64 %g13
  store i64 0, ptr %iv15
  br label %pb.p.cond.16
pb.p.cond.16:
  %g19 = load i64, ptr %iv15
  %g20 = icmp slt i64 %g19, %kc
  br i1 %g20, label %pb.p.body.17, label %pb.p.end.18
pb.p.body.17:
  %g21 = load i64, ptr %iv15
  %g22 = mul nsw i64 %g21, %ldb
  %g23 = add nsw i64 %g22, %g9
  %g24 = getelementptr inbounds float, ptr %src, i64 %g23
  %g25 = mul nsw i64 %g21, 64
  %g26 = getelementptr inbounds float, ptr %g14, i64 %g25
  %g27 = sub nsw i64 %g12, 0
  %g28 = insertelement <16 x i64> poison, i64 %g27, i32 0
  %g29 = shufflevector <16 x i64> %g28, <16 x i64> poison, <16 x i32> zeroinitializer
  %g30 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g29
  %g31 = getelementptr inbounds float, ptr %g24, i64 0
  %g32 = getelementptr inbounds float, ptr %g26, i64 0
  %g33 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g31, i32 4, <16 x i1> %g30, <16 x float> zeroinitializer)
  store <16 x float> %g33, ptr %g32, align 4
  %g34 = sub nsw i64 %g12, 16
  %g35 = insertelement <16 x i64> poison, i64 %g34, i32 0
  %g36 = shufflevector <16 x i64> %g35, <16 x i64> poison, <16 x i32> zeroinitializer
  %g37 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g36
  %g38 = getelementptr inbounds float, ptr %g24, i64 16
  %g39 = getelementptr inbounds float, ptr %g26, i64 16
  %g40 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g38, i32 4, <16 x i1> %g37, <16 x float> zeroinitializer)
  store <16 x float> %g40, ptr %g39, align 4
  %g41 = sub nsw i64 %g12, 32
  %g42 = insertelement <16 x i64> poison, i64 %g41, i32 0
  %g43 = shufflevector <16 x i64> %g42, <16 x i64> poison, <16 x i32> zeroinitializer
  %g44 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g43
  %g45 = getelementptr inbounds float, ptr %g24, i64 32
  %g46 = getelementptr inbounds float, ptr %g26, i64 32
  %g47 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g45, i32 4, <16 x i1> %g44, <16 x float> zeroinitializer)
  store <16 x float> %g47, ptr %g46, align 4
  %g48 = sub nsw i64 %g12, 48
  %g49 = insertelement <16 x i64> poison, i64 %g48, i32 0
  %g50 = shufflevector <16 x i64> %g49, <16 x i64> poison, <16 x i32> zeroinitializer
  %g51 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g50
  %g52 = getelementptr inbounds float, ptr %g24, i64 48
  %g53 = getelementptr inbounds float, ptr %g26, i64 48
  %g54 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g52, i32 4, <16 x i1> %g51, <16 x float> zeroinitializer)
  store <16 x float> %g54, ptr %g53, align 4
  %g55 = load i64, ptr %iv15
  %g56 = add i64 %g55, 1
  store i64 %g56, ptr %iv15
  br label %pb.p.cond.16
pb.p.end.18:
  %g57 = load i64, ptr %iv3
  %g58 = add i64 %g57, %g2
  store i64 %g58, ptr %iv3
  br label %pb.j.cond.4
pb.j.end.6:
  ret void
}

define internal void @__y_gemm_pack_a(ptr noalias %src, i64 %lda, i64 %mc, i64 %kc, ptr noalias %dst) #0 {
entry:
  %iv1 = alloca i64, align 8
  %iv13 = alloca i64, align 8
  store i64 0, ptr %iv1
  br label %pa.i.cond.2
pa.i.cond.2:
  %g5 = load i64, ptr %iv1
  %g6 = icmp slt i64 %g5, %mc
  br i1 %g6, label %pa.i.body.3, label %pa.i.end.4
pa.i.body.3:
  %g7 = load i64, ptr %iv1
  %g8 = sub nsw i64 %mc, %g7
  %g9 = icmp slt i64 %g8, 6
  %g10 = select i1 %g9, i64 %g8, i64 6
  %g11 = mul nsw i64 %g7, %kc
  %g12 = getelementptr inbounds float, ptr %dst, i64 %g11
  store i64 0, ptr %iv13
  br label %pa.p.cond.14
pa.p.cond.14:
  %g17 = load i64, ptr %iv13
  %g18 = icmp slt i64 %g17, %kc
  br i1 %g18, label %pa.p.body.15, label %pa.p.end.16
pa.p.body.15:
  %g19 = load i64, ptr %iv13
  %g20 = mul nsw i64 %g19, 6
  %g21 = getelementptr inbounds float, ptr %g12, i64 %g20
  %g22 = icmp slt i64 0, %g10
  %g23 = add nsw i64 %g7, 0
  %g24 = mul nsw i64 %g23, %lda
  %g25 = add nsw i64 %g24, %g19
  %g26 = select i1 %g22, i64 %g25, i64 0
  %g27 = getelementptr inbounds float, ptr %src, i64 %g26
  %g28 = load float, ptr %g27, align 4
  %g29 = select i1 %g22, float %g28, float 0.0
  %g30 = getelementptr inbounds float, ptr %g21, i64 0
  store float %g29, ptr %g30, align 4
  %g31 = icmp slt i64 1, %g10
  %g32 = add nsw i64 %g7, 1
  %g33 = mul nsw i64 %g32, %lda
  %g34 = add nsw i64 %g33, %g19
  %g35 = select i1 %g31, i64 %g34, i64 0
  %g36 = getelementptr inbounds float, ptr %src, i64 %g35
  %g37 = load float, ptr %g36, align 4
  %g38 = select i1 %g31, float %g37, float 0.0
  %g39 = getelementptr inbounds float, ptr %g21, i64 1
  store float %g38, ptr %g39, align 4
  %g40 = icmp slt i64 2, %g10
  %g41 = add nsw i64 %g7, 2
  %g42 = mul nsw i64 %g41, %lda
  %g43 = add nsw i64 %g42, %g19
  %g44 = select i1 %g40, i64 %g43, i64 0
  %g45 = getelementptr inbounds float, ptr %src, i64 %g44
  %g46 = load float, ptr %g45, align 4
  %g47 = select i1 %g40, float %g46, float 0.0
  %g48 = getelementptr inbounds float, ptr %g21, i64 2
  store float %g47, ptr %g48, align 4
  %g49 = icmp slt i64 3, %g10
  %g50 = add nsw i64 %g7, 3
  %g51 = mul nsw i64 %g50, %lda
  %g52 = add nsw i64 %g51, %g19
  %g53 = select i1 %g49, i64 %g52, i64 0
  %g54 = getelementptr inbounds float, ptr %src, i64 %g53
  %g55 = load float, ptr %g54, align 4
  %g56 = select i1 %g49, float %g55, float 0.0
  %g57 = getelementptr inbounds float, ptr %g21, i64 3
  store float %g56, ptr %g57, align 4
  %g58 = icmp slt i64 4, %g10
  %g59 = add nsw i64 %g7, 4
  %g60 = mul nsw i64 %g59, %lda
  %g61 = add nsw i64 %g60, %g19
  %g62 = select i1 %g58, i64 %g61, i64 0
  %g63 = getelementptr inbounds float, ptr %src, i64 %g62
  %g64 = load float, ptr %g63, align 4
  %g65 = select i1 %g58, float %g64, float 0.0
  %g66 = getelementptr inbounds float, ptr %g21, i64 4
  store float %g65, ptr %g66, align 4
  %g67 = icmp slt i64 5, %g10
  %g68 = add nsw i64 %g7, 5
  %g69 = mul nsw i64 %g68, %lda
  %g70 = add nsw i64 %g69, %g19
  %g71 = select i1 %g67, i64 %g70, i64 0
  %g72 = getelementptr inbounds float, ptr %src, i64 %g71
  %g73 = load float, ptr %g72, align 4
  %g74 = select i1 %g67, float %g73, float 0.0
  %g75 = getelementptr inbounds float, ptr %g21, i64 5
  store float %g74, ptr %g75, align 4
  %g76 = load i64, ptr %iv13
  %g77 = add i64 %g76, 1
  store i64 %g77, ptr %iv13
  br label %pa.p.cond.14
pa.p.end.16:
  %g78 = load i64, ptr %iv1
  %g79 = add i64 %g78, 6
  store i64 %g79, ptr %iv1
  br label %pa.i.cond.2
pa.i.end.4:
  ret void
}

define internal void @__y_gemm_micro(ptr noalias %ap, ptr noalias %bp, i64 %ldb, ptr %c, i64 %ldc, i64 %kc, i64 %mw, i64 %jw, i1 %first) #0 {
entry:
  %acc0_0 = alloca <16 x float>, align 64
  %acc0_1 = alloca <16 x float>, align 64
  %acc0_2 = alloca <16 x float>, align 64
  %acc0_3 = alloca <16 x float>, align 64
  %acc1_0 = alloca <16 x float>, align 64
  %acc1_1 = alloca <16 x float>, align 64
  %acc1_2 = alloca <16 x float>, align 64
  %acc1_3 = alloca <16 x float>, align 64
  %acc2_0 = alloca <16 x float>, align 64
  %acc2_1 = alloca <16 x float>, align 64
  %acc2_2 = alloca <16 x float>, align 64
  %acc2_3 = alloca <16 x float>, align 64
  %acc3_0 = alloca <16 x float>, align 64
  %acc3_1 = alloca <16 x float>, align 64
  %acc3_2 = alloca <16 x float>, align 64
  %acc3_3 = alloca <16 x float>, align 64
  %acc4_0 = alloca <16 x float>, align 64
  %acc4_1 = alloca <16 x float>, align 64
  %acc4_2 = alloca <16 x float>, align 64
  %acc4_3 = alloca <16 x float>, align 64
  %acc5_0 = alloca <16 x float>, align 64
  %acc5_1 = alloca <16 x float>, align 64
  %acc5_2 = alloca <16 x float>, align 64
  %acc5_3 = alloca <16 x float>, align 64
  %iv5 = alloca i64, align 8
  %iv98 = alloca i64, align 8
  store <16 x float> zeroinitializer, ptr %acc0_0, align 64
  store <16 x float> zeroinitializer, ptr %acc0_1, align 64
  store <16 x float> zeroinitializer, ptr %acc0_2, align 64
  store <16 x float> zeroinitializer, ptr %acc0_3, align 64
  store <16 x float> zeroinitializer, ptr %acc1_0, align 64
  store <16 x float> zeroinitializer, ptr %acc1_1, align 64
  store <16 x float> zeroinitializer, ptr %acc1_2, align 64
  store <16 x float> zeroinitializer, ptr %acc1_3, align 64
  store <16 x float> zeroinitializer, ptr %acc2_0, align 64
  store <16 x float> zeroinitializer, ptr %acc2_1, align 64
  store <16 x float> zeroinitializer, ptr %acc2_2, align 64
  store <16 x float> zeroinitializer, ptr %acc2_3, align 64
  store <16 x float> zeroinitializer, ptr %acc3_0, align 64
  store <16 x float> zeroinitializer, ptr %acc3_1, align 64
  store <16 x float> zeroinitializer, ptr %acc3_2, align 64
  store <16 x float> zeroinitializer, ptr %acc3_3, align 64
  store <16 x float> zeroinitializer, ptr %acc4_0, align 64
  store <16 x float> zeroinitializer, ptr %acc4_1, align 64
  store <16 x float> zeroinitializer, ptr %acc4_2, align 64
  store <16 x float> zeroinitializer, ptr %acc4_3, align 64
  store <16 x float> zeroinitializer, ptr %acc5_0, align 64
  store <16 x float> zeroinitializer, ptr %acc5_1, align 64
  store <16 x float> zeroinitializer, ptr %acc5_2, align 64
  store <16 x float> zeroinitializer, ptr %acc5_3, align 64
  %g1 = icmp eq i64 %jw, 64
  br i1 %g1, label %mk.full.2, label %mk.tail.3
mk.full.2:
  store i64 0, ptr %iv5
  br label %mk.p.cond.6
mk.p.cond.6:
  %g9 = load i64, ptr %iv5
  %g10 = icmp slt i64 %g9, %kc
  br i1 %g10, label %mk.p.body.7, label %mk.p.end.8
mk.p.body.7:
  %g11 = load i64, ptr %iv5
  %g12 = mul nsw i64 %g11, %ldb
  %g13 = getelementptr inbounds float, ptr %bp, i64 %g12
  %g14 = getelementptr inbounds float, ptr %g13, i64 0
  %g15 = load <16 x float>, ptr %g14, align 4
  %g16 = getelementptr inbounds float, ptr %g13, i64 16
  %g17 = load <16 x float>, ptr %g16, align 4
  %g18 = getelementptr inbounds float, ptr %g13, i64 32
  %g19 = load <16 x float>, ptr %g18, align 4
  %g20 = getelementptr inbounds float, ptr %g13, i64 48
  %g21 = load <16 x float>, ptr %g20, align 4
  %g22 = mul nsw i64 %g11, 6
  %g23 = getelementptr inbounds float, ptr %ap, i64 %g22
  %g24 = getelementptr inbounds float, ptr %g23, i64 0
  %g25 = load float, ptr %g24, align 4
  %g26 = insertelement <16 x float> poison, float %g25, i32 0
  %g27 = shufflevector <16 x float> %g26, <16 x float> poison, <16 x i32> zeroinitializer
  %g28 = load <16 x float>, ptr %acc0_0, align 64
  %g29 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g27, <16 x float> %g15, <16 x float> %g28)
  store <16 x float> %g29, ptr %acc0_0, align 64
  %g30 = load <16 x float>, ptr %acc0_1, align 64
  %g31 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g27, <16 x float> %g17, <16 x float> %g30)
  store <16 x float> %g31, ptr %acc0_1, align 64
  %g32 = load <16 x float>, ptr %acc0_2, align 64
  %g33 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g27, <16 x float> %g19, <16 x float> %g32)
  store <16 x float> %g33, ptr %acc0_2, align 64
  %g34 = load <16 x float>, ptr %acc0_3, align 64
  %g35 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g27, <16 x float> %g21, <16 x float> %g34)
  store <16 x float> %g35, ptr %acc0_3, align 64
  %g36 = getelementptr inbounds float, ptr %g23, i64 1
  %g37 = load float, ptr %g36, align 4
  %g38 = insertelement <16 x float> poison, float %g37, i32 0
  %g39 = shufflevector <16 x float> %g38, <16 x float> poison, <16 x i32> zeroinitializer
  %g40 = load <16 x float>, ptr %acc1_0, align 64
  %g41 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g39, <16 x float> %g15, <16 x float> %g40)
  store <16 x float> %g41, ptr %acc1_0, align 64
  %g42 = load <16 x float>, ptr %acc1_1, align 64
  %g43 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g39, <16 x float> %g17, <16 x float> %g42)
  store <16 x float> %g43, ptr %acc1_1, align 64
  %g44 = load <16 x float>, ptr %acc1_2, align 64
  %g45 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g39, <16 x float> %g19, <16 x float> %g44)
  store <16 x float> %g45, ptr %acc1_2, align 64
  %g46 = load <16 x float>, ptr %acc1_3, align 64
  %g47 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g39, <16 x float> %g21, <16 x float> %g46)
  store <16 x float> %g47, ptr %acc1_3, align 64
  %g48 = getelementptr inbounds float, ptr %g23, i64 2
  %g49 = load float, ptr %g48, align 4
  %g50 = insertelement <16 x float> poison, float %g49, i32 0
  %g51 = shufflevector <16 x float> %g50, <16 x float> poison, <16 x i32> zeroinitializer
  %g52 = load <16 x float>, ptr %acc2_0, align 64
  %g53 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g51, <16 x float> %g15, <16 x float> %g52)
  store <16 x float> %g53, ptr %acc2_0, align 64
  %g54 = load <16 x float>, ptr %acc2_1, align 64
  %g55 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g51, <16 x float> %g17, <16 x float> %g54)
  store <16 x float> %g55, ptr %acc2_1, align 64
  %g56 = load <16 x float>, ptr %acc2_2, align 64
  %g57 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g51, <16 x float> %g19, <16 x float> %g56)
  store <16 x float> %g57, ptr %acc2_2, align 64
  %g58 = load <16 x float>, ptr %acc2_3, align 64
  %g59 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g51, <16 x float> %g21, <16 x float> %g58)
  store <16 x float> %g59, ptr %acc2_3, align 64
  %g60 = getelementptr inbounds float, ptr %g23, i64 3
  %g61 = load float, ptr %g60, align 4
  %g62 = insertelement <16 x float> poison, float %g61, i32 0
  %g63 = shufflevector <16 x float> %g62, <16 x float> poison, <16 x i32> zeroinitializer
  %g64 = load <16 x float>, ptr %acc3_0, align 64
  %g65 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g63, <16 x float> %g15, <16 x float> %g64)
  store <16 x float> %g65, ptr %acc3_0, align 64
  %g66 = load <16 x float>, ptr %acc3_1, align 64
  %g67 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g63, <16 x float> %g17, <16 x float> %g66)
  store <16 x float> %g67, ptr %acc3_1, align 64
  %g68 = load <16 x float>, ptr %acc3_2, align 64
  %g69 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g63, <16 x float> %g19, <16 x float> %g68)
  store <16 x float> %g69, ptr %acc3_2, align 64
  %g70 = load <16 x float>, ptr %acc3_3, align 64
  %g71 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g63, <16 x float> %g21, <16 x float> %g70)
  store <16 x float> %g71, ptr %acc3_3, align 64
  %g72 = getelementptr inbounds float, ptr %g23, i64 4
  %g73 = load float, ptr %g72, align 4
  %g74 = insertelement <16 x float> poison, float %g73, i32 0
  %g75 = shufflevector <16 x float> %g74, <16 x float> poison, <16 x i32> zeroinitializer
  %g76 = load <16 x float>, ptr %acc4_0, align 64
  %g77 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g75, <16 x float> %g15, <16 x float> %g76)
  store <16 x float> %g77, ptr %acc4_0, align 64
  %g78 = load <16 x float>, ptr %acc4_1, align 64
  %g79 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g75, <16 x float> %g17, <16 x float> %g78)
  store <16 x float> %g79, ptr %acc4_1, align 64
  %g80 = load <16 x float>, ptr %acc4_2, align 64
  %g81 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g75, <16 x float> %g19, <16 x float> %g80)
  store <16 x float> %g81, ptr %acc4_2, align 64
  %g82 = load <16 x float>, ptr %acc4_3, align 64
  %g83 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g75, <16 x float> %g21, <16 x float> %g82)
  store <16 x float> %g83, ptr %acc4_3, align 64
  %g84 = getelementptr inbounds float, ptr %g23, i64 5
  %g85 = load float, ptr %g84, align 4
  %g86 = insertelement <16 x float> poison, float %g85, i32 0
  %g87 = shufflevector <16 x float> %g86, <16 x float> poison, <16 x i32> zeroinitializer
  %g88 = load <16 x float>, ptr %acc5_0, align 64
  %g89 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g87, <16 x float> %g15, <16 x float> %g88)
  store <16 x float> %g89, ptr %acc5_0, align 64
  %g90 = load <16 x float>, ptr %acc5_1, align 64
  %g91 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g87, <16 x float> %g17, <16 x float> %g90)
  store <16 x float> %g91, ptr %acc5_1, align 64
  %g92 = load <16 x float>, ptr %acc5_2, align 64
  %g93 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g87, <16 x float> %g19, <16 x float> %g92)
  store <16 x float> %g93, ptr %acc5_2, align 64
  %g94 = load <16 x float>, ptr %acc5_3, align 64
  %g95 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g87, <16 x float> %g21, <16 x float> %g94)
  store <16 x float> %g95, ptr %acc5_3, align 64
  %g96 = load i64, ptr %iv5
  %g97 = add i64 %g96, 1
  store i64 %g97, ptr %iv5
  br label %mk.p.cond.6
mk.p.end.8:
  br label %mk.epi.4
mk.tail.3:
  store i64 0, ptr %iv98
  br label %mk.p.cond.99
mk.p.cond.99:
  %g102 = load i64, ptr %iv98
  %g103 = icmp slt i64 %g102, %kc
  br i1 %g103, label %mk.p.body.100, label %mk.p.end.101
mk.p.body.100:
  %g104 = load i64, ptr %iv98
  %g105 = mul nsw i64 %g104, %ldb
  %g106 = getelementptr inbounds float, ptr %bp, i64 %g105
  %g107 = getelementptr inbounds float, ptr %g106, i64 0
  %g109 = sub nsw i64 %jw, 0
  %g110 = insertelement <16 x i64> poison, i64 %g109, i32 0
  %g111 = shufflevector <16 x i64> %g110, <16 x i64> poison, <16 x i32> zeroinitializer
  %g112 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g111
  %g108 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g107, i32 4, <16 x i1> %g112, <16 x float> zeroinitializer)
  %g113 = getelementptr inbounds float, ptr %g106, i64 16
  %g115 = sub nsw i64 %jw, 16
  %g116 = insertelement <16 x i64> poison, i64 %g115, i32 0
  %g117 = shufflevector <16 x i64> %g116, <16 x i64> poison, <16 x i32> zeroinitializer
  %g118 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g117
  %g114 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g113, i32 4, <16 x i1> %g118, <16 x float> zeroinitializer)
  %g119 = getelementptr inbounds float, ptr %g106, i64 32
  %g121 = sub nsw i64 %jw, 32
  %g122 = insertelement <16 x i64> poison, i64 %g121, i32 0
  %g123 = shufflevector <16 x i64> %g122, <16 x i64> poison, <16 x i32> zeroinitializer
  %g124 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g123
  %g120 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g119, i32 4, <16 x i1> %g124, <16 x float> zeroinitializer)
  %g125 = getelementptr inbounds float, ptr %g106, i64 48
  %g127 = sub nsw i64 %jw, 48
  %g128 = insertelement <16 x i64> poison, i64 %g127, i32 0
  %g129 = shufflevector <16 x i64> %g128, <16 x i64> poison, <16 x i32> zeroinitializer
  %g130 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g129
  %g126 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g125, i32 4, <16 x i1> %g130, <16 x float> zeroinitializer)
  %g131 = mul nsw i64 %g104, 6
  %g132 = getelementptr inbounds float, ptr %ap, i64 %g131
  %g133 = getelementptr inbounds float, ptr %g132, i64 0
  %g134 = load float, ptr %g133, align 4
  %g135 = insertelement <16 x float> poison, float %g134, i32 0
  %g136 = shufflevector <16 x float> %g135, <16 x float> poison, <16 x i32> zeroinitializer
  %g137 = load <16 x float>, ptr %acc0_0, align 64
  %g138 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g136, <16 x float> %g108, <16 x float> %g137)
  store <16 x float> %g138, ptr %acc0_0, align 64
  %g139 = load <16 x float>, ptr %acc0_1, align 64
  %g140 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g136, <16 x float> %g114, <16 x float> %g139)
  store <16 x float> %g140, ptr %acc0_1, align 64
  %g141 = load <16 x float>, ptr %acc0_2, align 64
  %g142 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g136, <16 x float> %g120, <16 x float> %g141)
  store <16 x float> %g142, ptr %acc0_2, align 64
  %g143 = load <16 x float>, ptr %acc0_3, align 64
  %g144 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g136, <16 x float> %g126, <16 x float> %g143)
  store <16 x float> %g144, ptr %acc0_3, align 64
  %g145 = getelementptr inbounds float, ptr %g132, i64 1
  %g146 = load float, ptr %g145, align 4
  %g147 = insertelement <16 x float> poison, float %g146, i32 0
  %g148 = shufflevector <16 x float> %g147, <16 x float> poison, <16 x i32> zeroinitializer
  %g149 = load <16 x float>, ptr %acc1_0, align 64
  %g150 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g148, <16 x float> %g108, <16 x float> %g149)
  store <16 x float> %g150, ptr %acc1_0, align 64
  %g151 = load <16 x float>, ptr %acc1_1, align 64
  %g152 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g148, <16 x float> %g114, <16 x float> %g151)
  store <16 x float> %g152, ptr %acc1_1, align 64
  %g153 = load <16 x float>, ptr %acc1_2, align 64
  %g154 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g148, <16 x float> %g120, <16 x float> %g153)
  store <16 x float> %g154, ptr %acc1_2, align 64
  %g155 = load <16 x float>, ptr %acc1_3, align 64
  %g156 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g148, <16 x float> %g126, <16 x float> %g155)
  store <16 x float> %g156, ptr %acc1_3, align 64
  %g157 = getelementptr inbounds float, ptr %g132, i64 2
  %g158 = load float, ptr %g157, align 4
  %g159 = insertelement <16 x float> poison, float %g158, i32 0
  %g160 = shufflevector <16 x float> %g159, <16 x float> poison, <16 x i32> zeroinitializer
  %g161 = load <16 x float>, ptr %acc2_0, align 64
  %g162 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g160, <16 x float> %g108, <16 x float> %g161)
  store <16 x float> %g162, ptr %acc2_0, align 64
  %g163 = load <16 x float>, ptr %acc2_1, align 64
  %g164 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g160, <16 x float> %g114, <16 x float> %g163)
  store <16 x float> %g164, ptr %acc2_1, align 64
  %g165 = load <16 x float>, ptr %acc2_2, align 64
  %g166 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g160, <16 x float> %g120, <16 x float> %g165)
  store <16 x float> %g166, ptr %acc2_2, align 64
  %g167 = load <16 x float>, ptr %acc2_3, align 64
  %g168 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g160, <16 x float> %g126, <16 x float> %g167)
  store <16 x float> %g168, ptr %acc2_3, align 64
  %g169 = getelementptr inbounds float, ptr %g132, i64 3
  %g170 = load float, ptr %g169, align 4
  %g171 = insertelement <16 x float> poison, float %g170, i32 0
  %g172 = shufflevector <16 x float> %g171, <16 x float> poison, <16 x i32> zeroinitializer
  %g173 = load <16 x float>, ptr %acc3_0, align 64
  %g174 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g172, <16 x float> %g108, <16 x float> %g173)
  store <16 x float> %g174, ptr %acc3_0, align 64
  %g175 = load <16 x float>, ptr %acc3_1, align 64
  %g176 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g172, <16 x float> %g114, <16 x float> %g175)
  store <16 x float> %g176, ptr %acc3_1, align 64
  %g177 = load <16 x float>, ptr %acc3_2, align 64
  %g178 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g172, <16 x float> %g120, <16 x float> %g177)
  store <16 x float> %g178, ptr %acc3_2, align 64
  %g179 = load <16 x float>, ptr %acc3_3, align 64
  %g180 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g172, <16 x float> %g126, <16 x float> %g179)
  store <16 x float> %g180, ptr %acc3_3, align 64
  %g181 = getelementptr inbounds float, ptr %g132, i64 4
  %g182 = load float, ptr %g181, align 4
  %g183 = insertelement <16 x float> poison, float %g182, i32 0
  %g184 = shufflevector <16 x float> %g183, <16 x float> poison, <16 x i32> zeroinitializer
  %g185 = load <16 x float>, ptr %acc4_0, align 64
  %g186 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g184, <16 x float> %g108, <16 x float> %g185)
  store <16 x float> %g186, ptr %acc4_0, align 64
  %g187 = load <16 x float>, ptr %acc4_1, align 64
  %g188 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g184, <16 x float> %g114, <16 x float> %g187)
  store <16 x float> %g188, ptr %acc4_1, align 64
  %g189 = load <16 x float>, ptr %acc4_2, align 64
  %g190 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g184, <16 x float> %g120, <16 x float> %g189)
  store <16 x float> %g190, ptr %acc4_2, align 64
  %g191 = load <16 x float>, ptr %acc4_3, align 64
  %g192 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g184, <16 x float> %g126, <16 x float> %g191)
  store <16 x float> %g192, ptr %acc4_3, align 64
  %g193 = getelementptr inbounds float, ptr %g132, i64 5
  %g194 = load float, ptr %g193, align 4
  %g195 = insertelement <16 x float> poison, float %g194, i32 0
  %g196 = shufflevector <16 x float> %g195, <16 x float> poison, <16 x i32> zeroinitializer
  %g197 = load <16 x float>, ptr %acc5_0, align 64
  %g198 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g196, <16 x float> %g108, <16 x float> %g197)
  store <16 x float> %g198, ptr %acc5_0, align 64
  %g199 = load <16 x float>, ptr %acc5_1, align 64
  %g200 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g196, <16 x float> %g114, <16 x float> %g199)
  store <16 x float> %g200, ptr %acc5_1, align 64
  %g201 = load <16 x float>, ptr %acc5_2, align 64
  %g202 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g196, <16 x float> %g120, <16 x float> %g201)
  store <16 x float> %g202, ptr %acc5_2, align 64
  %g203 = load <16 x float>, ptr %acc5_3, align 64
  %g204 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g196, <16 x float> %g126, <16 x float> %g203)
  store <16 x float> %g204, ptr %acc5_3, align 64
  %g205 = load i64, ptr %iv98
  %g206 = add i64 %g205, 1
  store i64 %g206, ptr %iv98
  br label %mk.p.cond.99
mk.p.end.101:
  br label %mk.epi.4
mk.epi.4:
  br i1 %first, label %mk.first.208, label %mk.acc.207
mk.first.208:
  %g210 = icmp slt i64 0, %mw
  br i1 %g210, label %mk.st.211, label %mk.sk.212
mk.st.211:
  %g213 = mul nsw i64 0, %ldc
  %g214 = getelementptr inbounds float, ptr %c, i64 %g213
  %g215 = sub nsw i64 %jw, 0
  %g216 = insertelement <16 x i64> poison, i64 %g215, i32 0
  %g217 = shufflevector <16 x i64> %g216, <16 x i64> poison, <16 x i32> zeroinitializer
  %g218 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g217
  %g219 = getelementptr inbounds float, ptr %g214, i64 0
  %g220 = load <16 x float>, ptr %acc0_0, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g220, ptr %g219, i32 4, <16 x i1> %g218)
  %g221 = sub nsw i64 %jw, 16
  %g222 = insertelement <16 x i64> poison, i64 %g221, i32 0
  %g223 = shufflevector <16 x i64> %g222, <16 x i64> poison, <16 x i32> zeroinitializer
  %g224 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g223
  %g225 = getelementptr inbounds float, ptr %g214, i64 16
  %g226 = load <16 x float>, ptr %acc0_1, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g226, ptr %g225, i32 4, <16 x i1> %g224)
  %g227 = sub nsw i64 %jw, 32
  %g228 = insertelement <16 x i64> poison, i64 %g227, i32 0
  %g229 = shufflevector <16 x i64> %g228, <16 x i64> poison, <16 x i32> zeroinitializer
  %g230 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g229
  %g231 = getelementptr inbounds float, ptr %g214, i64 32
  %g232 = load <16 x float>, ptr %acc0_2, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g232, ptr %g231, i32 4, <16 x i1> %g230)
  %g233 = sub nsw i64 %jw, 48
  %g234 = insertelement <16 x i64> poison, i64 %g233, i32 0
  %g235 = shufflevector <16 x i64> %g234, <16 x i64> poison, <16 x i32> zeroinitializer
  %g236 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g235
  %g237 = getelementptr inbounds float, ptr %g214, i64 48
  %g238 = load <16 x float>, ptr %acc0_3, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g238, ptr %g237, i32 4, <16 x i1> %g236)
  br label %mk.sk.212
mk.sk.212:
  %g239 = icmp slt i64 1, %mw
  br i1 %g239, label %mk.st.240, label %mk.sk.241
mk.st.240:
  %g242 = mul nsw i64 1, %ldc
  %g243 = getelementptr inbounds float, ptr %c, i64 %g242
  %g244 = sub nsw i64 %jw, 0
  %g245 = insertelement <16 x i64> poison, i64 %g244, i32 0
  %g246 = shufflevector <16 x i64> %g245, <16 x i64> poison, <16 x i32> zeroinitializer
  %g247 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g246
  %g248 = getelementptr inbounds float, ptr %g243, i64 0
  %g249 = load <16 x float>, ptr %acc1_0, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g249, ptr %g248, i32 4, <16 x i1> %g247)
  %g250 = sub nsw i64 %jw, 16
  %g251 = insertelement <16 x i64> poison, i64 %g250, i32 0
  %g252 = shufflevector <16 x i64> %g251, <16 x i64> poison, <16 x i32> zeroinitializer
  %g253 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g252
  %g254 = getelementptr inbounds float, ptr %g243, i64 16
  %g255 = load <16 x float>, ptr %acc1_1, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g255, ptr %g254, i32 4, <16 x i1> %g253)
  %g256 = sub nsw i64 %jw, 32
  %g257 = insertelement <16 x i64> poison, i64 %g256, i32 0
  %g258 = shufflevector <16 x i64> %g257, <16 x i64> poison, <16 x i32> zeroinitializer
  %g259 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g258
  %g260 = getelementptr inbounds float, ptr %g243, i64 32
  %g261 = load <16 x float>, ptr %acc1_2, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g261, ptr %g260, i32 4, <16 x i1> %g259)
  %g262 = sub nsw i64 %jw, 48
  %g263 = insertelement <16 x i64> poison, i64 %g262, i32 0
  %g264 = shufflevector <16 x i64> %g263, <16 x i64> poison, <16 x i32> zeroinitializer
  %g265 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g264
  %g266 = getelementptr inbounds float, ptr %g243, i64 48
  %g267 = load <16 x float>, ptr %acc1_3, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g267, ptr %g266, i32 4, <16 x i1> %g265)
  br label %mk.sk.241
mk.sk.241:
  %g268 = icmp slt i64 2, %mw
  br i1 %g268, label %mk.st.269, label %mk.sk.270
mk.st.269:
  %g271 = mul nsw i64 2, %ldc
  %g272 = getelementptr inbounds float, ptr %c, i64 %g271
  %g273 = sub nsw i64 %jw, 0
  %g274 = insertelement <16 x i64> poison, i64 %g273, i32 0
  %g275 = shufflevector <16 x i64> %g274, <16 x i64> poison, <16 x i32> zeroinitializer
  %g276 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g275
  %g277 = getelementptr inbounds float, ptr %g272, i64 0
  %g278 = load <16 x float>, ptr %acc2_0, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g278, ptr %g277, i32 4, <16 x i1> %g276)
  %g279 = sub nsw i64 %jw, 16
  %g280 = insertelement <16 x i64> poison, i64 %g279, i32 0
  %g281 = shufflevector <16 x i64> %g280, <16 x i64> poison, <16 x i32> zeroinitializer
  %g282 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g281
  %g283 = getelementptr inbounds float, ptr %g272, i64 16
  %g284 = load <16 x float>, ptr %acc2_1, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g284, ptr %g283, i32 4, <16 x i1> %g282)
  %g285 = sub nsw i64 %jw, 32
  %g286 = insertelement <16 x i64> poison, i64 %g285, i32 0
  %g287 = shufflevector <16 x i64> %g286, <16 x i64> poison, <16 x i32> zeroinitializer
  %g288 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g287
  %g289 = getelementptr inbounds float, ptr %g272, i64 32
  %g290 = load <16 x float>, ptr %acc2_2, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g290, ptr %g289, i32 4, <16 x i1> %g288)
  %g291 = sub nsw i64 %jw, 48
  %g292 = insertelement <16 x i64> poison, i64 %g291, i32 0
  %g293 = shufflevector <16 x i64> %g292, <16 x i64> poison, <16 x i32> zeroinitializer
  %g294 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g293
  %g295 = getelementptr inbounds float, ptr %g272, i64 48
  %g296 = load <16 x float>, ptr %acc2_3, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g296, ptr %g295, i32 4, <16 x i1> %g294)
  br label %mk.sk.270
mk.sk.270:
  %g297 = icmp slt i64 3, %mw
  br i1 %g297, label %mk.st.298, label %mk.sk.299
mk.st.298:
  %g300 = mul nsw i64 3, %ldc
  %g301 = getelementptr inbounds float, ptr %c, i64 %g300
  %g302 = sub nsw i64 %jw, 0
  %g303 = insertelement <16 x i64> poison, i64 %g302, i32 0
  %g304 = shufflevector <16 x i64> %g303, <16 x i64> poison, <16 x i32> zeroinitializer
  %g305 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g304
  %g306 = getelementptr inbounds float, ptr %g301, i64 0
  %g307 = load <16 x float>, ptr %acc3_0, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g307, ptr %g306, i32 4, <16 x i1> %g305)
  %g308 = sub nsw i64 %jw, 16
  %g309 = insertelement <16 x i64> poison, i64 %g308, i32 0
  %g310 = shufflevector <16 x i64> %g309, <16 x i64> poison, <16 x i32> zeroinitializer
  %g311 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g310
  %g312 = getelementptr inbounds float, ptr %g301, i64 16
  %g313 = load <16 x float>, ptr %acc3_1, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g313, ptr %g312, i32 4, <16 x i1> %g311)
  %g314 = sub nsw i64 %jw, 32
  %g315 = insertelement <16 x i64> poison, i64 %g314, i32 0
  %g316 = shufflevector <16 x i64> %g315, <16 x i64> poison, <16 x i32> zeroinitializer
  %g317 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g316
  %g318 = getelementptr inbounds float, ptr %g301, i64 32
  %g319 = load <16 x float>, ptr %acc3_2, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g319, ptr %g318, i32 4, <16 x i1> %g317)
  %g320 = sub nsw i64 %jw, 48
  %g321 = insertelement <16 x i64> poison, i64 %g320, i32 0
  %g322 = shufflevector <16 x i64> %g321, <16 x i64> poison, <16 x i32> zeroinitializer
  %g323 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g322
  %g324 = getelementptr inbounds float, ptr %g301, i64 48
  %g325 = load <16 x float>, ptr %acc3_3, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g325, ptr %g324, i32 4, <16 x i1> %g323)
  br label %mk.sk.299
mk.sk.299:
  %g326 = icmp slt i64 4, %mw
  br i1 %g326, label %mk.st.327, label %mk.sk.328
mk.st.327:
  %g329 = mul nsw i64 4, %ldc
  %g330 = getelementptr inbounds float, ptr %c, i64 %g329
  %g331 = sub nsw i64 %jw, 0
  %g332 = insertelement <16 x i64> poison, i64 %g331, i32 0
  %g333 = shufflevector <16 x i64> %g332, <16 x i64> poison, <16 x i32> zeroinitializer
  %g334 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g333
  %g335 = getelementptr inbounds float, ptr %g330, i64 0
  %g336 = load <16 x float>, ptr %acc4_0, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g336, ptr %g335, i32 4, <16 x i1> %g334)
  %g337 = sub nsw i64 %jw, 16
  %g338 = insertelement <16 x i64> poison, i64 %g337, i32 0
  %g339 = shufflevector <16 x i64> %g338, <16 x i64> poison, <16 x i32> zeroinitializer
  %g340 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g339
  %g341 = getelementptr inbounds float, ptr %g330, i64 16
  %g342 = load <16 x float>, ptr %acc4_1, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g342, ptr %g341, i32 4, <16 x i1> %g340)
  %g343 = sub nsw i64 %jw, 32
  %g344 = insertelement <16 x i64> poison, i64 %g343, i32 0
  %g345 = shufflevector <16 x i64> %g344, <16 x i64> poison, <16 x i32> zeroinitializer
  %g346 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g345
  %g347 = getelementptr inbounds float, ptr %g330, i64 32
  %g348 = load <16 x float>, ptr %acc4_2, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g348, ptr %g347, i32 4, <16 x i1> %g346)
  %g349 = sub nsw i64 %jw, 48
  %g350 = insertelement <16 x i64> poison, i64 %g349, i32 0
  %g351 = shufflevector <16 x i64> %g350, <16 x i64> poison, <16 x i32> zeroinitializer
  %g352 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g351
  %g353 = getelementptr inbounds float, ptr %g330, i64 48
  %g354 = load <16 x float>, ptr %acc4_3, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g354, ptr %g353, i32 4, <16 x i1> %g352)
  br label %mk.sk.328
mk.sk.328:
  %g355 = icmp slt i64 5, %mw
  br i1 %g355, label %mk.st.356, label %mk.sk.357
mk.st.356:
  %g358 = mul nsw i64 5, %ldc
  %g359 = getelementptr inbounds float, ptr %c, i64 %g358
  %g360 = sub nsw i64 %jw, 0
  %g361 = insertelement <16 x i64> poison, i64 %g360, i32 0
  %g362 = shufflevector <16 x i64> %g361, <16 x i64> poison, <16 x i32> zeroinitializer
  %g363 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g362
  %g364 = getelementptr inbounds float, ptr %g359, i64 0
  %g365 = load <16 x float>, ptr %acc5_0, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g365, ptr %g364, i32 4, <16 x i1> %g363)
  %g366 = sub nsw i64 %jw, 16
  %g367 = insertelement <16 x i64> poison, i64 %g366, i32 0
  %g368 = shufflevector <16 x i64> %g367, <16 x i64> poison, <16 x i32> zeroinitializer
  %g369 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g368
  %g370 = getelementptr inbounds float, ptr %g359, i64 16
  %g371 = load <16 x float>, ptr %acc5_1, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g371, ptr %g370, i32 4, <16 x i1> %g369)
  %g372 = sub nsw i64 %jw, 32
  %g373 = insertelement <16 x i64> poison, i64 %g372, i32 0
  %g374 = shufflevector <16 x i64> %g373, <16 x i64> poison, <16 x i32> zeroinitializer
  %g375 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g374
  %g376 = getelementptr inbounds float, ptr %g359, i64 32
  %g377 = load <16 x float>, ptr %acc5_2, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g377, ptr %g376, i32 4, <16 x i1> %g375)
  %g378 = sub nsw i64 %jw, 48
  %g379 = insertelement <16 x i64> poison, i64 %g378, i32 0
  %g380 = shufflevector <16 x i64> %g379, <16 x i64> poison, <16 x i32> zeroinitializer
  %g381 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g380
  %g382 = getelementptr inbounds float, ptr %g359, i64 48
  %g383 = load <16 x float>, ptr %acc5_3, align 64
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g383, ptr %g382, i32 4, <16 x i1> %g381)
  br label %mk.sk.357
mk.sk.357:
  br label %mk.done.209
mk.acc.207:
  %g384 = icmp slt i64 0, %mw
  br i1 %g384, label %mk.st.385, label %mk.sk.386
mk.st.385:
  %g387 = mul nsw i64 0, %ldc
  %g388 = getelementptr inbounds float, ptr %c, i64 %g387
  %g389 = sub nsw i64 %jw, 0
  %g390 = insertelement <16 x i64> poison, i64 %g389, i32 0
  %g391 = shufflevector <16 x i64> %g390, <16 x i64> poison, <16 x i32> zeroinitializer
  %g392 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g391
  %g393 = getelementptr inbounds float, ptr %g388, i64 0
  %g394 = load <16 x float>, ptr %acc0_0, align 64
  %g395 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g393, i32 4, <16 x i1> %g392, <16 x float> zeroinitializer)
  %g396 = fadd <16 x float> %g394, %g395
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g396, ptr %g393, i32 4, <16 x i1> %g392)
  %g397 = sub nsw i64 %jw, 16
  %g398 = insertelement <16 x i64> poison, i64 %g397, i32 0
  %g399 = shufflevector <16 x i64> %g398, <16 x i64> poison, <16 x i32> zeroinitializer
  %g400 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g399
  %g401 = getelementptr inbounds float, ptr %g388, i64 16
  %g402 = load <16 x float>, ptr %acc0_1, align 64
  %g403 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g401, i32 4, <16 x i1> %g400, <16 x float> zeroinitializer)
  %g404 = fadd <16 x float> %g402, %g403
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g404, ptr %g401, i32 4, <16 x i1> %g400)
  %g405 = sub nsw i64 %jw, 32
  %g406 = insertelement <16 x i64> poison, i64 %g405, i32 0
  %g407 = shufflevector <16 x i64> %g406, <16 x i64> poison, <16 x i32> zeroinitializer
  %g408 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g407
  %g409 = getelementptr inbounds float, ptr %g388, i64 32
  %g410 = load <16 x float>, ptr %acc0_2, align 64
  %g411 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g409, i32 4, <16 x i1> %g408, <16 x float> zeroinitializer)
  %g412 = fadd <16 x float> %g410, %g411
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g412, ptr %g409, i32 4, <16 x i1> %g408)
  %g413 = sub nsw i64 %jw, 48
  %g414 = insertelement <16 x i64> poison, i64 %g413, i32 0
  %g415 = shufflevector <16 x i64> %g414, <16 x i64> poison, <16 x i32> zeroinitializer
  %g416 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g415
  %g417 = getelementptr inbounds float, ptr %g388, i64 48
  %g418 = load <16 x float>, ptr %acc0_3, align 64
  %g419 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g417, i32 4, <16 x i1> %g416, <16 x float> zeroinitializer)
  %g420 = fadd <16 x float> %g418, %g419
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g420, ptr %g417, i32 4, <16 x i1> %g416)
  br label %mk.sk.386
mk.sk.386:
  %g421 = icmp slt i64 1, %mw
  br i1 %g421, label %mk.st.422, label %mk.sk.423
mk.st.422:
  %g424 = mul nsw i64 1, %ldc
  %g425 = getelementptr inbounds float, ptr %c, i64 %g424
  %g426 = sub nsw i64 %jw, 0
  %g427 = insertelement <16 x i64> poison, i64 %g426, i32 0
  %g428 = shufflevector <16 x i64> %g427, <16 x i64> poison, <16 x i32> zeroinitializer
  %g429 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g428
  %g430 = getelementptr inbounds float, ptr %g425, i64 0
  %g431 = load <16 x float>, ptr %acc1_0, align 64
  %g432 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g430, i32 4, <16 x i1> %g429, <16 x float> zeroinitializer)
  %g433 = fadd <16 x float> %g431, %g432
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g433, ptr %g430, i32 4, <16 x i1> %g429)
  %g434 = sub nsw i64 %jw, 16
  %g435 = insertelement <16 x i64> poison, i64 %g434, i32 0
  %g436 = shufflevector <16 x i64> %g435, <16 x i64> poison, <16 x i32> zeroinitializer
  %g437 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g436
  %g438 = getelementptr inbounds float, ptr %g425, i64 16
  %g439 = load <16 x float>, ptr %acc1_1, align 64
  %g440 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g438, i32 4, <16 x i1> %g437, <16 x float> zeroinitializer)
  %g441 = fadd <16 x float> %g439, %g440
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g441, ptr %g438, i32 4, <16 x i1> %g437)
  %g442 = sub nsw i64 %jw, 32
  %g443 = insertelement <16 x i64> poison, i64 %g442, i32 0
  %g444 = shufflevector <16 x i64> %g443, <16 x i64> poison, <16 x i32> zeroinitializer
  %g445 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g444
  %g446 = getelementptr inbounds float, ptr %g425, i64 32
  %g447 = load <16 x float>, ptr %acc1_2, align 64
  %g448 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g446, i32 4, <16 x i1> %g445, <16 x float> zeroinitializer)
  %g449 = fadd <16 x float> %g447, %g448
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g449, ptr %g446, i32 4, <16 x i1> %g445)
  %g450 = sub nsw i64 %jw, 48
  %g451 = insertelement <16 x i64> poison, i64 %g450, i32 0
  %g452 = shufflevector <16 x i64> %g451, <16 x i64> poison, <16 x i32> zeroinitializer
  %g453 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g452
  %g454 = getelementptr inbounds float, ptr %g425, i64 48
  %g455 = load <16 x float>, ptr %acc1_3, align 64
  %g456 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g454, i32 4, <16 x i1> %g453, <16 x float> zeroinitializer)
  %g457 = fadd <16 x float> %g455, %g456
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g457, ptr %g454, i32 4, <16 x i1> %g453)
  br label %mk.sk.423
mk.sk.423:
  %g458 = icmp slt i64 2, %mw
  br i1 %g458, label %mk.st.459, label %mk.sk.460
mk.st.459:
  %g461 = mul nsw i64 2, %ldc
  %g462 = getelementptr inbounds float, ptr %c, i64 %g461
  %g463 = sub nsw i64 %jw, 0
  %g464 = insertelement <16 x i64> poison, i64 %g463, i32 0
  %g465 = shufflevector <16 x i64> %g464, <16 x i64> poison, <16 x i32> zeroinitializer
  %g466 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g465
  %g467 = getelementptr inbounds float, ptr %g462, i64 0
  %g468 = load <16 x float>, ptr %acc2_0, align 64
  %g469 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g467, i32 4, <16 x i1> %g466, <16 x float> zeroinitializer)
  %g470 = fadd <16 x float> %g468, %g469
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g470, ptr %g467, i32 4, <16 x i1> %g466)
  %g471 = sub nsw i64 %jw, 16
  %g472 = insertelement <16 x i64> poison, i64 %g471, i32 0
  %g473 = shufflevector <16 x i64> %g472, <16 x i64> poison, <16 x i32> zeroinitializer
  %g474 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g473
  %g475 = getelementptr inbounds float, ptr %g462, i64 16
  %g476 = load <16 x float>, ptr %acc2_1, align 64
  %g477 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g475, i32 4, <16 x i1> %g474, <16 x float> zeroinitializer)
  %g478 = fadd <16 x float> %g476, %g477
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g478, ptr %g475, i32 4, <16 x i1> %g474)
  %g479 = sub nsw i64 %jw, 32
  %g480 = insertelement <16 x i64> poison, i64 %g479, i32 0
  %g481 = shufflevector <16 x i64> %g480, <16 x i64> poison, <16 x i32> zeroinitializer
  %g482 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g481
  %g483 = getelementptr inbounds float, ptr %g462, i64 32
  %g484 = load <16 x float>, ptr %acc2_2, align 64
  %g485 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g483, i32 4, <16 x i1> %g482, <16 x float> zeroinitializer)
  %g486 = fadd <16 x float> %g484, %g485
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g486, ptr %g483, i32 4, <16 x i1> %g482)
  %g487 = sub nsw i64 %jw, 48
  %g488 = insertelement <16 x i64> poison, i64 %g487, i32 0
  %g489 = shufflevector <16 x i64> %g488, <16 x i64> poison, <16 x i32> zeroinitializer
  %g490 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g489
  %g491 = getelementptr inbounds float, ptr %g462, i64 48
  %g492 = load <16 x float>, ptr %acc2_3, align 64
  %g493 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g491, i32 4, <16 x i1> %g490, <16 x float> zeroinitializer)
  %g494 = fadd <16 x float> %g492, %g493
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g494, ptr %g491, i32 4, <16 x i1> %g490)
  br label %mk.sk.460
mk.sk.460:
  %g495 = icmp slt i64 3, %mw
  br i1 %g495, label %mk.st.496, label %mk.sk.497
mk.st.496:
  %g498 = mul nsw i64 3, %ldc
  %g499 = getelementptr inbounds float, ptr %c, i64 %g498
  %g500 = sub nsw i64 %jw, 0
  %g501 = insertelement <16 x i64> poison, i64 %g500, i32 0
  %g502 = shufflevector <16 x i64> %g501, <16 x i64> poison, <16 x i32> zeroinitializer
  %g503 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g502
  %g504 = getelementptr inbounds float, ptr %g499, i64 0
  %g505 = load <16 x float>, ptr %acc3_0, align 64
  %g506 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g504, i32 4, <16 x i1> %g503, <16 x float> zeroinitializer)
  %g507 = fadd <16 x float> %g505, %g506
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g507, ptr %g504, i32 4, <16 x i1> %g503)
  %g508 = sub nsw i64 %jw, 16
  %g509 = insertelement <16 x i64> poison, i64 %g508, i32 0
  %g510 = shufflevector <16 x i64> %g509, <16 x i64> poison, <16 x i32> zeroinitializer
  %g511 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g510
  %g512 = getelementptr inbounds float, ptr %g499, i64 16
  %g513 = load <16 x float>, ptr %acc3_1, align 64
  %g514 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g512, i32 4, <16 x i1> %g511, <16 x float> zeroinitializer)
  %g515 = fadd <16 x float> %g513, %g514
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g515, ptr %g512, i32 4, <16 x i1> %g511)
  %g516 = sub nsw i64 %jw, 32
  %g517 = insertelement <16 x i64> poison, i64 %g516, i32 0
  %g518 = shufflevector <16 x i64> %g517, <16 x i64> poison, <16 x i32> zeroinitializer
  %g519 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g518
  %g520 = getelementptr inbounds float, ptr %g499, i64 32
  %g521 = load <16 x float>, ptr %acc3_2, align 64
  %g522 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g520, i32 4, <16 x i1> %g519, <16 x float> zeroinitializer)
  %g523 = fadd <16 x float> %g521, %g522
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g523, ptr %g520, i32 4, <16 x i1> %g519)
  %g524 = sub nsw i64 %jw, 48
  %g525 = insertelement <16 x i64> poison, i64 %g524, i32 0
  %g526 = shufflevector <16 x i64> %g525, <16 x i64> poison, <16 x i32> zeroinitializer
  %g527 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g526
  %g528 = getelementptr inbounds float, ptr %g499, i64 48
  %g529 = load <16 x float>, ptr %acc3_3, align 64
  %g530 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g528, i32 4, <16 x i1> %g527, <16 x float> zeroinitializer)
  %g531 = fadd <16 x float> %g529, %g530
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g531, ptr %g528, i32 4, <16 x i1> %g527)
  br label %mk.sk.497
mk.sk.497:
  %g532 = icmp slt i64 4, %mw
  br i1 %g532, label %mk.st.533, label %mk.sk.534
mk.st.533:
  %g535 = mul nsw i64 4, %ldc
  %g536 = getelementptr inbounds float, ptr %c, i64 %g535
  %g537 = sub nsw i64 %jw, 0
  %g538 = insertelement <16 x i64> poison, i64 %g537, i32 0
  %g539 = shufflevector <16 x i64> %g538, <16 x i64> poison, <16 x i32> zeroinitializer
  %g540 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g539
  %g541 = getelementptr inbounds float, ptr %g536, i64 0
  %g542 = load <16 x float>, ptr %acc4_0, align 64
  %g543 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g541, i32 4, <16 x i1> %g540, <16 x float> zeroinitializer)
  %g544 = fadd <16 x float> %g542, %g543
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g544, ptr %g541, i32 4, <16 x i1> %g540)
  %g545 = sub nsw i64 %jw, 16
  %g546 = insertelement <16 x i64> poison, i64 %g545, i32 0
  %g547 = shufflevector <16 x i64> %g546, <16 x i64> poison, <16 x i32> zeroinitializer
  %g548 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g547
  %g549 = getelementptr inbounds float, ptr %g536, i64 16
  %g550 = load <16 x float>, ptr %acc4_1, align 64
  %g551 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g549, i32 4, <16 x i1> %g548, <16 x float> zeroinitializer)
  %g552 = fadd <16 x float> %g550, %g551
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g552, ptr %g549, i32 4, <16 x i1> %g548)
  %g553 = sub nsw i64 %jw, 32
  %g554 = insertelement <16 x i64> poison, i64 %g553, i32 0
  %g555 = shufflevector <16 x i64> %g554, <16 x i64> poison, <16 x i32> zeroinitializer
  %g556 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g555
  %g557 = getelementptr inbounds float, ptr %g536, i64 32
  %g558 = load <16 x float>, ptr %acc4_2, align 64
  %g559 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g557, i32 4, <16 x i1> %g556, <16 x float> zeroinitializer)
  %g560 = fadd <16 x float> %g558, %g559
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g560, ptr %g557, i32 4, <16 x i1> %g556)
  %g561 = sub nsw i64 %jw, 48
  %g562 = insertelement <16 x i64> poison, i64 %g561, i32 0
  %g563 = shufflevector <16 x i64> %g562, <16 x i64> poison, <16 x i32> zeroinitializer
  %g564 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g563
  %g565 = getelementptr inbounds float, ptr %g536, i64 48
  %g566 = load <16 x float>, ptr %acc4_3, align 64
  %g567 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g565, i32 4, <16 x i1> %g564, <16 x float> zeroinitializer)
  %g568 = fadd <16 x float> %g566, %g567
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g568, ptr %g565, i32 4, <16 x i1> %g564)
  br label %mk.sk.534
mk.sk.534:
  %g569 = icmp slt i64 5, %mw
  br i1 %g569, label %mk.st.570, label %mk.sk.571
mk.st.570:
  %g572 = mul nsw i64 5, %ldc
  %g573 = getelementptr inbounds float, ptr %c, i64 %g572
  %g574 = sub nsw i64 %jw, 0
  %g575 = insertelement <16 x i64> poison, i64 %g574, i32 0
  %g576 = shufflevector <16 x i64> %g575, <16 x i64> poison, <16 x i32> zeroinitializer
  %g577 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g576
  %g578 = getelementptr inbounds float, ptr %g573, i64 0
  %g579 = load <16 x float>, ptr %acc5_0, align 64
  %g580 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g578, i32 4, <16 x i1> %g577, <16 x float> zeroinitializer)
  %g581 = fadd <16 x float> %g579, %g580
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g581, ptr %g578, i32 4, <16 x i1> %g577)
  %g582 = sub nsw i64 %jw, 16
  %g583 = insertelement <16 x i64> poison, i64 %g582, i32 0
  %g584 = shufflevector <16 x i64> %g583, <16 x i64> poison, <16 x i32> zeroinitializer
  %g585 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g584
  %g586 = getelementptr inbounds float, ptr %g573, i64 16
  %g587 = load <16 x float>, ptr %acc5_1, align 64
  %g588 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g586, i32 4, <16 x i1> %g585, <16 x float> zeroinitializer)
  %g589 = fadd <16 x float> %g587, %g588
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g589, ptr %g586, i32 4, <16 x i1> %g585)
  %g590 = sub nsw i64 %jw, 32
  %g591 = insertelement <16 x i64> poison, i64 %g590, i32 0
  %g592 = shufflevector <16 x i64> %g591, <16 x i64> poison, <16 x i32> zeroinitializer
  %g593 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g592
  %g594 = getelementptr inbounds float, ptr %g573, i64 32
  %g595 = load <16 x float>, ptr %acc5_2, align 64
  %g596 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g594, i32 4, <16 x i1> %g593, <16 x float> zeroinitializer)
  %g597 = fadd <16 x float> %g595, %g596
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g597, ptr %g594, i32 4, <16 x i1> %g593)
  %g598 = sub nsw i64 %jw, 48
  %g599 = insertelement <16 x i64> poison, i64 %g598, i32 0
  %g600 = shufflevector <16 x i64> %g599, <16 x i64> poison, <16 x i32> zeroinitializer
  %g601 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g600
  %g602 = getelementptr inbounds float, ptr %g573, i64 48
  %g603 = load <16 x float>, ptr %acc5_3, align 64
  %g604 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g602, i32 4, <16 x i1> %g601, <16 x float> zeroinitializer)
  %g605 = fadd <16 x float> %g603, %g604
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g605, ptr %g602, i32 4, <16 x i1> %g601)
  br label %mk.sk.571
mk.sk.571:
  br label %mk.done.209
mk.done.209:
  ret void
}

define internal void @__y_gemm_small_m(ptr noalias %A, ptr noalias %B, ptr %C, i64 %M, i64 %N, i64 %K, i64 %m0, i64 %m1, i64 %n0, i64 %n1) #0 {
entry:
  %iv3 = alloca i64, align 8
  %iv15 = alloca i64, align 8
  %iv25 = alloca i64, align 8
  %iv118 = alloca i64, align 8
  %iv201 = alloca i64, align 8
  %g1 = sub nsw i64 %n1, %n0
  %g2 = shl i64 %g1, 2
  store i64 %m0, ptr %iv3
  br label %sm.z.cond.4
sm.z.cond.4:
  %g7 = load i64, ptr %iv3
  %g8 = icmp slt i64 %g7, %m1
  br i1 %g8, label %sm.z.body.5, label %sm.z.end.6
sm.z.body.5:
  %g9 = load i64, ptr %iv3
  %g10 = mul nsw i64 %g9, %N
  %g11 = add nsw i64 %g10, %n0
  %g12 = getelementptr inbounds float, ptr %C, i64 %g11
  call void @llvm.memset.p0.i64(ptr %g12, i8 0, i64 %g2, i1 false)
  %g13 = load i64, ptr %iv3
  %g14 = add i64 %g13, 1
  store i64 %g14, ptr %iv3
  br label %sm.z.cond.4
sm.z.end.6:
  store i64 %m0, ptr %iv15
  br label %sm.i.cond.16
sm.i.cond.16:
  %g19 = load i64, ptr %iv15
  %g20 = icmp slt i64 %g19, %m1
  br i1 %g20, label %sm.i.body.17, label %sm.i.end.18
sm.i.body.17:
  %g21 = load i64, ptr %iv15
  %g22 = sub nsw i64 %m1, %g21
  %g23 = icmp slt i64 %g22, 8
  %g24 = select i1 %g23, i64 %g22, i64 8
  store i64 0, ptr %iv25
  br label %sm.p.cond.26
sm.p.cond.26:
  %g29 = load i64, ptr %iv25
  %g30 = icmp slt i64 %g29, %K
  br i1 %g30, label %sm.p.body.27, label %sm.p.end.28
sm.p.body.27:
  %g31 = load i64, ptr %iv25
  %g32 = icmp slt i64 0, %g24
  %g33 = add nsw i64 %g21, 0
  %g34 = mul nsw i64 %g33, %K
  %g35 = add nsw i64 %g34, %g31
  %g36 = select i1 %g32, i64 %g35, i64 0
  %g37 = getelementptr inbounds float, ptr %A, i64 %g36
  %g38 = load float, ptr %g37, align 4
  %g39 = select i1 %g32, float %g38, float 0.0
  %g40 = insertelement <16 x float> poison, float %g39, i32 0
  %g41 = shufflevector <16 x float> %g40, <16 x float> poison, <16 x i32> zeroinitializer
  %g42 = icmp slt i64 1, %g24
  %g43 = add nsw i64 %g21, 1
  %g44 = mul nsw i64 %g43, %K
  %g45 = add nsw i64 %g44, %g31
  %g46 = select i1 %g42, i64 %g45, i64 0
  %g47 = getelementptr inbounds float, ptr %A, i64 %g46
  %g48 = load float, ptr %g47, align 4
  %g49 = select i1 %g42, float %g48, float 0.0
  %g50 = insertelement <16 x float> poison, float %g49, i32 0
  %g51 = shufflevector <16 x float> %g50, <16 x float> poison, <16 x i32> zeroinitializer
  %g52 = icmp slt i64 2, %g24
  %g53 = add nsw i64 %g21, 2
  %g54 = mul nsw i64 %g53, %K
  %g55 = add nsw i64 %g54, %g31
  %g56 = select i1 %g52, i64 %g55, i64 0
  %g57 = getelementptr inbounds float, ptr %A, i64 %g56
  %g58 = load float, ptr %g57, align 4
  %g59 = select i1 %g52, float %g58, float 0.0
  %g60 = insertelement <16 x float> poison, float %g59, i32 0
  %g61 = shufflevector <16 x float> %g60, <16 x float> poison, <16 x i32> zeroinitializer
  %g62 = icmp slt i64 3, %g24
  %g63 = add nsw i64 %g21, 3
  %g64 = mul nsw i64 %g63, %K
  %g65 = add nsw i64 %g64, %g31
  %g66 = select i1 %g62, i64 %g65, i64 0
  %g67 = getelementptr inbounds float, ptr %A, i64 %g66
  %g68 = load float, ptr %g67, align 4
  %g69 = select i1 %g62, float %g68, float 0.0
  %g70 = insertelement <16 x float> poison, float %g69, i32 0
  %g71 = shufflevector <16 x float> %g70, <16 x float> poison, <16 x i32> zeroinitializer
  %g72 = icmp slt i64 4, %g24
  %g73 = add nsw i64 %g21, 4
  %g74 = mul nsw i64 %g73, %K
  %g75 = add nsw i64 %g74, %g31
  %g76 = select i1 %g72, i64 %g75, i64 0
  %g77 = getelementptr inbounds float, ptr %A, i64 %g76
  %g78 = load float, ptr %g77, align 4
  %g79 = select i1 %g72, float %g78, float 0.0
  %g80 = insertelement <16 x float> poison, float %g79, i32 0
  %g81 = shufflevector <16 x float> %g80, <16 x float> poison, <16 x i32> zeroinitializer
  %g82 = icmp slt i64 5, %g24
  %g83 = add nsw i64 %g21, 5
  %g84 = mul nsw i64 %g83, %K
  %g85 = add nsw i64 %g84, %g31
  %g86 = select i1 %g82, i64 %g85, i64 0
  %g87 = getelementptr inbounds float, ptr %A, i64 %g86
  %g88 = load float, ptr %g87, align 4
  %g89 = select i1 %g82, float %g88, float 0.0
  %g90 = insertelement <16 x float> poison, float %g89, i32 0
  %g91 = shufflevector <16 x float> %g90, <16 x float> poison, <16 x i32> zeroinitializer
  %g92 = icmp slt i64 6, %g24
  %g93 = add nsw i64 %g21, 6
  %g94 = mul nsw i64 %g93, %K
  %g95 = add nsw i64 %g94, %g31
  %g96 = select i1 %g92, i64 %g95, i64 0
  %g97 = getelementptr inbounds float, ptr %A, i64 %g96
  %g98 = load float, ptr %g97, align 4
  %g99 = select i1 %g92, float %g98, float 0.0
  %g100 = insertelement <16 x float> poison, float %g99, i32 0
  %g101 = shufflevector <16 x float> %g100, <16 x float> poison, <16 x i32> zeroinitializer
  %g102 = icmp slt i64 7, %g24
  %g103 = add nsw i64 %g21, 7
  %g104 = mul nsw i64 %g103, %K
  %g105 = add nsw i64 %g104, %g31
  %g106 = select i1 %g102, i64 %g105, i64 0
  %g107 = getelementptr inbounds float, ptr %A, i64 %g106
  %g108 = load float, ptr %g107, align 4
  %g109 = select i1 %g102, float %g108, float 0.0
  %g110 = insertelement <16 x float> poison, float %g109, i32 0
  %g111 = shufflevector <16 x float> %g110, <16 x float> poison, <16 x i32> zeroinitializer
  %g112 = mul nsw i64 %g31, %N
  %g113 = getelementptr inbounds float, ptr %B, i64 %g112
  %g114 = mul nsw i64 %g21, %N
  %g115 = sub nsw i64 %n1, %n0
  %g116 = and i64 %g115, -16
  %g117 = add nsw i64 %n0, %g116
  store i64 %n0, ptr %iv118
  br label %sm.j.cond.119
sm.j.cond.119:
  %g122 = load i64, ptr %iv118
  %g123 = icmp slt i64 %g122, %g117
  br i1 %g123, label %sm.j.body.120, label %sm.j.end.121
sm.j.body.120:
  %g124 = load i64, ptr %iv118
  %g125 = getelementptr inbounds float, ptr %g113, i64 %g124
  %g126 = load <16 x float>, ptr %g125, align 4
  %g127 = icmp slt i64 0, %g24
  br i1 %g127, label %sm.do.128, label %sm.sk.129
sm.do.128:
  %g130 = mul nsw i64 0, %N
  %g131 = add nsw i64 %g114, %g130
  %g132 = add nsw i64 %g131, %g124
  %g133 = getelementptr inbounds float, ptr %C, i64 %g132
  %g134 = load <16 x float>, ptr %g133, align 4
  %g135 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g41, <16 x float> %g126, <16 x float> %g134)
  store <16 x float> %g135, ptr %g133, align 4
  br label %sm.sk.129
sm.sk.129:
  %g136 = icmp slt i64 1, %g24
  br i1 %g136, label %sm.do.137, label %sm.sk.138
sm.do.137:
  %g139 = mul nsw i64 1, %N
  %g140 = add nsw i64 %g114, %g139
  %g141 = add nsw i64 %g140, %g124
  %g142 = getelementptr inbounds float, ptr %C, i64 %g141
  %g143 = load <16 x float>, ptr %g142, align 4
  %g144 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g51, <16 x float> %g126, <16 x float> %g143)
  store <16 x float> %g144, ptr %g142, align 4
  br label %sm.sk.138
sm.sk.138:
  %g145 = icmp slt i64 2, %g24
  br i1 %g145, label %sm.do.146, label %sm.sk.147
sm.do.146:
  %g148 = mul nsw i64 2, %N
  %g149 = add nsw i64 %g114, %g148
  %g150 = add nsw i64 %g149, %g124
  %g151 = getelementptr inbounds float, ptr %C, i64 %g150
  %g152 = load <16 x float>, ptr %g151, align 4
  %g153 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g61, <16 x float> %g126, <16 x float> %g152)
  store <16 x float> %g153, ptr %g151, align 4
  br label %sm.sk.147
sm.sk.147:
  %g154 = icmp slt i64 3, %g24
  br i1 %g154, label %sm.do.155, label %sm.sk.156
sm.do.155:
  %g157 = mul nsw i64 3, %N
  %g158 = add nsw i64 %g114, %g157
  %g159 = add nsw i64 %g158, %g124
  %g160 = getelementptr inbounds float, ptr %C, i64 %g159
  %g161 = load <16 x float>, ptr %g160, align 4
  %g162 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g71, <16 x float> %g126, <16 x float> %g161)
  store <16 x float> %g162, ptr %g160, align 4
  br label %sm.sk.156
sm.sk.156:
  %g163 = icmp slt i64 4, %g24
  br i1 %g163, label %sm.do.164, label %sm.sk.165
sm.do.164:
  %g166 = mul nsw i64 4, %N
  %g167 = add nsw i64 %g114, %g166
  %g168 = add nsw i64 %g167, %g124
  %g169 = getelementptr inbounds float, ptr %C, i64 %g168
  %g170 = load <16 x float>, ptr %g169, align 4
  %g171 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g81, <16 x float> %g126, <16 x float> %g170)
  store <16 x float> %g171, ptr %g169, align 4
  br label %sm.sk.165
sm.sk.165:
  %g172 = icmp slt i64 5, %g24
  br i1 %g172, label %sm.do.173, label %sm.sk.174
sm.do.173:
  %g175 = mul nsw i64 5, %N
  %g176 = add nsw i64 %g114, %g175
  %g177 = add nsw i64 %g176, %g124
  %g178 = getelementptr inbounds float, ptr %C, i64 %g177
  %g179 = load <16 x float>, ptr %g178, align 4
  %g180 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g91, <16 x float> %g126, <16 x float> %g179)
  store <16 x float> %g180, ptr %g178, align 4
  br label %sm.sk.174
sm.sk.174:
  %g181 = icmp slt i64 6, %g24
  br i1 %g181, label %sm.do.182, label %sm.sk.183
sm.do.182:
  %g184 = mul nsw i64 6, %N
  %g185 = add nsw i64 %g114, %g184
  %g186 = add nsw i64 %g185, %g124
  %g187 = getelementptr inbounds float, ptr %C, i64 %g186
  %g188 = load <16 x float>, ptr %g187, align 4
  %g189 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g101, <16 x float> %g126, <16 x float> %g188)
  store <16 x float> %g189, ptr %g187, align 4
  br label %sm.sk.183
sm.sk.183:
  %g190 = icmp slt i64 7, %g24
  br i1 %g190, label %sm.do.191, label %sm.sk.192
sm.do.191:
  %g193 = mul nsw i64 7, %N
  %g194 = add nsw i64 %g114, %g193
  %g195 = add nsw i64 %g194, %g124
  %g196 = getelementptr inbounds float, ptr %C, i64 %g195
  %g197 = load <16 x float>, ptr %g196, align 4
  %g198 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g111, <16 x float> %g126, <16 x float> %g197)
  store <16 x float> %g198, ptr %g196, align 4
  br label %sm.sk.192
sm.sk.192:
  %g199 = load i64, ptr %iv118
  %g200 = add i64 %g199, 16
  store i64 %g200, ptr %iv118
  br label %sm.j.cond.119
sm.j.end.121:
  store i64 %g117, ptr %iv201
  br label %sm.t.cond.202
sm.t.cond.202:
  %g205 = load i64, ptr %iv201
  %g206 = icmp slt i64 %g205, %n1
  br i1 %g206, label %sm.t.body.203, label %sm.t.end.204
sm.t.body.203:
  %g207 = load i64, ptr %iv201
  %g208 = getelementptr inbounds float, ptr %g113, i64 %g207
  %g210 = sub nsw i64 %n1, %g207
  %g211 = insertelement <16 x i64> poison, i64 %g210, i32 0
  %g212 = shufflevector <16 x i64> %g211, <16 x i64> poison, <16 x i32> zeroinitializer
  %g213 = icmp slt <16 x i64> <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %g212
  %g209 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g208, i32 4, <16 x i1> %g213, <16 x float> zeroinitializer)
  %g214 = icmp slt i64 0, %g24
  br i1 %g214, label %sm.do.215, label %sm.sk.216
sm.do.215:
  %g217 = mul nsw i64 0, %N
  %g218 = add nsw i64 %g114, %g217
  %g219 = add nsw i64 %g218, %g207
  %g220 = getelementptr inbounds float, ptr %C, i64 %g219
  %g221 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g220, i32 4, <16 x i1> %g213, <16 x float> zeroinitializer)
  %g222 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g41, <16 x float> %g209, <16 x float> %g221)
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g222, ptr %g220, i32 4, <16 x i1> %g213)
  br label %sm.sk.216
sm.sk.216:
  %g223 = icmp slt i64 1, %g24
  br i1 %g223, label %sm.do.224, label %sm.sk.225
sm.do.224:
  %g226 = mul nsw i64 1, %N
  %g227 = add nsw i64 %g114, %g226
  %g228 = add nsw i64 %g227, %g207
  %g229 = getelementptr inbounds float, ptr %C, i64 %g228
  %g230 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g229, i32 4, <16 x i1> %g213, <16 x float> zeroinitializer)
  %g231 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g51, <16 x float> %g209, <16 x float> %g230)
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g231, ptr %g229, i32 4, <16 x i1> %g213)
  br label %sm.sk.225
sm.sk.225:
  %g232 = icmp slt i64 2, %g24
  br i1 %g232, label %sm.do.233, label %sm.sk.234
sm.do.233:
  %g235 = mul nsw i64 2, %N
  %g236 = add nsw i64 %g114, %g235
  %g237 = add nsw i64 %g236, %g207
  %g238 = getelementptr inbounds float, ptr %C, i64 %g237
  %g239 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g238, i32 4, <16 x i1> %g213, <16 x float> zeroinitializer)
  %g240 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g61, <16 x float> %g209, <16 x float> %g239)
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g240, ptr %g238, i32 4, <16 x i1> %g213)
  br label %sm.sk.234
sm.sk.234:
  %g241 = icmp slt i64 3, %g24
  br i1 %g241, label %sm.do.242, label %sm.sk.243
sm.do.242:
  %g244 = mul nsw i64 3, %N
  %g245 = add nsw i64 %g114, %g244
  %g246 = add nsw i64 %g245, %g207
  %g247 = getelementptr inbounds float, ptr %C, i64 %g246
  %g248 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g247, i32 4, <16 x i1> %g213, <16 x float> zeroinitializer)
  %g249 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g71, <16 x float> %g209, <16 x float> %g248)
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g249, ptr %g247, i32 4, <16 x i1> %g213)
  br label %sm.sk.243
sm.sk.243:
  %g250 = icmp slt i64 4, %g24
  br i1 %g250, label %sm.do.251, label %sm.sk.252
sm.do.251:
  %g253 = mul nsw i64 4, %N
  %g254 = add nsw i64 %g114, %g253
  %g255 = add nsw i64 %g254, %g207
  %g256 = getelementptr inbounds float, ptr %C, i64 %g255
  %g257 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g256, i32 4, <16 x i1> %g213, <16 x float> zeroinitializer)
  %g258 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g81, <16 x float> %g209, <16 x float> %g257)
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g258, ptr %g256, i32 4, <16 x i1> %g213)
  br label %sm.sk.252
sm.sk.252:
  %g259 = icmp slt i64 5, %g24
  br i1 %g259, label %sm.do.260, label %sm.sk.261
sm.do.260:
  %g262 = mul nsw i64 5, %N
  %g263 = add nsw i64 %g114, %g262
  %g264 = add nsw i64 %g263, %g207
  %g265 = getelementptr inbounds float, ptr %C, i64 %g264
  %g266 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g265, i32 4, <16 x i1> %g213, <16 x float> zeroinitializer)
  %g267 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g91, <16 x float> %g209, <16 x float> %g266)
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g267, ptr %g265, i32 4, <16 x i1> %g213)
  br label %sm.sk.261
sm.sk.261:
  %g268 = icmp slt i64 6, %g24
  br i1 %g268, label %sm.do.269, label %sm.sk.270
sm.do.269:
  %g271 = mul nsw i64 6, %N
  %g272 = add nsw i64 %g114, %g271
  %g273 = add nsw i64 %g272, %g207
  %g274 = getelementptr inbounds float, ptr %C, i64 %g273
  %g275 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g274, i32 4, <16 x i1> %g213, <16 x float> zeroinitializer)
  %g276 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g101, <16 x float> %g209, <16 x float> %g275)
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g276, ptr %g274, i32 4, <16 x i1> %g213)
  br label %sm.sk.270
sm.sk.270:
  %g277 = icmp slt i64 7, %g24
  br i1 %g277, label %sm.do.278, label %sm.sk.279
sm.do.278:
  %g280 = mul nsw i64 7, %N
  %g281 = add nsw i64 %g114, %g280
  %g282 = add nsw i64 %g281, %g207
  %g283 = getelementptr inbounds float, ptr %C, i64 %g282
  %g284 = call <16 x float> @llvm.masked.load.v16f32.p0(ptr %g283, i32 4, <16 x i1> %g213, <16 x float> zeroinitializer)
  %g285 = call <16 x float> @llvm.fmuladd.v16f32(<16 x float> %g111, <16 x float> %g209, <16 x float> %g284)
  call void @llvm.masked.store.v16f32.p0(<16 x float> %g285, ptr %g283, i32 4, <16 x i1> %g213)
  br label %sm.sk.279
sm.sk.279:
  %g286 = load i64, ptr %iv201
  %g287 = add i64 %g286, 16
  store i64 %g287, ptr %iv201
  br label %sm.t.cond.202
sm.t.end.204:
  %g288 = load i64, ptr %iv25
  %g289 = add i64 %g288, 1
  store i64 %g289, ptr %iv25
  br label %sm.p.cond.26
sm.p.end.28:
  %g290 = load i64, ptr %iv15
  %g291 = add i64 %g290, 8
  store i64 %g291, ptr %iv15
  br label %sm.i.cond.16
sm.i.end.18:
  ret void
}

define internal void @__y_gemm_run(ptr noalias %A, ptr noalias %B, ptr %C, i64 %M, i64 %N, i64 %K, i64 %m0, i64 %m1, i64 %n0, i64 %n1, ptr noalias %scratch, i64 %tid, i64 %nthr, i64 %shared) #0 {
entry:
  %iv12 = alloca i64, align 8
  %iv28 = alloca i64, align 8
  %iv46 = alloca i64, align 8
  %iv59 = alloca i64, align 8
  %iv71 = alloca i64, align 8
  %g1 = icmp sge i64 %m0, %m1
  %g2 = icmp sge i64 %n0, %n1
  %g3 = or i1 %g1, %g2
  br i1 %g3, label %g.empty.4, label %g.go.5
g.empty.4:
  ret void
g.go.5:
  %g6 = getelementptr inbounds float, ptr %scratch, i64 409600
  %g7 = icmp ne i64 %shared, 0
  %g8 = select i1 %g7, ptr @__y_shared_b, ptr %g6
  %g9 = icmp sle i64 %M, 8
  br i1 %g9, label %g.small.10, label %g.big.11
g.small.10:
  call void @__y_gemm_small_m(ptr %A, ptr %B, ptr %C, i64 %M, i64 %N, i64 %K, i64 %m0, i64 %m1, i64 %n0, i64 %n1)
  ret void
g.big.11:
  store i64 %n0, ptr %iv12
  br label %g.jc.cond.13
g.jc.cond.13:
  %g16 = load i64, ptr %iv12
  %g17 = icmp slt i64 %g16, %n1
  br i1 %g17, label %g.jc.body.14, label %g.jc.end.15
g.jc.body.14:
  %g18 = load i64, ptr %iv12
  %g19 = sub nsw i64 %n1, %g18
  %g20 = icmp slt i64 %g19, 2048
  %g21 = select i1 %g20, i64 %g19, i64 2048
  %g22 = mul nsw i64 %nthr, %g21
  %g23 = udiv i64 8388608, %g22
  %g24 = icmp slt i64 %g23, 1024
  %g25 = select i1 %g24, i64 %g23, i64 1024
  %g26 = icmp sgt i64 %g25, 64
  %g27 = select i1 %g26, i64 %g25, i64 64
  store i64 0, ptr %iv28
  br label %g.pc.cond.29
g.pc.cond.29:
  %g32 = load i64, ptr %iv28
  %g33 = icmp slt i64 %g32, %K
  br i1 %g33, label %g.pc.body.30, label %g.pc.end.31
g.pc.body.30:
  %g34 = load i64, ptr %iv28
  %g35 = sub nsw i64 %K, %g34
  %g36 = icmp slt i64 %g35, %g27
  %g37 = select i1 %g36, i64 %g35, i64 %g27
  %g38 = mul nsw i64 %g34, %N
  %g39 = add nsw i64 %g38, %g18
  %g40 = getelementptr inbounds float, ptr %B, i64 %g39
  %g41 = select i1 %g7, i64 %tid, i64 0
  %g42 = select i1 %g7, i64 %nthr, i64 1
  call void @__y_gemm_pack_b(ptr %g40, i64 %N, i64 %g37, i64 %g21, ptr %g8, i64 %g41, i64 %g42)
  br i1 %g7, label %g.bar1.43, label %g.after1.44
g.bar1.43:
  call i32 @pthread_barrier_wait(ptr @__y_pool_barrier)
  br label %g.after1.44
g.after1.44:
  %g45 = icmp eq i64 %g34, 0
  store i64 %m0, ptr %iv46
  br label %g.ic.cond.47
g.ic.cond.47:
  %g50 = load i64, ptr %iv46
  %g51 = icmp slt i64 %g50, %m1
  br i1 %g51, label %g.ic.body.48, label %g.ic.end.49
g.ic.body.48:
  %g52 = load i64, ptr %iv46
  %g53 = sub nsw i64 %m1, %g52
  %g54 = icmp slt i64 %g53, 192
  %g55 = select i1 %g54, i64 %g53, i64 192
  %g56 = mul nsw i64 %g52, %K
  %g57 = add nsw i64 %g56, %g34
  %g58 = getelementptr inbounds float, ptr %A, i64 %g57
  call void @__y_gemm_pack_a(ptr %g58, i64 %K, i64 %g55, i64 %g37, ptr %scratch)
  store i64 0, ptr %iv59
  br label %g.jr.cond.60
g.jr.cond.60:
  %g63 = load i64, ptr %iv59
  %g64 = icmp slt i64 %g63, %g21
  br i1 %g64, label %g.jr.body.61, label %g.jr.end.62
g.jr.body.61:
  %g65 = load i64, ptr %iv59
  %g66 = sub nsw i64 %g21, %g65
  %g67 = icmp slt i64 %g66, 64
  %g68 = select i1 %g67, i64 %g66, i64 64
  %g69 = mul nsw i64 %g65, %g37
  %g70 = getelementptr inbounds float, ptr %g8, i64 %g69
  store i64 0, ptr %iv71
  br label %g.ir.cond.72
g.ir.cond.72:
  %g75 = load i64, ptr %iv71
  %g76 = icmp slt i64 %g75, %g55
  br i1 %g76, label %g.ir.body.73, label %g.ir.end.74
g.ir.body.73:
  %g77 = load i64, ptr %iv71
  %g78 = sub nsw i64 %g55, %g77
  %g79 = icmp slt i64 %g78, 6
  %g80 = select i1 %g79, i64 %g78, i64 6
  %g81 = mul nsw i64 %g77, %g37
  %g82 = getelementptr inbounds float, ptr %scratch, i64 %g81
  %g83 = add nsw i64 %g52, %g77
  %g84 = mul nsw i64 %g83, %N
  %g85 = add nsw i64 %g84, %g18
  %g86 = add nsw i64 %g85, %g65
  %g87 = getelementptr inbounds float, ptr %C, i64 %g86
  call void @__y_gemm_micro(ptr %g82, ptr %g70, i64 64, ptr %g87, i64 %N, i64 %g37, i64 %g80, i64 %g68, i1 %g45)
  %g88 = load i64, ptr %iv71
  %g89 = add i64 %g88, 6
  store i64 %g89, ptr %iv71
  br label %g.ir.cond.72
g.ir.end.74:
  %g90 = load i64, ptr %iv59
  %g91 = add i64 %g90, 64
  store i64 %g91, ptr %iv59
  br label %g.jr.cond.60
g.jr.end.62:
  %g92 = load i64, ptr %iv46
  %g93 = add i64 %g92, 192
  store i64 %g93, ptr %iv46
  br label %g.ic.cond.47
g.ic.end.49:
  br i1 %g7, label %g.bar2.94, label %g.after2.95
g.bar2.94:
  call i32 @pthread_barrier_wait(ptr @__y_pool_barrier)
  br label %g.after2.95
g.after2.95:
  %g96 = load i64, ptr %iv28
  %g97 = add i64 %g96, %g27
  store i64 %g97, ptr %iv28
  br label %g.pc.cond.29
g.pc.end.31:
  %g98 = load i64, ptr %iv12
  %g99 = add i64 %g98, 2048
  store i64 %g99, ptr %iv12
  br label %g.jc.cond.13
g.jc.end.15:
  ret void
}

define internal ptr @__y_gemm_worker(ptr %t) #0 {
entry:
  %g1 = getelementptr inbounds %y_gemm_task, ptr %t, i64 0, i32 0
  %g2 = load ptr, ptr %g1, align 8
  %g3 = getelementptr inbounds %y_gemm_task, ptr %t, i64 0, i32 1
  %g4 = load ptr, ptr %g3, align 8
  %g5 = getelementptr inbounds %y_gemm_task, ptr %t, i64 0, i32 2
  %g6 = load ptr, ptr %g5, align 8
  %g7 = getelementptr inbounds %y_gemm_task, ptr %t, i64 0, i32 3
  %g8 = load i64, ptr %g7, align 8
  %g9 = getelementptr inbounds %y_gemm_task, ptr %t, i64 0, i32 4
  %g10 = load i64, ptr %g9, align 8
  %g11 = getelementptr inbounds %y_gemm_task, ptr %t, i64 0, i32 5
  %g12 = load i64, ptr %g11, align 8
  %g13 = getelementptr inbounds %y_gemm_task, ptr %t, i64 0, i32 6
  %g14 = load i64, ptr %g13, align 8
  %g15 = getelementptr inbounds %y_gemm_task, ptr %t, i64 0, i32 7
  %g16 = load i64, ptr %g15, align 8
  %g17 = getelementptr inbounds %y_gemm_task, ptr %t, i64 0, i32 8
  %g18 = load i64, ptr %g17, align 8
  %g19 = getelementptr inbounds %y_gemm_task, ptr %t, i64 0, i32 9
  %g20 = load i64, ptr %g19, align 8
  %g21 = getelementptr inbounds %y_gemm_task, ptr %t, i64 0, i32 10
  %g22 = load ptr, ptr %g21, align 8
  %g23 = getelementptr inbounds %y_gemm_task, ptr %t, i64 0, i32 11
  %g24 = load i64, ptr %g23, align 8
  %g25 = getelementptr inbounds %y_gemm_task, ptr %t, i64 0, i32 12
  %g26 = load i64, ptr %g25, align 8
  %g27 = getelementptr inbounds %y_gemm_task, ptr %t, i64 0, i32 13
  %g28 = load i64, ptr %g27, align 8
  call void @__y_gemm_run(ptr %g2, ptr %g4, ptr %g6, i64 %g8, i64 %g10, i64 %g12, i64 %g14, i64 %g16, i64 %g18, i64 %g20, ptr %g22, i64 %g24, i64 %g26, i64 %g28)
  ret ptr null
}

define internal i64 @__y_gemm_threads(i64 %M, i64 %N, i64 %K) #0 {
entry:
  %g1 = load i64, ptr @__y_gemm_nthreads, align 8
  %g2 = icmp eq i64 %g1, 0
  br i1 %g2, label %nt.resolve.3, label %nt.have.4
nt.resolve.3:
  %g5 = call ptr @getenv(ptr @.y_gemm_env)
  %g6 = icmp ne ptr %g5, null
  br i1 %g6, label %nt.env.7, label %nt.sys.8
nt.env.7:
  %g10 = call i32 @atoi(ptr %g5)
  %g11 = sext i32 %g10 to i64
  br label %nt.set.9
nt.sys.8:
  %g12 = call i64 @sysconf(i32 84)
  br label %nt.set.9
nt.set.9:
  %g13 = phi i64 [ %g11, %nt.env.7 ], [ %g12, %nt.sys.8 ]
  %g14 = icmp sgt i64 %g13, 1
  %g15 = select i1 %g14, i64 %g13, i64 1
  %g16 = icmp slt i64 %g15, 16
  %g17 = select i1 %g16, i64 %g15, i64 16
  store i64 %g17, ptr @__y_gemm_nthreads, align 8
  br label %nt.have.4
nt.have.4:
  %g18 = load i64, ptr @__y_gemm_nthreads, align 8
  %g19 = mul nsw i64 %M, %N
  %g20 = mul nsw i64 %g19, %K
  %g21 = icmp sgt i64 %g20, 4194304
  br i1 %g21, label %nt.scale.22, label %nt.one.23
nt.scale.22:
  %g25 = sdiv i64 %g20, 4194304
  %g26 = icmp slt i64 %g25, %g18
  %g27 = select i1 %g26, i64 %g25, i64 %g18
  %g28 = icmp sgt i64 %g27, 1
  %g29 = select i1 %g28, i64 %g27, i64 1
  br label %nt.out.24
nt.one.23:
  br label %nt.out.24
nt.out.24:
  %g30 = phi i64 [ %g29, %nt.scale.22 ], [ 1, %nt.one.23 ]
  ret i64 %g30
}

define internal ptr @__y_pool_worker(ptr %idxp) #0 {
entry:
  %.last = alloca i64, align 8
  %.spin = alloca i64, align 8
  %.gen = alloca i64, align 8
  %g1 = load i64, ptr %idxp, align 8
  %g2 = getelementptr inbounds [16 x i64], ptr @__y_pool_done, i64 0, i64 %g1
  %g3 = getelementptr inbounds [16 x %y_gemm_task], ptr @__y_pool_task, i64 0, i64 %g1
  store i64 0, ptr %.last, align 8
  br label %w.outer.4
w.outer.4:
  store i64 0, ptr %.spin, align 8
  br label %w.wait.5
w.wait.5:
  %g8 = load atomic i64, ptr @__y_pool_gen acquire, align 8
  %g9 = load i64, ptr %.last, align 8
  %g10 = icmp ne i64 %g8, %g9
  store i64 %g8, ptr %.gen, align 8
  br i1 %g10, label %w.work.6, label %w.park.7
w.park.7:
  %g11 = load i64, ptr %.spin, align 8
  %g12 = add nsw i64 %g11, 1
  store i64 %g12, ptr %.spin, align 8
  %g13 = icmp slt i64 %g12, 512
  br i1 %g13, label %w.spin.14, label %w.block.15
w.spin.14:
  call void @llvm.x86.sse2.pause()
  br label %w.wait.5
w.block.15:
  call i32 @pthread_mutex_lock(ptr @__y_pool_mutex)
  br label %w.recheck.16
w.recheck.16:
  %g17 = load atomic i64, ptr @__y_pool_gen acquire, align 8
  %g18 = load i64, ptr %.last, align 8
  %g19 = icmp ne i64 %g17, %g18
  br i1 %g19, label %w.wake.20, label %w.sleep.21
w.sleep.21:
  call i32 @pthread_cond_wait(ptr @__y_pool_cond, ptr @__y_pool_mutex)
  br label %w.recheck.16
w.wake.20:
  call i32 @pthread_mutex_unlock(ptr @__y_pool_mutex)
  store i64 %g17, ptr %.gen, align 8
  br label %w.work.6
w.work.6:
  %g22 = load i64, ptr %.gen, align 8
  store i64 %g22, ptr %.last, align 8
  call void @__y_gemm_worker(ptr %g3)
  store atomic i64 %g22, ptr %g2 release, align 8
  br label %w.outer.4
}

define internal void @__y_sgemm_f32_avx512(ptr noalias %A, ptr noalias %B, ptr noalias %C, i64 %M, i64 %N, i64 %K) #0 {
entry:
  %.tid = alloca i64, align 8
  %iv18 = alloca i64, align 8
  %iv57 = alloca i64, align 8
  %iv105 = alloca i64, align 8
  %g1 = call i64 @__y_gemm_threads(i64 %M, i64 %N, i64 %K)
  %g2 = icmp sle i64 %g1, 1
  br i1 %g2, label %e.solo.3, label %e.par.4
e.solo.3:
  %g5 = load ptr, ptr @__y_gemm_scratch, align 8
  %g6 = icmp ne ptr %g5, null
  %g7 = select i1 %g6, ptr %g5, ptr @__y_gemm_fallback
  call void @__y_gemm_run(ptr %A, ptr %B, ptr %C, i64 %M, i64 %N, i64 %K, i64 0, i64 %M, i64 0, i64 %N, ptr %g7, i64 0, i64 1, i64 0)
  ret void
e.par.4:
  %g8 = load i64, ptr @__y_pool_n, align 8
  %g9 = icmp eq i64 %g8, 0
  br i1 %g9, label %e.start.10, label %e.hot.11
e.start.10:
  %g12 = load i64, ptr @__y_gemm_nthreads, align 8
  %g13 = mul nsw i64 %g12, 10289152
  %g14 = call ptr @malloc(i64 %g13)
  store ptr %g14, ptr @__y_gemm_scratch, align 8
  %g15 = icmp ne ptr %g14, null
  br i1 %g15, label %e.spawn0.17, label %e.oom.16
e.oom.16:
  call void @__y_gemm_run(ptr %A, ptr %B, ptr %C, i64 %M, i64 %N, i64 %K, i64 0, i64 %M, i64 0, i64 %N, ptr @__y_gemm_fallback, i64 0, i64 1, i64 0)
  ret void
e.spawn0.17:
  call i32 @pthread_mutex_init(ptr @__y_pool_mutex, ptr null)
  call i32 @pthread_cond_init(ptr @__y_pool_cond, ptr null)
  store i64 1, ptr %iv18
  br label %e.spawn.cond.19
e.spawn.cond.19:
  %g22 = load i64, ptr %iv18
  %g23 = icmp slt i64 %g22, %g12
  br i1 %g23, label %e.spawn.body.20, label %e.spawn.end.21
e.spawn.body.20:
  %g24 = load i64, ptr %iv18
  %g25 = getelementptr inbounds [16 x i64], ptr @__y_pool_ids, i64 0, i64 %g24
  store i64 %g24, ptr %g25, align 8
  call i32 @pthread_create(ptr %.tid, ptr null, ptr @__y_pool_worker, ptr %g25)
  %g26 = load i64, ptr %iv18
  %g27 = add i64 %g26, 1
  store i64 %g27, ptr %iv18
  br label %e.spawn.cond.19
e.spawn.end.21:
  store i64 %g12, ptr @__y_pool_n, align 8
  br label %e.hot.11
e.hot.11:
  %g28 = load i64, ptr @__y_pool_n, align 8
  %g29 = load ptr, ptr @__y_gemm_scratch, align 8
  %g30 = sdiv i64 %M, 6
  %g31 = icmp sgt i64 %g30, 1
  %g32 = select i1 %g31, i64 %g30, i64 1
  %g33 = sdiv i64 %N, 64
  %g34 = icmp sgt i64 %g33, 1
  %g35 = select i1 %g34, i64 %g33, i64 1
  %g36 = icmp sge i64 %g32, %g35
  %g37 = icmp sgt i64 %g32, %g35
  %g38 = select i1 %g37, i64 %g32, i64 %g35
  %g39 = icmp slt i64 %g1, %g38
  %g40 = select i1 %g39, i64 %g1, i64 %g38
  %g41 = select i1 %g36, i64 %M, i64 %N
  %g42 = select i1 %g36, i64 6, i64 64
  %g43 = mul nsw i64 %M, %N
  %g44 = mul nsw i64 %g43, %K
  %g45 = icmp sge i64 %g44, 2147483648
  %g46 = and i1 %g36, %g45
  %g47 = zext i1 %g46 to i64
  %g50 = load i64, ptr @__y_barrier_n, align 8
  %g51 = icmp ne i64 %g50, %g40
  %g52 = and i1 %g51, %g46
  br i1 %g52, label %e.bar.48, label %e.barok.49
e.bar.48:
  %g53 = icmp ne i64 %g50, 0
  br i1 %g53, label %e.bardestroy.54, label %e.barinit.55
e.bardestroy.54:
  call i32 @pthread_barrier_destroy(ptr @__y_pool_barrier)
  br label %e.barinit.55
e.barinit.55:
  %g56 = trunc i64 %g40 to i32
  call i32 @pthread_barrier_init(ptr @__y_pool_barrier, ptr null, i32 %g56)
  store i64 %g40, ptr @__y_barrier_n, align 8
  br label %e.barok.49
e.barok.49:
  store i64 0, ptr %iv57
  br label %e.fill.cond.58
e.fill.cond.58:
  %g61 = load i64, ptr %iv57
  %g62 = icmp slt i64 %g61, %g28
  br i1 %g62, label %e.fill.body.59, label %e.fill.end.60
e.fill.body.59:
  %g63 = load i64, ptr %iv57
  %g64 = mul nsw i64 %g63, %g41
  %g65 = sdiv i64 %g64, %g40
  %g66 = sdiv i64 %g65, %g42
  %g67 = mul nsw i64 %g66, %g42
  %g68 = add nsw i64 %g63, 1
  %g69 = mul nsw i64 %g68, %g41
  %g70 = sdiv i64 %g69, %g40
  %g71 = sdiv i64 %g70, %g42
  %g72 = mul nsw i64 %g71, %g42
  %g73 = icmp eq i64 %g68, %g40
  %g74 = select i1 %g73, i64 %g41, i64 %g72
  %g75 = icmp slt i64 %g63, %g40
  %g76 = select i1 %g75, i64 %g74, i64 %g67
  %g77 = getelementptr inbounds [16 x %y_gemm_task], ptr @__y_pool_task, i64 0, i64 %g63
  %g78 = select i1 %g36, i64 %g67, i64 0
  %g79 = select i1 %g36, i64 %g76, i64 %M
  %g80 = select i1 %g36, i64 0, i64 %g67
  %g81 = select i1 %g36, i64 %N, i64 %g76
  %g82 = select i1 %g75, i64 %g79, i64 %g78
  %g83 = select i1 %g75, i64 %g81, i64 %g80
  %g84 = mul nsw i64 %g63, 2572288
  %g85 = getelementptr inbounds float, ptr %g29, i64 %g84
  %g86 = getelementptr inbounds %y_gemm_task, ptr %g77, i64 0, i32 0
  store ptr %A, ptr %g86, align 8
  %g87 = getelementptr inbounds %y_gemm_task, ptr %g77, i64 0, i32 1
  store ptr %B, ptr %g87, align 8
  %g88 = getelementptr inbounds %y_gemm_task, ptr %g77, i64 0, i32 2
  store ptr %C, ptr %g88, align 8
  %g89 = getelementptr inbounds %y_gemm_task, ptr %g77, i64 0, i32 3
  store i64 %M, ptr %g89, align 8
  %g90 = getelementptr inbounds %y_gemm_task, ptr %g77, i64 0, i32 4
  store i64 %N, ptr %g90, align 8
  %g91 = getelementptr inbounds %y_gemm_task, ptr %g77, i64 0, i32 5
  store i64 %K, ptr %g91, align 8
  %g92 = getelementptr inbounds %y_gemm_task, ptr %g77, i64 0, i32 6
  store i64 %g78, ptr %g92, align 8
  %g93 = getelementptr inbounds %y_gemm_task, ptr %g77, i64 0, i32 7
  store i64 %g82, ptr %g93, align 8
  %g94 = getelementptr inbounds %y_gemm_task, ptr %g77, i64 0, i32 8
  store i64 %g80, ptr %g94, align 8
  %g95 = getelementptr inbounds %y_gemm_task, ptr %g77, i64 0, i32 9
  store i64 %g83, ptr %g95, align 8
  %g96 = getelementptr inbounds %y_gemm_task, ptr %g77, i64 0, i32 10
  store ptr %g85, ptr %g96, align 8
  %g97 = getelementptr inbounds %y_gemm_task, ptr %g77, i64 0, i32 11
  store i64 %g63, ptr %g97, align 8
  %g98 = getelementptr inbounds %y_gemm_task, ptr %g77, i64 0, i32 12
  store i64 %g40, ptr %g98, align 8
  %g99 = getelementptr inbounds %y_gemm_task, ptr %g77, i64 0, i32 13
  store i64 %g47, ptr %g99, align 8
  %g100 = load i64, ptr %iv57
  %g101 = add i64 %g100, 1
  store i64 %g101, ptr %iv57
  br label %e.fill.cond.58
e.fill.end.60:
  %g102 = load i64, ptr @__y_pool_gen, align 8
  %g103 = add nsw i64 %g102, 1
  call i32 @pthread_mutex_lock(ptr @__y_pool_mutex)
  store atomic i64 %g103, ptr @__y_pool_gen release, align 8
  call i32 @pthread_cond_broadcast(ptr @__y_pool_cond)
  call i32 @pthread_mutex_unlock(ptr @__y_pool_mutex)
  %g104 = getelementptr inbounds [16 x %y_gemm_task], ptr @__y_pool_task, i64 0, i64 0
  call void @__y_gemm_worker(ptr %g104)
  store i64 1, ptr %iv105
  br label %e.join.cond.106
e.join.cond.106:
  %g109 = load i64, ptr %iv105
  %g110 = icmp slt i64 %g109, %g28
  br i1 %g110, label %e.join.body.107, label %e.join.end.108
e.join.body.107:
  %g111 = load i64, ptr %iv105
  %g112 = getelementptr inbounds [16 x i64], ptr @__y_pool_done, i64 0, i64 %g111
  br label %e.spinwait.113
e.spinwait.113:
  %g115 = load atomic i64, ptr %g112 acquire, align 8
  %g116 = icmp eq i64 %g115, %g103
  br i1 %g116, label %e.done.114, label %e.again.117
e.again.117:
  call void @llvm.x86.sse2.pause()
  br label %e.spinwait.113
e.done.114:
  %g118 = load i64, ptr %iv105
  %g119 = add i64 %g118, 1
  store i64 %g119, ptr %iv105
  br label %e.join.cond.106
e.join.end.108:
  ret void
}
!0 = !{i32 1}
