//! A radix-2 NTT over BN254 Fr, on the GPU, written in Y.
//!
//! `tests/bn254_ntt_stage.ysu` is one Cooley-Tukey stage: one butterfly per
//! thread, with the Montgomery multiply, the modular add and the modular
//! subtract all inlined and register-resident. The host launches it once per
//! stage. It is generated by `tools/gen_bn254_kernels.py` for the reason given
//! there - the backend has no local arrays, so an eight-limb value is eight
//! named scalars and every limb index has to be a literal.
//!
//! **The oracle is a naive O(N^2) DFT**, not another NTT. Checking a fast
//! transform against a fast transform shares the bug: a wrong twiddle order,
//! a missing bit-reversal or an off-by-one in the stage schedule appears in
//! both and cancels. The direct sum has no structure to get wrong, which is
//! the whole reason it is worth its 1M field multiplies here.

use std::path::{Path, PathBuf};
use std::process::Command;

use y::cuda_runtime::{CudaContext, DeviceBuffer, KernelModule};
use y::zk_field::Fr;

fn bin() -> PathBuf {
    let mut p = std::env::current_exe().unwrap();
    p.pop();
    if p.ends_with("deps") {
        p.pop();
    }
    p.join("Y")
}

fn repo() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

fn load_kernel(ctx: &CudaContext, entry: &str) -> KernelModule {
    let out = Command::new(bin())
        .arg(repo().join(format!("tests/{}.ysu", entry)))
        .arg("--emit-ptx")
        .current_dir(repo())
        .output()
        .expect("failed to run the Y binary");
    assert!(
        out.status.success(),
        "{}.ysu did not compile:\n{}{}",
        entry,
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    let ptx = std::fs::read_to_string(repo().join(format!("tests/{}.ptx", entry))).unwrap();
    assert!(
        !ptx.contains("ld.global.f32") && !ptx.contains("add.f32"),
        "{} is routing field limbs through the float datapath",
        entry
    );
    ctx.load_ptx(&ptx, entry)
        .unwrap_or_else(|e| panic!("{} did not load: {}", entry, e))
}

fn limbs32(x: &Fr) -> [u32; 8] {
    let l = x.to_limbs();
    let mut o = [0u32; 8];
    for i in 0..4 {
        o[2 * i] = l[i] as u32;
        o[2 * i + 1] = (l[i] >> 32) as u32;
    }
    o
}

fn as_bytes(v: &[u32]) -> &[u8] {
    unsafe { std::slice::from_raw_parts(v.as_ptr() as *const u8, v.len() * 4) }
}

fn read_u32(ctx: &CudaContext, buf: &DeviceBuffer, n: usize) -> Vec<u32> {
    let mut raw = vec![0u8; n * 4];
    ctx.memcpy_dtoh_at(&mut raw, buf, 0).unwrap();
    raw.chunks_exact(4)
        .map(|c| u32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

/// `R mod p`, via the public API only (`Fr`'s Montgomery limbs are private).
/// The kernel's multiply returns `a * b * R^-1`, so a twiddle goes in as
/// `w * R` and the butterfly's product comes out canonical.
fn r_mod_p() -> Fr {
    let mut r = Fr::from_u64(1);
    for _ in 0..256 {
        r = r.add(&r);
    }
    r
}

/// A primitive `2^k`-th root of unity in BN254 Fr.
///
/// `Fr*` has order `p - 1`, whose 2-adic valuation is 28, so roots exist for
/// every `k <= 28`. `5` is a generator; `5^((p-1)/2^k)` therefore has order
/// exactly `2^k`, which the caller checks rather than assumes.
fn root_of_unity(k: u32) -> Fr {
    assert!(k <= 28, "BN254 Fr has 2-adicity 28");
    // (p - 1) / 2^k, as four little-endian u64 limbs.
    let p_minus_1 = Fr::zero().sub(&Fr::one()).to_limbs();
    let mut e = p_minus_1;
    for _ in 0..k {
        // shift right by one across the four limbs
        for i in 0..3 {
            e[i] = (e[i] >> 1) | (e[i + 1] << 63);
        }
        e[3] >>= 1;
    }
    let w = Fr::from_u64(5).pow_limbs(&e);

    // Order exactly 2^k: w^(2^k) == 1 and w^(2^(k-1)) != 1.
    let mut t = w;
    for _ in 0..k.saturating_sub(1) {
        t = t.square();
    }
    assert_ne!(t.to_decimal_string(), "1", "root has order below 2^{}", k);
    assert_eq!(t.square().to_decimal_string(), "1", "root is not a 2^{}-th root", k);
    w
}

fn bit_reverse<T: Clone>(v: &[T], log_n: u32) -> Vec<T> {
    let n = v.len();
    let mut out = v.to_vec();
    for i in 0..n {
        let mut r = 0usize;
        for b in 0..log_n {
            if i >> b & 1 == 1 {
                r |= 1 << (log_n - 1 - b);
            }
        }
        if r > i {
            out.swap(i, r);
        }
    }
    out
}

/// The oracle: `X[k] = sum_j a[j] * w^(j*k)`, straight from the definition.
fn naive_dft(a: &[Fr], w: &Fr) -> Vec<Fr> {
    let n = a.len();
    // w^(j*k) depends only on (j*k) mod n.
    let mut pow = Vec::with_capacity(n);
    let mut acc = Fr::one();
    for _ in 0..n {
        pow.push(acc);
        acc = acc.mul(w);
    }
    (0..n)
        .map(|k| {
            let mut s = Fr::zero();
            for j in 0..n {
                s = s.add(&a[j].mul(&pow[j * k % n]));
            }
            s
        })
        .collect()
}

/// Runs the whole transform on the device: `log2(n)` launches of the stage
/// kernel over a bit-reversed input.
fn gpu_ntt(ctx: &CudaContext, module: &KernelModule, a: &[Fr], w: &Fr) -> Vec<Fr> {
    let n = a.len();
    let log_n = n.trailing_zeros();
    let r = r_mod_p();

    let input = bit_reverse(a, log_n);
    let mut flat = Vec::with_capacity(n * 8);
    for x in &input {
        flat.extend_from_slice(&limbs32(x));
    }
    let d_x = ctx.alloc(n * 8 * 4).unwrap();
    ctx.memcpy_htod_at(&d_x, 0, as_bytes(&flat)).unwrap();

    for s in 1..=log_n {
        let m = 1usize << s;
        let half = m / 2;
        // omega_m = w^(n/m), and the table holds omega_m^pos * R.
        let step = w.pow_limbs(&[(n / m) as u64, 0, 0, 0]);
        let mut tw = Vec::with_capacity(half * 8);
        let mut cur = Fr::one();
        for _ in 0..half {
            tw.extend_from_slice(&limbs32(&cur.mul(&r)));
            cur = cur.mul(&step);
        }
        let d_tw = ctx.alloc(half * 8 * 4).unwrap();
        ctx.memcpy_htod_at(&d_tw, 0, as_bytes(&tw)).unwrap();

        let pairs = n / 2;
        let block = 256u32.min(pairs as u32);
        let grid = ((pairs as u32) + block - 1) / block;
        let args = vec![
            d_x.device_ptr(),
            d_tw.device_ptr(),
            half as u64,
            pairs as u64,
            n as u64,
        ];
        ctx.launch(module, (grid, 1, 1), (block, 1, 1), 0, &args)
            .expect("stage launch failed");
        ctx.synchronize().expect("stage did not complete");
    }

    let got = read_u32(ctx, &d_x, n * 8);
    (0..n)
        .map(|i| {
            let mut l = [0u64; 4];
            for j in 0..4 {
                l[j] = got[i * 8 + 2 * j] as u64 | ((got[i * 8 + 2 * j + 1] as u64) << 32);
            }
            Fr::from_limbs_reduce(l)
        })
        .collect()
}

#[test]
fn gpu_ntt_matches_a_naive_dft() {
    let Some(ctx) = CudaContext::new() else {
        eprintln!("SKIP: no CUDA driver — bn254_ntt_stage.ysu was not executed.");
        return;
    };
    let module = load_kernel(&ctx, "bn254_ntt_stage");

    const LOG_N: u32 = 10;
    const N: usize = 1 << LOG_N;
    let w = root_of_unity(LOG_N);

    let mut state = 0x1234_5678_9ABC_DEF0u64;
    let mut next = || {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        state >> 1
    };
    let a: Vec<Fr> = (0..N)
        .map(|_| Fr::from_limbs_reduce([next(), next(), next(), next()]))
        .collect();

    let want = naive_dft(&a, &w);
    let got = gpu_ntt(&ctx, &module, &a, &w);

    let mut wrong = 0;
    let mut first = String::new();
    for k in 0..N {
        if got[k].to_decimal_string() != want[k].to_decimal_string() {
            wrong += 1;
            if first.is_empty() {
                first = format!(
                    "k={}\n  GPU {}\n  DFT {}",
                    k,
                    got[k].to_decimal_string(),
                    want[k].to_decimal_string()
                );
            }
        }
    }
    assert_eq!(wrong, 0, "{} of {} NTT outputs disagree with the DFT.\n{}", wrong, N, first);
}

/// A transform is only useful if it inverts. `INTT(NTT(a)) == a` catches a
/// whole class of scaling and ordering errors that a forward-only check
/// against a matching-order DFT cannot see.
#[test]
fn the_transform_round_trips() {
    let Some(ctx) = CudaContext::new() else {
        eprintln!("SKIP: no CUDA driver.");
        return;
    };
    let module = load_kernel(&ctx, "bn254_ntt_stage");

    const LOG_N: u32 = 8;
    const N: usize = 1 << LOG_N;
    let w = root_of_unity(LOG_N);
    let w_inv = w.inv();
    let n_inv = Fr::from_u64(N as u64).inv();

    let mut state = 0x0FED_CBA9_8765_4321u64;
    let mut next = || {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        state >> 1
    };
    let a: Vec<Fr> = (0..N)
        .map(|_| Fr::from_limbs_reduce([next(), next(), next(), next()]))
        .collect();

    let fwd = gpu_ntt(&ctx, &module, &a, &w);
    let back = gpu_ntt(&ctx, &module, &fwd, &w_inv);
    for i in 0..N {
        assert_eq!(
            back[i].mul(&n_inv).to_decimal_string(),
            a[i].to_decimal_string(),
            "round trip failed at {}",
            i
        );
    }
}

/// The controls. Both tests above compare against something; these check the
/// something is real - that the root has the order claimed, and that the DFT
/// is not returning its input.
#[test]
fn the_oracle_is_not_vacuous() {
    let w = root_of_unity(4);
    // A primitive 16th root: 16 distinct powers, and only the 16th is one.
    let mut acc = Fr::one();
    let mut seen = std::collections::HashSet::new();
    for _ in 0..16 {
        assert!(seen.insert(acc.to_decimal_string()), "root is not primitive");
        acc = acc.mul(&w);
    }
    assert_eq!(acc.to_decimal_string(), "1");

    let a: Vec<Fr> = (1..=16u64).map(Fr::from_u64).collect();
    let x = naive_dft(&a, &w);
    // X[0] is the plain sum, 1 + ... + 16 = 136, and the transform must move
    // the other bins somewhere else.
    assert_eq!(x[0].to_decimal_string(), "136");
    assert_ne!(x[1].to_decimal_string(), a[1].to_decimal_string());
}

/// What a full-size NTT costs.  `--ignored`: a measurement, not a property.
///
/// Reported in three parts on purpose. A single end-to-end number here is
/// dominated by the harness, not the device: turning 2^20 `Fr` values into
/// limbs calls `to_limbs()`, which is itself a Montgomery multiply, so the
/// marshalling alone costs about as much as the transform. Quoting that as
/// "the NTT" would be measuring this test.
#[test]
#[ignore]
fn what_the_gpu_ntt_costs() {
    let Some(ctx) = CudaContext::new() else {
        eprintln!("SKIP: no CUDA driver.");
        return;
    };
    let module = load_kernel(&ctx, "bn254_ntt_stage");

    const LOG_N: u32 = 20;
    const N: usize = 1 << LOG_N;
    let w = root_of_unity(LOG_N);
    let mut state = 0xABCD_1234_5678_9EF0u64;
    let mut next = || {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        state >> 1
    };
    let a: Vec<Fr> = (0..N)
        .map(|_| Fr::from_limbs_reduce([next(), next(), next(), next()]))
        .collect();

    // ── setup, outside the timed region, as a library would have it ──
    let r = r_mod_p();
    let input = bit_reverse(&a, LOG_N);
    let mut flat = Vec::with_capacity(N * 8);
    for x in &input {
        flat.extend_from_slice(&limbs32(x));
    }
    let d_x = ctx.alloc(N * 8 * 4).unwrap();
    ctx.memcpy_htod_at(&d_x, 0, as_bytes(&flat)).unwrap();

    let mut stages = Vec::new();
    for s in 1..=LOG_N {
        let m = 1usize << s;
        let half = m / 2;
        let step = w.pow_limbs(&[(N / m) as u64, 0, 0, 0]);
        let mut tw = Vec::with_capacity(half * 8);
        let mut cur = Fr::one();
        for _ in 0..half {
            tw.extend_from_slice(&limbs32(&cur.mul(&r)));
            cur = cur.mul(&step);
        }
        let d_tw = ctx.alloc(half * 8 * 4).unwrap();
        ctx.memcpy_htod_at(&d_tw, 0, as_bytes(&tw)).unwrap();
        stages.push((half, d_tw));
    }

    // ── the device work: 20 stage launches over a resident array ──
    let reps = 5;
    let pairs = N / 2;
    let grid = (pairs / 256) as u32;
    ctx.synchronize().unwrap();
    let t0 = std::time::Instant::now();
    for _ in 0..reps {
        for (half, d_tw) in &stages {
            let args = vec![
                d_x.device_ptr(), d_tw.device_ptr(),
                *half as u64, pairs as u64, N as u64,
            ];
            ctx.launch(&module, (grid, 1, 1), (256, 1, 1), 0, &args).unwrap();
        }
    }
    ctx.synchronize().unwrap();
    let gpu_ms = t0.elapsed().as_secs_f64() * 1000.0 / reps as f64;

    // ── the same transform on one CPU core ──
    let t1 = std::time::Instant::now();
    let mut x = bit_reverse(&a, LOG_N);
    for s in 1..=LOG_N {
        let m = 1usize << s;
        let half = m / 2;
        let step = w.pow_limbs(&[(N / m) as u64, 0, 0, 0]);
        for k in (0..N).step_by(m) {
            let mut tw = Fr::one();
            for j in 0..half {
                let u = x[k + j];
                let v = x[k + j + half].mul(&tw);
                x[k + j] = u.add(&v);
                x[k + j + half] = u.sub(&v);
                tw = tw.mul(&step);
            }
        }
    }
    let cpu_ms = t1.elapsed().as_secs_f64() * 1000.0;
    std::hint::black_box(x);

    // ── and what the harness adds on top, so it is not mistaken for either ──
    let t2 = std::time::Instant::now();
    let br = bit_reverse(&a, LOG_N);
    let mut f2 = Vec::with_capacity(N * 8);
    for v in &br { f2.extend_from_slice(&limbs32(v)); }
    let host_ms = t2.elapsed().as_secs_f64() * 1000.0;
    std::hint::black_box(f2);

    let butterflies = (N / 2) as f64 * LOG_N as f64;
    println!("\nBN254 NTT, N = 2^{} = {}", LOG_N, N);
    println!("  GPU device time ({} stage launches): {:>8.2} ms  ({:.1} M butterflies/s)",
             LOG_N, gpu_ms, butterflies / gpu_ms / 1000.0);
    println!("  CPU, 1 thread, same algorithm:      {:>8.2} ms", cpu_ms);
    println!("  speedup: {:.1}x", cpu_ms / gpu_ms);
    println!();
    println!("  host marshalling (not counted above): {:>7.2} ms", host_ms);
    println!(
        "  Every stage re-reads and rewrites all {} MB of X from DRAM, so the\n\
         \x20 transform is bandwidth-bound and the small stages waste most of it.\n\
         \x20 Fusing them in shared memory is the next step, not more tuning.",
        N * 32 / 1_000_000
    );
}
