//! A radix-2 NTT over BN254 Fr, on the GPU, written in Y.
//!
//! `tests/bn254_ntt_stage.ysu` is one Cooley-Tukey stage: one butterfly per
//! thread, with the Montgomery multiply, the modular add and the modular
//! subtract all inlined and register-resident. The host launches it once per
//! stage. It is generated by `tools/gen_bn254_kernels.py` for the reason given
//! there - the backend has no local arrays, so an eight-limb value is eight
//! named scalars and every limb index has to be a literal.
//!
//! **The oracle is a naive O(N^2) DFT**, not another NTT. Checking a fast
//! transform against a fast transform shares the bug: a wrong twiddle order,
//! a missing bit-reversal or an off-by-one in the stage schedule appears in
//! both and cancels. The direct sum has no structure to get wrong, which is
//! the whole reason it is worth its 1M field multiplies here.

use std::path::{Path, PathBuf};
use std::process::Command;

use y::cuda_runtime::{CudaContext, DeviceBuffer, KernelModule};
use y::zk_field::Fr;

fn bin() -> PathBuf {
    let mut p = std::env::current_exe().unwrap();
    p.pop();
    if p.ends_with("deps") {
        p.pop();
    }
    p.join("Y")
}

fn repo() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

fn load_kernel(ctx: &CudaContext, entry: &str) -> KernelModule {
    let out = Command::new(bin())
        .arg(repo().join(format!("tests/{}.ysu", entry)))
        .arg("--emit-ptx")
        .current_dir(repo())
        .output()
        .expect("failed to run the Y binary");
    assert!(
        out.status.success(),
        "{}.ysu did not compile:\n{}{}",
        entry,
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    let ptx = std::fs::read_to_string(repo().join(format!("tests/{}.ptx", entry))).unwrap();
    assert!(
        !ptx.contains("ld.global.f32") && !ptx.contains("add.f32"),
        "{} is routing field limbs through the float datapath",
        entry
    );
    // `Y_PTX_MAXNREG` rewrites the emitter's `.maxnreg` before JIT, for
    // measuring what register pressure is actually costing. The emitter
    // derives that number from its VIRTUAL register count, which in a fully
    // unrolled kernel runs into the thousands and buckets straight to 255 -
    // nowhere near the ~82 ptxas really needs, and the difference is whole
    // blocks of occupancy.
    let ptx = match std::env::var("Y_PTX_MAXNREG") {
        Ok(v) => {
            let mut out = String::with_capacity(ptx.len());
            for line in ptx.lines() {
                if line.trim_start().starts_with(".maxnreg") {
                    out.push_str(&format!(".maxnreg {}\n", v));
                } else {
                    out.push_str(line);
                    out.push('\n');
                }
            }
            out
        }
        Err(_) => ptx,
    };
    ctx.load_ptx(&ptx, entry)
        .unwrap_or_else(|e| panic!("{} did not load: {}", entry, e))
}

fn limbs32(x: &Fr) -> [u32; 8] {
    let l = x.to_limbs();
    let mut o = [0u32; 8];
    for i in 0..4 {
        o[2 * i] = l[i] as u32;
        o[2 * i + 1] = (l[i] >> 32) as u32;
    }
    o
}

/// Planar arrays of `uint4`: limb `j` of element `i` at
/// `[(j/4) * 4n + i*4 + (j%4)]`. See the note in `tools/gen_bn254_kernels.py`.
fn to_planar(v: &[Fr], n: usize) -> Vec<u32> {
    let mut out = vec![0u32; n * 8];
    for (i, x) in v.iter().enumerate() {
        let l = limbs32(x);
        for j in 0..8 {
            out[(j / 4) * 4 * n + i * 4 + (j % 4)] = l[j];
        }
    }
    out
}

fn from_planar(raw: &[u32], n: usize) -> Vec<Fr> {
    let limb = |i: usize, j: usize| raw[(j / 4) * 4 * n + i * 4 + (j % 4)] as u64;
    (0..n)
        .map(|i| {
            let mut l = [0u64; 4];
            for j in 0..4 {
                l[j] = limb(i, 2 * j) | (limb(i, 2 * j + 1) << 32);
            }
            Fr::from_limbs_reduce(l)
        })
        .collect()
}

fn as_bytes(v: &[u32]) -> &[u8] {
    unsafe { std::slice::from_raw_parts(v.as_ptr() as *const u8, v.len() * 4) }
}

fn read_u32(ctx: &CudaContext, buf: &DeviceBuffer, n: usize) -> Vec<u32> {
    let mut raw = vec![0u8; n * 4];
    ctx.memcpy_dtoh_at(&mut raw, buf, 0).unwrap();
    raw.chunks_exact(4)
        .map(|c| u32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

/// `R mod p`, via the public API only (`Fr`'s Montgomery limbs are private).
/// The kernel's multiply returns `a * b * R^-1`, so a twiddle goes in as
/// `w * R` and the butterfly's product comes out canonical.
fn r_mod_p() -> Fr {
    let mut r = Fr::from_u64(1);
    for _ in 0..256 {
        r = r.add(&r);
    }
    r
}

/// A primitive `2^k`-th root of unity in BN254 Fr.
///
/// `Fr*` has order `p - 1`, whose 2-adic valuation is 28, so roots exist for
/// every `k <= 28`. `5` is a generator; `5^((p-1)/2^k)` therefore has order
/// exactly `2^k`, which the caller checks rather than assumes.
fn root_of_unity(k: u32) -> Fr {
    assert!(k <= 28, "BN254 Fr has 2-adicity 28");
    // (p - 1) / 2^k, as four little-endian u64 limbs.
    let p_minus_1 = Fr::zero().sub(&Fr::one()).to_limbs();
    let mut e = p_minus_1;
    for _ in 0..k {
        // shift right by one across the four limbs
        for i in 0..3 {
            e[i] = (e[i] >> 1) | (e[i + 1] << 63);
        }
        e[3] >>= 1;
    }
    let w = Fr::from_u64(5).pow_limbs(&e);

    // Order exactly 2^k: w^(2^k) == 1 and w^(2^(k-1)) != 1.
    let mut t = w;
    for _ in 0..k.saturating_sub(1) {
        t = t.square();
    }
    assert_ne!(t.to_decimal_string(), "1", "root has order below 2^{}", k);
    assert_eq!(t.square().to_decimal_string(), "1", "root is not a 2^{}-th root", k);
    w
}

fn bit_reverse<T: Clone>(v: &[T], log_n: u32) -> Vec<T> {
    let n = v.len();
    let mut out = v.to_vec();
    for i in 0..n {
        let mut r = 0usize;
        for b in 0..log_n {
            if i >> b & 1 == 1 {
                r |= 1 << (log_n - 1 - b);
            }
        }
        if r > i {
            out.swap(i, r);
        }
    }
    out
}

/// The oracle: `X[k] = sum_j a[j] * w^(j*k)`, straight from the definition.
fn naive_dft(a: &[Fr], w: &Fr) -> Vec<Fr> {
    let n = a.len();
    // w^(j*k) depends only on (j*k) mod n.
    let mut pow = Vec::with_capacity(n);
    let mut acc = Fr::one();
    for _ in 0..n {
        pow.push(acc);
        acc = acc.mul(w);
    }
    (0..n)
        .map(|k| {
            let mut s = Fr::zero();
            for j in 0..n {
                s = s.add(&a[j].mul(&pow[j * k % n]));
            }
            s
        })
        .collect()
}

/// Runs the whole transform on the device: `log2(n)` launches of the stage
/// kernel over a bit-reversed input.
fn gpu_ntt(ctx: &CudaContext, module: &KernelModule, a: &[Fr], w: &Fr) -> Vec<Fr> {
    let n = a.len();
    let log_n = n.trailing_zeros();
    let r = r_mod_p();

    let flat = to_planar(&bit_reverse(a, log_n), n);
    let d_x = ctx.alloc(n * 8 * 4).unwrap();
    ctx.memcpy_htod_at(&d_x, 0, as_bytes(&flat)).unwrap();

    for s in 1..=log_n {
        let m = 1usize << s;
        let half = m / 2;
        // omega_m = w^(n/m), and the table holds omega_m^pos * R.
        let step = w.pow_limbs(&[(n / m) as u64, 0, 0, 0]);
        let mut tws = Vec::with_capacity(half);
        let mut cur = Fr::one();
        for _ in 0..half {
            tws.push(cur.mul(&r));
            cur = cur.mul(&step);
        }
        let tw = to_planar(&tws, half);
        let d_tw = ctx.alloc(half * 8 * 4).unwrap();
        ctx.memcpy_htod_at(&d_tw, 0, as_bytes(&tw)).unwrap();

        let pairs = n / 2;
        let block = 256u32.min(pairs as u32);
        let grid = ((pairs as u32) + block - 1) / block;
        let args = vec![
            d_x.device_ptr(),
            d_tw.device_ptr(),
            half as u64,
            pairs as u64,
            n as u64,
        ];
        ctx.launch(module, (grid, 1, 1), (block, 1, 1), 0, &args)
            .expect("stage launch failed");
        ctx.synchronize().expect("stage did not complete");
    }

    from_planar(&read_u32(ctx, &d_x, n * 8), n)
}

/// Base-4 digit reversal, the input permutation a radix-4 DIT needs.
///
/// Digit reversal is an involution, so the swap loop is safe.
fn digit_reverse4<T: Clone>(v: &[T], log_n: u32) -> Vec<T> {
    assert_eq!(log_n % 2, 0, "radix-4 needs N = 4^k");
    let n = v.len();
    let k = log_n / 2;
    let mut out = v.to_vec();
    for i in 0..n {
        let (mut r, mut t) = (0usize, i);
        for _ in 0..k {
            r = r * 4 + (t & 3);
            t >>= 2;
        }
        if r > i {
            out.swap(i, r);
        }
    }
    out
}

/// Everything the radix-4 stages need on the device, built once.
struct Radix4Plan {
    stages: Vec<(usize, DeviceBuffer, DeviceBuffer, DeviceBuffer)>, // quarter, w^p, w^2p, w^3p
    i_root: DeviceBuffer,
}

fn radix4_plan(ctx: &CudaContext, n: usize, log_n: u32, w: &Fr) -> Radix4Plan {
    let r = r_mod_p();
    let mut stages = Vec::new();
    let mut m = 4usize;
    while m <= n {
        let q = m / 4;
        let wm = w.pow_limbs(&[(n / m) as u64, 0, 0, 0]);
        let mut t1 = Vec::with_capacity(q);
        let mut t2 = Vec::with_capacity(q);
        let mut t3 = Vec::with_capacity(q);
        let mut cur = Fr::one();
        for _ in 0..q {
            let c2 = cur.mul(&cur);
            t1.push(cur.mul(&r));
            t2.push(c2.mul(&r));
            t3.push(c2.mul(&cur).mul(&r));
            cur = cur.mul(&wm);
        }
        let mk = |v: &[Fr]| {
            let f = to_planar(v, v.len());
            let d = ctx.alloc(v.len() * 8 * 4).unwrap();
            ctx.memcpy_htod_at(&d, 0, as_bytes(&f)).unwrap();
            d
        };
        stages.push((q, mk(&t1), mk(&t2), mk(&t3)));
        m *= 4;
    }
    // The primitive 4th root. Taken from `w` itself, so the inverse transform
    // (which passes w^-1) automatically gets i^-1 rather than i.
    let i_root = {
        let v = vec![w.pow_limbs(&[(n / 4) as u64, 0, 0, 0]).mul(&r)];
        let f = to_planar(&v, 1);
        let d = ctx.alloc(8 * 4).unwrap();
        ctx.memcpy_htod_at(&d, 0, as_bytes(&f)).unwrap();
        d
    };
    Radix4Plan { stages, i_root }
}

fn gpu_ntt4(ctx: &CudaContext, module: &KernelModule, a: &[Fr], w: &Fr) -> Vec<Fr> {
    let n = a.len();
    let log_n = n.trailing_zeros();
    let flat = to_planar(&digit_reverse4(a, log_n), n);
    let d_x = ctx.alloc(n * 8 * 4).unwrap();
    ctx.memcpy_htod_at(&d_x, 0, as_bytes(&flat)).unwrap();

    let plan = radix4_plan(ctx, n, log_n, w);
    let butterflies = n / 4;
    let block = 256u32.min(butterflies as u32);
    let grid = (butterflies as u32).div_ceil(block);
    for (q, t1, t2, t3) in &plan.stages {
        let args = vec![
            d_x.device_ptr(), t1.device_ptr(), t2.device_ptr(), t3.device_ptr(),
            plan.i_root.device_ptr(), *q as u64, n as u64,
        ];
        ctx.launch(module, (grid, 1, 1), (block, 1, 1), 0, &args)
            .expect("radix-4 stage launch failed");
        ctx.synchronize().expect("radix-4 stage did not complete");
    }
    from_planar(&read_u32(ctx, &d_x, n * 8), n)
}

/// The radix-4 transform, against the same naive DFT. Nothing about halving
/// the pass count is allowed to change the answer.
#[test]
fn gpu_radix4_ntt_matches_a_naive_dft() {
    let Some(ctx) = CudaContext::new() else {
        eprintln!("SKIP: no CUDA driver — bn254_ntt4_stage.ysu was not executed.");
        return;
    };
    let module = load_kernel(&ctx, "bn254_ntt4_stage");

    const LOG_N: u32 = 10;
    const N: usize = 1 << LOG_N;
    let w = root_of_unity(LOG_N);
    let mut state = 0x7E57_D06_0BADu64;
    let mut next = || {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        state >> 1
    };
    let a: Vec<Fr> = (0..N)
        .map(|_| Fr::from_limbs_reduce([next(), next(), next(), next()]))
        .collect();

    let want = naive_dft(&a, &w);
    let got = gpu_ntt4(&ctx, &module, &a, &w);
    for k in 0..N {
        assert_eq!(
            got[k].to_decimal_string(),
            want[k].to_decimal_string(),
            "radix-4 output {} disagrees with the DFT",
            k
        );
    }
}

/// And it must agree with the radix-2 path element for element, since a real
/// library would pick between them by size alone.
#[test]
fn radix4_and_radix2_agree() {
    let Some(ctx) = CudaContext::new() else {
        eprintln!("SKIP: no CUDA driver.");
        return;
    };
    let m2 = load_kernel(&ctx, "bn254_ntt_stage");
    let m4 = load_kernel(&ctx, "bn254_ntt4_stage");
    const LOG_N: u32 = 12;
    const N: usize = 1 << LOG_N;
    let w = root_of_unity(LOG_N);
    let a: Vec<Fr> = (0..N).map(|i| Fr::from_u64((i * 7 + 3) as u64)).collect();
    let r2 = gpu_ntt(&ctx, &m2, &a, &w);
    let r4 = gpu_ntt4(&ctx, &m4, &a, &w);
    for k in 0..N {
        assert_eq!(r2[k].to_decimal_string(), r4[k].to_decimal_string(),
                   "radix-2 and radix-4 disagree at {}", k);
    }
}

#[test]
fn gpu_ntt_matches_a_naive_dft() {
    let Some(ctx) = CudaContext::new() else {
        eprintln!("SKIP: no CUDA driver — bn254_ntt_stage.ysu was not executed.");
        return;
    };
    let module = load_kernel(&ctx, "bn254_ntt_stage");

    const LOG_N: u32 = 10;
    const N: usize = 1 << LOG_N;
    let w = root_of_unity(LOG_N);

    let mut state = 0x1234_5678_9ABC_DEF0u64;
    let mut next = || {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        state >> 1
    };
    let a: Vec<Fr> = (0..N)
        .map(|_| Fr::from_limbs_reduce([next(), next(), next(), next()]))
        .collect();

    let want = naive_dft(&a, &w);
    let got = gpu_ntt(&ctx, &module, &a, &w);

    let mut wrong = 0;
    let mut first = String::new();
    for k in 0..N {
        if got[k].to_decimal_string() != want[k].to_decimal_string() {
            wrong += 1;
            if first.is_empty() {
                first = format!(
                    "k={}\n  GPU {}\n  DFT {}",
                    k,
                    got[k].to_decimal_string(),
                    want[k].to_decimal_string()
                );
            }
        }
    }
    assert_eq!(wrong, 0, "{} of {} NTT outputs disagree with the DFT.\n{}", wrong, N, first);
}

/// A transform is only useful if it inverts. `INTT(NTT(a)) == a` catches a
/// whole class of scaling and ordering errors that a forward-only check
/// against a matching-order DFT cannot see.
#[test]
fn the_transform_round_trips() {
    let Some(ctx) = CudaContext::new() else {
        eprintln!("SKIP: no CUDA driver.");
        return;
    };
    let module = load_kernel(&ctx, "bn254_ntt_stage");

    const LOG_N: u32 = 8;
    const N: usize = 1 << LOG_N;
    let w = root_of_unity(LOG_N);
    let w_inv = w.inv();
    let n_inv = Fr::from_u64(N as u64).inv();

    let mut state = 0x0FED_CBA9_8765_4321u64;
    let mut next = || {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        state >> 1
    };
    let a: Vec<Fr> = (0..N)
        .map(|_| Fr::from_limbs_reduce([next(), next(), next(), next()]))
        .collect();

    let fwd = gpu_ntt(&ctx, &module, &a, &w);
    let back = gpu_ntt(&ctx, &module, &fwd, &w_inv);
    for i in 0..N {
        assert_eq!(
            back[i].mul(&n_inv).to_decimal_string(),
            a[i].to_decimal_string(),
            "round trip failed at {}",
            i
        );
    }
}

/// The controls. Both tests above compare against something; these check the
/// something is real - that the root has the order claimed, and that the DFT
/// is not returning its input.
#[test]
fn the_oracle_is_not_vacuous() {
    let w = root_of_unity(4);
    // A primitive 16th root: 16 distinct powers, and only the 16th is one.
    let mut acc = Fr::one();
    let mut seen = std::collections::HashSet::new();
    for _ in 0..16 {
        assert!(seen.insert(acc.to_decimal_string()), "root is not primitive");
        acc = acc.mul(&w);
    }
    assert_eq!(acc.to_decimal_string(), "1");

    let a: Vec<Fr> = (1..=16u64).map(Fr::from_u64).collect();
    let x = naive_dft(&a, &w);
    // X[0] is the plain sum, 1 + ... + 16 = 136, and the transform must move
    // the other bins somewhere else.
    assert_eq!(x[0].to_decimal_string(), "136");
    assert_ne!(x[1].to_decimal_string(), a[1].to_decimal_string());
}

/// What a full-size NTT costs.  `--ignored`: a measurement, not a property.
///
/// Reported in three parts on purpose. A single end-to-end number here is
/// dominated by the harness, not the device: turning 2^20 `Fr` values into
/// limbs calls `to_limbs()`, which is itself a Montgomery multiply, so the
/// marshalling alone costs about as much as the transform. Quoting that as
/// "the NTT" would be measuring this test.
#[test]
#[ignore]
fn what_the_gpu_ntt_costs() {
    let Some(ctx) = CudaContext::new() else {
        eprintln!("SKIP: no CUDA driver.");
        return;
    };
    let module = load_kernel(&ctx, "bn254_ntt_stage");

    const LOG_N: u32 = 20;
    const N: usize = 1 << LOG_N;
    let w = root_of_unity(LOG_N);
    let mut state = 0xABCD_1234_5678_9EF0u64;
    let mut next = || {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        state >> 1
    };
    let a: Vec<Fr> = (0..N)
        .map(|_| Fr::from_limbs_reduce([next(), next(), next(), next()]))
        .collect();

    // ── setup, outside the timed region, as a library would have it ──
    let r = r_mod_p();
    let input = bit_reverse(&a, LOG_N);
    let flat = to_planar(&input, N);
    let d_x = ctx.alloc(N * 8 * 4).unwrap();
    ctx.memcpy_htod_at(&d_x, 0, as_bytes(&flat)).unwrap();

    let mut stages = Vec::new();
    for s in 1..=LOG_N {
        let m = 1usize << s;
        let half = m / 2;
        let step = w.pow_limbs(&[(N / m) as u64, 0, 0, 0]);
        let mut tws = Vec::with_capacity(half);
        let mut cur = Fr::one();
        for _ in 0..half {
            tws.push(cur.mul(&r));
            cur = cur.mul(&step);
        }
        let tw = to_planar(&tws, half);
        let d_tw = ctx.alloc(half * 8 * 4).unwrap();
        ctx.memcpy_htod_at(&d_tw, 0, as_bytes(&tw)).unwrap();
        stages.push((half, d_tw));
    }

    // ── the device work: 20 stage launches over a resident array ──
    let reps = 5;
    let pairs = N / 2;
    let grid = (pairs / 256) as u32;
    ctx.synchronize().unwrap();
    let t0 = std::time::Instant::now();
    for _ in 0..reps {
        for (half, d_tw) in &stages {
            let args = vec![
                d_x.device_ptr(), d_tw.device_ptr(),
                *half as u64, pairs as u64, N as u64,
            ];
            ctx.launch(&module, (grid, 1, 1), (256, 1, 1), 0, &args).unwrap();
        }
    }
    ctx.synchronize().unwrap();
    let gpu_ms = t0.elapsed().as_secs_f64() * 1000.0 / reps as f64;

    // ── the same transform on one CPU core ──
    let t1 = std::time::Instant::now();
    let mut x = bit_reverse(&a, LOG_N);
    for s in 1..=LOG_N {
        let m = 1usize << s;
        let half = m / 2;
        let step = w.pow_limbs(&[(N / m) as u64, 0, 0, 0]);
        for k in (0..N).step_by(m) {
            let mut tw = Fr::one();
            for j in 0..half {
                let u = x[k + j];
                let v = x[k + j + half].mul(&tw);
                x[k + j] = u.add(&v);
                x[k + j + half] = u.sub(&v);
                tw = tw.mul(&step);
            }
        }
    }
    let cpu_ms = t1.elapsed().as_secs_f64() * 1000.0;
    std::hint::black_box(x);

    // ── and what the harness adds on top, so it is not mistaken for either ──
    let t2 = std::time::Instant::now();
    let br = bit_reverse(&a, LOG_N);
    let f2 = to_planar(&br, N);
    let host_ms = t2.elapsed().as_secs_f64() * 1000.0;
    std::hint::black_box(f2);

    let butterflies = (N / 2) as f64 * LOG_N as f64;
    println!("\nBN254 NTT, N = 2^{} = {}", LOG_N, N);
    println!("  GPU device time ({} stage launches): {:>8.2} ms  ({:.1} M butterflies/s)",
             LOG_N, gpu_ms, butterflies / gpu_ms / 1000.0);
    println!("  CPU, 1 thread, same algorithm:      {:>8.2} ms", cpu_ms);
    println!("  speedup: {:.1}x", cpu_ms / gpu_ms);
    println!();
    println!("  host marshalling (not counted above): {:>7.2} ms", host_ms);
    println!(
        "  Every stage re-reads and rewrites all {} MB of X from DRAM, so the\n\
         \x20 transform is bandwidth-bound and the small stages waste most of it.\n\
         \x20 Fusing them in shared memory is the next step, not more tuning.",
        N * 32 / 1_000_000
    );
}

// ── Is the GPU actually winning? ────────────────────────────────────────────

/// One NTT stage across `nthreads` threads, using precomputed twiddles.
///
/// Two parallel shapes, because one is not enough. While there are more blocks
/// than threads, the blocks are independent and `chunks_mut(m)` splits them.
/// The last few stages have fewer blocks than threads - at `m = N` there is one
/// - and leaving those serial caps the whole thing by Amdahl at about 4x
/// however many cores are present. So within a block, `split_at_mut` separates
/// the two halves the butterfly touches, and the `j` range parallelises
/// instead.
fn cpu_ntt_stage(x: &mut [Fr], m: usize, tw: &[Fr], nthreads: usize) {
    let half = m / 2;
    let n = x.len();
    if n / m >= nthreads {
        let per = (n / m).div_ceil(nthreads) * m;
        std::thread::scope(|s| {
            for chunk in x.chunks_mut(per) {
                s.spawn(move || {
                    for blk in chunk.chunks_mut(m) {
                        let (lo, hi) = blk.split_at_mut(half);
                        for j in 0..half {
                            let u = lo[j];
                            let v = hi[j].mul(&tw[j]);
                            lo[j] = u.add(&v);
                            hi[j] = u.sub(&v);
                        }
                    }
                });
            }
        });
    } else {
        for blk in x.chunks_mut(m) {
            let (lo, hi) = blk.split_at_mut(half);
            let per = half.div_ceil(nthreads).max(1);
            std::thread::scope(|s| {
                for (ci, (lc, hc)) in lo.chunks_mut(per).zip(hi.chunks_mut(per)).enumerate() {
                    let tws = &tw[ci * per..];
                    s.spawn(move || {
                        for j in 0..lc.len() {
                            let u = lc[j];
                            let v = hc[j].mul(&tws[j]);
                            lc[j] = u.add(&v);
                            hc[j] = u.sub(&v);
                        }
                    });
                }
            });
        }
    }
}

/// The comparison that actually answers "is this worth a GPU".
///
/// The 60.6x in `what_the_gpu_ntt_costs` is device time against ONE core, and
/// no one runs a prover on one core. This times the whole 16-core machine, and
/// counts what offloading really costs: the PCIe transfer in both directions.
///
/// It also reports the case that matters more in practice - data already
/// resident on the device, because a real prover chains NTTs and MSMs without
/// coming back to the host between them.
///
/// Two measurement traps this has already fallen into, both worth keeping:
///
///   - **Warm the GPU.** The CPU thread sweep above leaves the device idle for
///     the better part of a second, which drops its clocks. Measured cold, the
///     first timed rep absorbed the whole ramp and reported 30.6 ms against a
///     warm 1.8 - and, being wall-clock, stole that time from the PCIe figure
///     taken after it, which came back 8x too fast. Hence the warmup and the
///     minimum over interleaved rounds.
///   - **Size it past L2.** `LOG_N = 20` is 33 MB, which fits inside this
///     card's 48 MB L2, and the transform then runs above DRAM peak: 0.88 ms,
///     41.8x the parallel CPU. That is a real effect and a real use case, but
///     quoting it alone is quoting a cache hit. At `LOG_N = 23` (268 MB, 5.6x
///     L2) it is 22.5 ms, 12.3x, and 82% of DRAM peak - the number to trust.
///
/// Profiled with NCU. What that changed, and what it did not:
///
///   - The layout transpose (array-of-structs -> struct-of-arrays, see
///     `tools/gen_bn254_kernels.py`) took one stage launch from 252.5 us to
///     88.5 us and the whole 2^20 transform from 1.81 ms to 0.88 ms. Warp
///     cycles per issued instruction: 64.3 -> 15.1.
///   - It is worth ~nothing at 2^23, because that size is already at 82% of
///     DRAM peak and a transpose moves no fewer bytes. Fewer PASSES is the
///     only lever left there, i.e. fusing stages in shared memory.
///   - **Occupancy is a red herring here, and NCU says otherwise.** It reports
///     26.9% achieved occupancy and 2 blocks/SM limited by registers, which
///     reads as an obvious fix. It is not: forcing the register count down
///     with `Y_PTX_MAXNREG` - with ZERO spills at every level tested - makes
///     it strictly slower (255: 0.87 ms, 96: 0.86, 80: 1.38, 64: 1.26, 48:
///     3.39). The kernel is bandwidth-bound with plenty of ILP, so more
///     resident blocks buy nothing and cost L2 contention. Measure before
///     acting on an occupancy warning.
///
/// Sanity-check any figure here against the bandwidth it implies before
/// believing it. That is what caught the cold run: 30.6 ms implies 44 GB/s,
/// which no GPU of this class does.
///
/// ## Bandwidth efficiency is finished; pass count is not
///
/// Profiled per radix-4 stage at N = 2^22 (a 134.2 MB array):
///
///   dram__bytes_read   135.81 MB    dram__bytes_write  118.76 MB
///   254.57 MB in 424.5 us  =  600 GB/s  =  89% of the 672 GB/s peak
///
/// Reads exceed the array itself by 1.6 MB, i.e. the three twiddle tables are
/// served almost entirely by L2. **There is no wasted traffic left to
/// recover** - every byte moved is one the algorithm needs, at 89% of peak.
/// Tuning the access pattern further cannot buy more than the last 11%.
///
/// The only remaining lever is moving over the array fewer times, and both
/// roads to that need the same missing compiler feature - `ld.shared` /
/// `st.shared`, which are unwired (shared memory currently computes an
/// address and then accesses it as global):
///
///   today, radix-4                          11 passes
///   + the 5 small stages fused in shared     7 passes   ~1.57x
///   four-step (Bailey), NTTs held in shared  3-4 passes ~3x
///
/// Radix-8 is the cheap-looking alternative and is not worth it: 8 passes
/// (1.37x) for eight elements plus seven twiddles live at once, where radix-4
/// already needs 96 registers.
#[test]
#[ignore]
fn is_the_gpu_actually_winning() {
    let Some(ctx) = CudaContext::new() else {
        eprintln!("SKIP: no CUDA driver.");
        return;
    };
    let module = load_kernel(&ctx, "bn254_ntt_stage");

    const LOG_N: u32 = 22;
    const N: usize = 1 << LOG_N;
    let nthreads = std::thread::available_parallelism().map(|p| p.get()).unwrap_or(1);
    let w = root_of_unity(LOG_N);
    let r = r_mod_p();

    let mut state = 0x2468_ACE0_1357_9BDFu64;
    let mut next = || {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        state >> 1
    };
    let a: Vec<Fr> = (0..N)
        .map(|_| Fr::from_limbs_reduce([next(), next(), next(), next()]))
        .collect();

    // Twiddle tables, precomputed once for BOTH sides. The GPU reads a table;
    // letting the CPU derive its twiddles by a multiply per butterfly would
    // charge it for work the GPU does not do.
    let mut tables: Vec<Vec<Fr>> = Vec::new();
    for s in 1..=LOG_N {
        let m = 1usize << s;
        let step = w.pow_limbs(&[(N / m) as u64, 0, 0, 0]);
        let mut t = Vec::with_capacity(m / 2);
        let mut cur = Fr::one();
        for _ in 0..m / 2 {
            t.push(cur);
            cur = cur.mul(&step);
        }
        tables.push(t);
    }

    // ── CPU, all cores ──
    let mut x = bit_reverse(&a, LOG_N);
    let t0 = std::time::Instant::now();
    for s in 1..=LOG_N {
        cpu_ntt_stage(&mut x, 1 << s, &tables[(s - 1) as usize], nthreads);
    }
    let cpu_par_ms = t0.elapsed().as_secs_f64() * 1000.0;

    // ── CPU thread sweep, so the baseline is where the CPU actually
    // plateaus rather than wherever `available_parallelism` happens to land.
    // SMT can make 32 slower than 16 on a compute-bound kernel, and quoting
    // the wrong one moves the GPU's ratio either way.
    let mut sweep = Vec::new();
    let mut cpu_one_ms = 0.0;
    for &nt in &[1usize, 2, 4, 8, 16, 24, 32] {
        if nt > nthreads { continue; }
        let mut y = bit_reverse(&a, LOG_N);
        let t = std::time::Instant::now();
        for s in 1..=LOG_N {
            cpu_ntt_stage(&mut y, 1 << s, &tables[(s - 1) as usize], nt);
        }
        let ms = t.elapsed().as_secs_f64() * 1000.0;
        assert_eq!(x[7].to_decimal_string(), y[7].to_decimal_string(),
                   "the {}-thread CPU path disagrees with the {}-thread one", nt, nthreads);
        if nt == 1 { cpu_one_ms = ms; }
        sweep.push((nt, ms));
    }
    let cpu_best_ms = sweep.iter().map(|s| s.1).fold(f64::INFINITY, f64::min);

    // ── GPU ──
    let flat = to_planar(&bit_reverse(&a, LOG_N), N);
    let d_x = ctx.alloc(N * 8 * 4).unwrap();
    let mut dev_tw = Vec::new();
    for t in &tables {
        let f = to_planar(&t.iter().map(|v| v.mul(&r)).collect::<Vec<_>>(), t.len());
        let d = ctx.alloc(t.len() * 8 * 4).unwrap();
        ctx.memcpy_htod_at(&d, 0, as_bytes(&f)).unwrap();
        dev_tw.push((t.len(), d));
    }

    let pairs = N / 2;
    let grid = (pairs / 256) as u32;
    let launch = |ctx: &CudaContext| {
        for (half, d) in &dev_tw {
            let args = vec![
                d_x.device_ptr(), d.device_ptr(),
                *half as u64, pairs as u64, N as u64,
            ];
            ctx.launch(&module, (grid, 1, 1), (256, 1, 1), 0, &args).unwrap();
        }
    };

    // The CPU sweep above leaves the GPU idle for the better part of a
    // second, which drops its clocks to idle. Measured cold, the first timed
    // rep absorbed the whole ramp and reported 30.6 ms against a warm 8.4 -
    // and, being wall-clock, it stole that time from the PCIe figure measured
    // after it, which came back 8x too fast. So: warm first, then take the
    // MINIMUM over interleaved rounds, which is this repo's standing rule for
    // GPU timing precisely because a ramp can only ever make a run slower.
    ctx.memcpy_htod_at(&d_x, 0, as_bytes(&flat)).unwrap();
    for _ in 0..5 {
        launch(&ctx);
    }
    ctx.synchronize().unwrap();

    // ── radix-4: half the passes, and fewer multiplies ──
    let m4 = load_kernel(&ctx, "bn254_ntt4_stage");
    let flat4 = to_planar(&digit_reverse4(&a, LOG_N), N);
    let d_x4 = ctx.alloc(N * 8 * 4).unwrap();
    ctx.memcpy_htod_at(&d_x4, 0, as_bytes(&flat4)).unwrap();
    let plan4 = radix4_plan(&ctx, N, LOG_N, &w);
    let bf = N / 4;
    let launch4 = |ctx: &CudaContext| {
        for (q, t1, t2, t3) in &plan4.stages {
            let args = vec![
                d_x4.device_ptr(), t1.device_ptr(), t2.device_ptr(), t3.device_ptr(),
                plan4.i_root.device_ptr(), *q as u64, N as u64,
            ];
            ctx.launch(&m4, ((bf / 256) as u32, 1, 1), (256, 1, 1), 0, &args).unwrap();
        }
    };
    for _ in 0..5 {
        launch4(&ctx);
    }
    ctx.synchronize().unwrap();
    let mut gpu_r4_ms = f64::INFINITY;
    for _ in 0..7 {
        ctx.synchronize().unwrap();
        let t = std::time::Instant::now();
        launch4(&ctx);
        ctx.synchronize().unwrap();
        gpu_r4_ms = gpu_r4_ms.min(t.elapsed().as_secs_f64() * 1000.0);
    }

    let mut back = vec![0u8; N * 8 * 4];
    let mut gpu_resident_ms = f64::INFINITY;
    let mut gpu_offload_ms = f64::INFINITY;
    for _ in 0..7 {
        ctx.synchronize().unwrap();
        let t = std::time::Instant::now();
        launch(&ctx);
        ctx.synchronize().unwrap();
        gpu_resident_ms = gpu_resident_ms.min(t.elapsed().as_secs_f64() * 1000.0);

        ctx.synchronize().unwrap();
        let t = std::time::Instant::now();
        ctx.memcpy_htod_at(&d_x, 0, as_bytes(&flat)).unwrap();
        launch(&ctx);
        ctx.memcpy_dtoh_at(&mut back, &d_x, 0).unwrap();
        ctx.synchronize().unwrap();
        gpu_offload_ms = gpu_offload_ms.min(t.elapsed().as_secs_f64() * 1000.0);
    }

    println!("\nBN254 NTT, N = 2^{} = {}  ({} MB of field elements)", LOG_N, N, N * 32 / 1_000_000);
    println!("  machine: {} hardware threads", nthreads);
    println!();
    for (nt, ms) in &sweep {
        println!("  CPU, {:>2} thread(s):            {:>9.2} ms   ({:.1}x over one)",
                 nt, ms, cpu_one_ms / ms);
    }
    println!("  --- best CPU: {:.2} ms ---", cpu_best_ms);
    println!("  GPU, data already resident:   {:>9.2} ms   ({:.1}x over the BEST CPU)",
             gpu_resident_ms, cpu_best_ms / gpu_resident_ms);
    println!("  GPU, radix-4, resident:       {:>9.2} ms   ({:.1}x over the BEST CPU)",
             gpu_r4_ms, cpu_best_ms / gpu_r4_ms);
    println!("  GPU, offloaded over PCIe:     {:>9.2} ms   ({:.1}x over the BEST CPU)",
             gpu_offload_ms, cpu_best_ms / gpu_offload_ms);
    println!("  radix-4 vs radix-2: {:.2}x  ({} passes vs {})",
             gpu_resident_ms / gpu_r4_ms, plan4.stages.len(), LOG_N);
    let _ = cpu_par_ms;
    println!();
    println!("  PCIe round trip is {:.2} ms of that, {:.0}% of the offloaded time.",
             gpu_offload_ms - gpu_resident_ms,
             (gpu_offload_ms - gpu_resident_ms) / gpu_offload_ms * 100.0);
}
