; ================================================
;  Generated by Y Compiler — LLVM IR Backend
;  Hardware Profile: AVX=true, AVX512=true, L2 Line=64B
; ================================================

target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

attributes #0 = { "target-cpu"="skylake-avx512" "target-features"="+avx512f,+avx512cd,+avx512bw,+avx512dq,+avx512vl" }

; --- Struct Definitions ---

; --- Enum Definitions ---

; --- External Runtime Declarations ---
declare ptr @ystr_new(ptr)
declare void @ystr_push(ptr, i8)
declare void @ystr_push_str(ptr, ptr)
declare i1 @ystr_eq_cstr(ptr, ptr)
declare i64 @ystr_len(ptr)
declare i8 @ystr_char_at(ptr, i64)
declare ptr @ystr_clone(ptr)
declare ptr @yvec_new(i64)
declare void @yvec_push(ptr, ptr)
declare ptr @yvec_get(ptr, i64)
declare i64 @yvec_len(ptr)
declare ptr @yfile_read_to_string(ptr)
declare void @yfile_write(ptr, ptr)
declare i32 @printf(ptr, ...)
declare ptr @malloc(i64)
declare void @free(ptr)
declare void @exit(i32) noreturn
declare void @println(ptr)
declare void @print_int(i32)
declare void @llvm.prefetch.p0(ptr nocapture readonly, i32, i32, i32)

; --- String Constants ---
@.str.0 = private unnamed_addr constant [3 x i8] c"hi\00"
@.str.1 = private unnamed_addr constant [3 x i8] c"hi\00"

@.fmt.sn = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt.s = private unnamed_addr constant [3 x i8] c"%s\00"
@.fmt.d = private unnamed_addr constant [4 x i8] c"%ld\00"

define void @main() #0 {
entry:
  %t1 = call ptr @ystr_new(ptr @.str.0)
  %t2 = call ptr @ystr_new(ptr @.str.1)
  %t3 = load ptr, ptr %t2
  %t4 = call i32 (ptr, ...) @printf(ptr @.fmt.sn, ptr %t3)
  ret void
}

!0 = !{i32 1}
