; ================================================
;  Generated by Y Compiler — LLVM IR Backend
;  Hardware Profile: AVX=true, AVX512=true, L2 Line=64B
; ================================================

target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

attributes #0 = { "target-cpu"="skylake-avx512" "target-features"="+avx512f,+avx512cd,+avx512bw,+avx512dq,+avx512vl" }

; --- Struct Definitions ---
%MyStruct = type { i64, i64 }

; --- Enum Definitions ---

; --- External Runtime Declarations ---
declare ptr @ystr_new(ptr)
declare void @ystr_push(ptr, i8)
declare void @ystr_push_str(ptr, ptr)
declare i1 @ystr_eq_cstr(ptr, ptr)
declare i64 @ystr_len(ptr)
declare i8 @ystr_char_at(ptr, i64)
declare ptr @ystr_clone(ptr)
declare ptr @yvec_new(i64)
declare void @yvec_push(ptr, ptr)
declare ptr @yvec_get(ptr, i64)
declare i64 @yvec_len(ptr)
declare ptr @yfile_read_to_string(ptr)
declare void @yfile_write(ptr, ptr)
declare i32 @printf(ptr, ...)
declare ptr @malloc(i64)
declare void @free(ptr)
declare void @exit(i32) noreturn
declare void @println(ptr)
declare void @print_int(i64)
declare void @llvm.prefetch.p0(ptr nocapture readonly, i32, i32, i32)
declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg)

@.fmt.sn = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.fmt.s = private unnamed_addr constant [3 x i8] c"%s\00"
@.fmt.d = private unnamed_addr constant [4 x i8] c"%ld\00"

define i64 @main() #0 {
entry:
  %s = alloca %MyStruct
  %ptr = alloca ptr
  %val = alloca i64
  %t1 = sext i32 10 to i64
  %t2 = insertvalue %MyStruct undef, i64 %t1, 0
  %t3 = sext i32 20 to i64
  %t4 = insertvalue %MyStruct %t2, i64 %t3, 1
  %t5 = getelementptr %MyStruct, ptr null, i32 1
  %t6 = ptrtoint ptr %t5 to i64
  %t7 = alloca %MyStruct
  store %MyStruct %t4, ptr %t7
  call void @llvm.memcpy.p0.p0.i64(ptr align 8 %s, ptr align 8 %t7, i64 %t6, i1 false)
  %t8 = load %MyStruct, ptr %s
  store ptr %s, ptr %ptr
  %t10 = load ptr, ptr %ptr
  ; lvalue .field2
  %t11 = getelementptr %MyStruct, ptr %t10, i32 0, i32 1
  %t12 = load i64, ptr %t11
  store i64 %t12, ptr %val
  %t13 = load i64, ptr %val
  ret i64 %t13
}

!0 = !{i32 1}
