(** * The packing buffers: every slot the emitted kernel writes is inside the
      `malloc` that was sized for it, and the `malloc` is not one byte larger.

    This is the item `exact_gemm_certificate::TRUST_BOUNDARY` carried as
    `Check::Unchecked` - "the panel buffers' sizes and the scratch tile's
    allocation are not modelled at all" - and it is the one with a history.
    Both of this repository's documented out-of-bounds writes are in exactly
    this arithmetic: the three `ldc` sites in `emit_vnni_threaded_module`,
    observed as `double free or corruption` and found only when
    [ExactGemmTiling.v] forced the `N <= ldc` hypothesis to be STATED; and a
    tile-count over-allocation that changes no answer and was therefore caught
    by the schedule gate and by nothing else.

    ** Why no correctness test can replace this, in either direction.

    An allocation that is too LARGE is invisible: every write lands in memory
    the process owns, every answer is right, and the only symptom is bytes.
    An allocation that is too SMALL corrupts the heap, which surfaces as a
    crash somewhere else entirely, on some shapes, sometimes - the repository
    has that recorded too. Neither is a property of the ANSWER, which is what
    every existing exact-GEMM suite compares.

    ** What is proved.

    - [pack_a_write_is_inside_the_allocation] / [pack_b_write_is_inside_the_allocation]
      - every live `(tile, group, index, half)` the packers write lands below
      the element count the driver allocated.
    - [the_scratch_store_is_inside_the_tile] - the flush's `MR x NR` store,
      addressed as `i * NR + col_of v l`, lands below `SCRATCH_TILE_BYTES / 8`.
    - [the_a_allocation_is_exactly_the_write_set] and its two siblings - the
      LAST slot written is the last slot allocated. This is the half that
      catches an over-allocation, and it is the half no test can see.
    - [one_element_short_overflows_the_a_panel] and its siblings - the
      refutations, so the bounds above are known to be tight rather than
      merely sufficient.
    - [the_stride_is_the_packing_proofs_panel_extent] - the join. The emitted
      stride IS the `kp * (2 * width)` that [ExactGemmPacking]'s
      [panel_is_the_only_solution] quantifies over. Without it this file is an
      arithmetic exercise about numbers that happen to agree with the ones the
      packing proof uses.

    ** What is NOT proved HERE.

    - Nothing about `malloc` FAILING. The emitted driver does not check its
      return value; that is a real gap and it is not this file's.
    - Nothing about the threaded wrapper's `pthread` mechanics - the job
      struct's layout, the spawn/join protocol, or the per-thread private C
      buffer. [ExactGemmKsplit.v] covers what the bands COMPUTE and says
      nothing about how they are dispatched.
    - The sizes are read from [ExactGemmSchedule], which is GENERATED from
      `src/cpu_gemm.rs` and byte-identity-gated, so "the number here is the
      number emitted" is that gate's claim rather than this file's.

    Build:  coqc proofs/ExactGemmAllocation.v      (Rocq 9.1)
*)

From Stdlib Require Import Arith Lia.
Require ExactGemmSchedule.
Require ExactGemmPacking.

Module SCH := ExactGemmSchedule.
Module PK := ExactGemmPacking.

(* ------------------------------------------------------------------ *)
(** ** The sizes, in elements                                          *)
(* ------------------------------------------------------------------ *)

(** The generated byte counts divided by `sizeof(i16)`, unfolded once so every
    proof below is plain arithmetic rather than a division. *)
Lemma panel_a_elems_unfold : forall mtiles kp,
  SCH.panel_a_elems mtiles kp = (mtiles * kp * (2 * SCH.MR))%nat.
Proof.
  intros mtiles kp. unfold SCH.panel_a_elems, SCH.panel_a_bytes, SCH.MR.
  rewrite Nat.div_mul by lia. reflexivity.
Qed.

Lemma panel_b_elems_unfold : forall kp,
  SCH.panel_b_elems kp = (kp * (2 * SCH.NR))%nat.
Proof.
  intros kp. unfold SCH.panel_b_elems, SCH.panel_b_bytes, SCH.NR.
  rewrite Nat.div_mul by lia. reflexivity.
Qed.

(** **THE JOIN.** The emitted A-panel stride is exactly the extent
    [ExactGemmPacking.panel_is_the_only_solution] quantifies over at
    `width = MR`, and one B panel is that extent at `width = NR`.

    Without this the rest of the file proves that some numbers fit inside some
    other numbers. With it, the buffer the driver allocates is the buffer the
    packing proof describes. *)
Theorem the_stride_is_the_packing_proofs_panel_extent : forall kp,
  SCH.panel_a_stride kp = (kp * (2 * PK.MR))%nat
  /\ SCH.panel_b_elems kp = (kp * (2 * PK.NR))%nat.
Proof.
  intros kp. split.
  - unfold SCH.panel_a_stride, PK.MR, SCH.MR. lia.
  - rewrite panel_b_elems_unfold. unfold PK.NR, SCH.NR. lia.
Qed.

(** The A buffer is `mtiles` panels back to back - A is packed ONCE for the
    whole matrix, outside every tile loop, which is what makes packing
    asymptotically free and is pinned as an event order by
    `tests/exact_gemm_packing_schedule.rs`. *)
Theorem the_a_buffer_is_one_panel_per_row_tile : forall mtiles kp,
  SCH.panel_a_elems mtiles kp = (mtiles * SCH.panel_a_stride kp)%nat.
Proof.
  intros mtiles kp. rewrite panel_a_elems_unfold.
  unfold SCH.panel_a_stride, SCH.MR. lia.
Qed.

(* ------------------------------------------------------------------ *)
(** ** The write sets are inside the allocations                       *)
(* ------------------------------------------------------------------ *)

(** Where `pack_a` writes row `i`, half `h` of k-pair group `p`, in the panel
    of row tile `t`. Transcribed from `emit_vnni_pack_a`, whose destination is
    `dbase + (2i + h)` with `dbase = p * (2*MR)`, offset by the driver's
    `panel_index * panel_stride`. *)
Definition a_write (t p i h kp : nat) : nat :=
  (t * SCH.panel_a_stride kp + (p * (2 * SCH.MR) + SCH.slot_a i h))%nat.

Definition b_write (p j h : nat) : nat :=
  (p * (2 * SCH.NR) + SCH.slot_b j h)%nat.

Theorem pack_a_write_is_inside_the_allocation : forall t p i h mtiles kp,
  (t < mtiles)%nat -> (p < kp)%nat -> (i < SCH.MR)%nat -> (h < 2)%nat ->
  (a_write t p i h kp < SCH.panel_a_elems mtiles kp)%nat.
Proof.
  intros t p i h mtiles kp Ht Hp Hi Hh.
  pose proof (PK.pack_a_slot_in_panel i h) as Hs.
  unfold PK.slot_a, PK.MR in Hs.
  specialize (Hs Hi Hh).
  rewrite panel_a_elems_unfold. unfold a_write, SCH.panel_a_stride, SCH.MR in *.
  (* t <= mtiles - 1 and p <= kp - 1, so the whole index is below
     mtiles * kp * 12. *)
  assert (Hts : (t * (kp * 12) <= (mtiles - 1) * (kp * 12))%nat)
    by (apply Nat.mul_le_mono_r; lia).
  assert (Hps : (p * 12 <= (kp - 1) * 12)%nat)
    by (apply Nat.mul_le_mono_r; lia).
  assert (Hm : (1 <= mtiles)%nat) by lia.
  assert (Hk : (1 <= kp)%nat) by lia.
  assert (E1 : ((mtiles - 1) * (kp * 12) = mtiles * kp * 12 - kp * 12)%nat)
    by (rewrite Nat.mul_sub_distr_r; lia).
  assert (E2 : ((kp - 1) * 12 = kp * 12 - 12)%nat)
    by (rewrite Nat.mul_sub_distr_r; lia).
  assert (Hkp12 : (12 <= kp * 12)%nat) by nia.
  assert (Hall : (kp * 12 <= mtiles * kp * 12)%nat) by nia.
  lia.
Qed.

Theorem pack_b_write_is_inside_the_allocation : forall p j h kp,
  (p < kp)%nat -> (j < SCH.NR)%nat -> (h < 2)%nat ->
  (b_write p j h < SCH.panel_b_elems kp)%nat.
Proof.
  intros p j h kp Hp Hj Hh.
  pose proof (PK.pack_b_slot_in_panel j h) as Hs.
  unfold PK.slot_b, PK.NR in Hs. specialize (Hs Hj Hh).
  rewrite panel_b_elems_unfold. unfold b_write, SCH.NR in *.
  assert (Hps : (p * 128 <= (kp - 1) * 128)%nat)
    by (apply Nat.mul_le_mono_r; lia).
  assert (E2 : ((kp - 1) * 128 = kp * 128 - 128)%nat)
    by (rewrite Nat.mul_sub_distr_r; lia).
  assert (H128 : (128 <= kp * 128)%nat) by nia.
  lia.
Qed.

(** The flush's store, addressed as `i * ldc + 16*v + l` with `ldc = NR` when
    the micro-kernel writes the scratch tile. *)
Definition scratch_store (i v l : nat) : nat :=
  (i * SCH.NR + SCH.col_of v l)%nat.

Definition scratch_elems : nat := (SCH.SCRATCH_TILE_BYTES / 8)%nat.

Theorem the_scratch_store_is_inside_the_tile : forall i v l,
  (i < SCH.MR)%nat -> (v < SCH.NRV)%nat -> (l < SCH.LANES)%nat ->
  (scratch_store i v l < scratch_elems)%nat.
Proof.
  intros i v l Hi Hv Hl.
  unfold scratch_store, scratch_elems, SCH.col_of, SCH.SCRATCH_TILE_BYTES,
         SCH.MR, SCH.NR, SCH.NRV, SCH.LANES in *.
  cbn. nia.
Qed.

(* ------------------------------------------------------------------ *)
(** ** The allocations are EXACT, which is the half no test can see    *)
(* ------------------------------------------------------------------ *)

(** The last slot written is the last slot allocated. A buffer one element
    larger passes every correctness test in this repository forever. *)
Theorem the_a_allocation_is_exactly_the_write_set : forall mtiles kp,
  (0 < mtiles)%nat -> (0 < kp)%nat ->
  S (a_write (mtiles - 1) (kp - 1) (SCH.MR - 1) 1 kp)
  = SCH.panel_a_elems mtiles kp.
Proof.
  intros mtiles kp Hm Hk. rewrite panel_a_elems_unfold.
  unfold a_write, SCH.panel_a_stride, SCH.slot_a, SCH.MR.
  assert (E1 : ((mtiles - 1) * (kp * 12) = mtiles * (kp * 12) - kp * 12)%nat)
    by (rewrite Nat.mul_sub_distr_r; lia).
  assert (E2 : ((kp - 1) * 12 = kp * 12 - 12)%nat)
    by (rewrite Nat.mul_sub_distr_r; lia).
  assert (H12 : (12 <= kp * 12)%nat) by nia.
  assert (H3 : (kp * 12 <= mtiles * (kp * 12))%nat) by nia.
  lia.
Qed.

Theorem the_b_allocation_is_exactly_the_write_set : forall kp,
  (0 < kp)%nat ->
  S (b_write (kp - 1) (SCH.NR - 1) 1) = SCH.panel_b_elems kp.
Proof.
  intros kp Hk. rewrite panel_b_elems_unfold.
  unfold b_write, SCH.slot_b, SCH.NR.
  assert (E2 : ((kp - 1) * 128 = kp * 128 - 128)%nat)
    by (rewrite Nat.mul_sub_distr_r; lia).
  assert (H128 : (128 <= kp * 128)%nat) by nia.
  cbn. lia.
Qed.

Theorem the_scratch_tile_is_exactly_the_store_set :
  S (scratch_store (SCH.MR - 1) (SCH.NRV - 1) (SCH.LANES - 1)) = scratch_elems.
Proof. reflexivity. Qed.

(* ------------------------------------------------------------------ *)
(** ** Refutations: the bounds are tight, not merely sufficient        *)
(* ------------------------------------------------------------------ *)

(** One element short and the last write is out of bounds. Stated as the
    refutation of the WEAKENED claim rather than by exhibiting a witness at a
    convenient size, so no choice of `mtiles` and `kp` satisfies it. *)
Theorem one_element_short_overflows_the_a_panel :
  ~ (forall mtiles kp,
        (0 < mtiles)%nat -> (0 < kp)%nat ->
        (a_write (mtiles - 1) (kp - 1) (SCH.MR - 1) 1 kp
         < SCH.panel_a_elems mtiles kp - 1)%nat).
Proof.
  (* `vm_compute` rather than `cbn`: the B slot map divides by 16, and a
     partially-reduced numeral is what `lia` cannot find a witness for. *)
  intros H. specialize (H 1 1 ltac:(lia) ltac:(lia)). vm_compute in H. lia.
Qed.

Theorem one_element_short_overflows_the_b_panel :
  ~ (forall kp, (0 < kp)%nat ->
        (b_write (kp - 1) (SCH.NR - 1) 1 < SCH.panel_b_elems kp - 1)%nat).
Proof.
  intros H. specialize (H 1 ltac:(lia)). vm_compute in H. lia.
Qed.

(** The scratch tile likewise. A tile sized `MR * NR - 1` drops the last
    column of the last row, which is a LIVE position whenever the tile is full
    - so this is a wrong answer as well as an out-of-bounds read. *)
Theorem one_element_short_overflows_the_scratch_tile :
  ~ (scratch_store (SCH.MR - 1) (SCH.NRV - 1) (SCH.LANES - 1)
     < scratch_elems - 1)%nat.
Proof.
  (* `vm_compute`, not `unfold` + `lia`: `scratch_elems` is a division by a
     literal, which `lia` does not evaluate. *)
  vm_compute. lia.
Qed.

(* ------------------------------------------------------------------ *)
(** ** Non-vacuity                                                     *)
(* ------------------------------------------------------------------ *)

(** The three sizes are positive at the shipped schedule, and the write sets
    they bound are not empty. A bound on an empty set is true and worthless,
    and `panel_a_elems 0 0 = 0` is a reachable instance of exactly that. *)
Theorem the_shipped_sizes_are_not_degenerate :
  (0 < SCH.panel_a_elems 1 1)%nat
  /\ (0 < SCH.panel_b_elems 1)%nat
  /\ (0 < scratch_elems)%nat
  /\ SCH.panel_a_elems 1 1 = 12%nat
  /\ SCH.panel_b_elems 1 = 128%nat
  /\ scratch_elems = 384%nat.
Proof. repeat split; vm_compute; lia. Qed.

(** And the join is not vacuous either: the two extents genuinely differ, so
    [the_stride_is_the_packing_proofs_panel_extent] is not one claim written
    twice. *)
Theorem the_two_panel_extents_are_different :
  SCH.panel_a_stride 1 <> SCH.panel_b_elems 1.
Proof. vm_compute. discriminate. Qed.

Print Assumptions the_stride_is_the_packing_proofs_panel_extent.
Print Assumptions the_a_buffer_is_one_panel_per_row_tile.
Print Assumptions pack_a_write_is_inside_the_allocation.
Print Assumptions pack_b_write_is_inside_the_allocation.
Print Assumptions the_scratch_store_is_inside_the_tile.
Print Assumptions the_a_allocation_is_exactly_the_write_set.
Print Assumptions the_b_allocation_is_exactly_the_write_set.
Print Assumptions the_scratch_tile_is_exactly_the_store_set.
Print Assumptions one_element_short_overflows_the_a_panel.
Print Assumptions one_element_short_overflows_the_b_panel.
Print Assumptions one_element_short_overflows_the_scratch_tile.
Print Assumptions the_shipped_sizes_are_not_degenerate.
Print Assumptions the_two_panel_extents_are_different.
