[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "y-lang"
version = "1.0.0"
description = "Python bindings and PyTorch JIT compiler interop for the Y programming language"
readme = "../README.md"
requires-python = ">=3.8"
dependencies = [
    "torch",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "cupy-cuda12x",
]
