#!/usr/bin/env python3
"""Extract circomlib's t=3 Poseidon constants into a Rust source file.

circomlib ships the *optimized* Poseidon parameters (C folded through the MDS,
plus P and the sparse S matrices). Y must use the same layout to produce the
same hash, so we transcribe rather than regenerate: a regenerated constant set
that differs in any way is a different hash function, and interop is the whole
point of this change.
"""
import re
import sys

SRC = "circomlib/circuits/poseidon_constants.circom"
OUT = "src/zk_poseidon_constants.rs"

T = 3
N_ROUNDS_F = 8
N_ROUNDS_P = 57

EXPECT = {
    "C": T * N_ROUNDS_F + N_ROUNDS_P,   # 81
    "M": T * T,                          # 9
    "P": T * T,                          # 9
    "S": N_ROUNDS_P * (T * 2 - 1),       # 285
}

text = open(SRC).read()


def grab(name):
    """Pull the t==3 branch of POSEIDON_<name> and return its hex literals in order."""
    m = re.search(r"function POSEIDON_%s\(t\)\s*\{(.*?)\n\}" % name, text, re.S)
    if not m:
        sys.exit("could not find POSEIDON_%s" % name)
    body = m.group(1)
    b = re.search(r"if \(t==3\)\s*\{(.*?)\n\s*\}", body, re.S)
    if not b:
        sys.exit("no t==3 branch in POSEIDON_%s" % name)
    return re.findall(r"0x[0-9a-fA-F]+", b.group(1))


vals = {}
for name in ("C", "M", "P", "S"):
    got = grab(name)
    if len(got) != EXPECT[name]:
        sys.exit("POSEIDON_%s: expected %d constants, parsed %d"
                 % (name, EXPECT[name], len(got)))
    vals[name] = got
    print("POSEIDON_%s: %d constants" % (name, len(got)))


def emit_flat(name, xs):
    lines = ["pub const POSEIDON_%s_T3: [&str; %d] = [" % (name, len(xs))]
    for x in xs:
        lines.append('    "%s",' % x)
    lines.append("];")
    return "\n".join(lines)


def emit_matrix(name, xs):
    lines = ["pub const POSEIDON_%s_T3: [[&str; 3]; 3] = [" % name]
    for i in range(3):
        row = xs[i * 3:(i + 1) * 3]
        lines.append("    [")
        for x in row:
            lines.append('        "%s",' % x)
        lines.append("    ],")
    lines.append("];")
    return "\n".join(lines)


header = '''//! circomlib-compatible Poseidon parameters for BN254, t=3 (two inputs).
//!
//! GENERATED by `tools/extract_poseidon.py` from
//! `circomlib/circuits/poseidon_constants.circom`. Do not hand-edit: these are
//! not "some constants", they ARE the hash function. Changing one value yields
//! a hash that matches no other implementation, which silently breaks interop
//! with every circomlib-built Merkle tree and commitment.
//!
//! Layout is circomlib's *optimized* Poseidon (Grassi-Khovratovich-Rechberger-
//! Roy-Schofnegger), where the partial rounds fold the MDS into the sparse `S`
//! matrices. `C` is correspondingly pre-folded and has length
//! `t*R_F + R_P = 81`, not `t*(R_F+R_P)`. `M` is the MDS, `P` the change of
//! basis applied once before the partial rounds.
//!
//! Verified against the circomlib test vector in `poseidon_matches_circomlib`.

'''

with open(OUT, "w") as f:
    f.write(header)
    f.write("pub const POSEIDON_T3_ROUNDS_F: usize = %d;\n" % N_ROUNDS_F)
    f.write("pub const POSEIDON_T3_ROUNDS_P: usize = %d;\n\n" % N_ROUNDS_P)
    f.write(emit_flat("C", vals["C"]) + "\n\n")
    f.write(emit_matrix("M", vals["M"]) + "\n\n")
    f.write(emit_matrix("P", vals["P"]) + "\n\n")
    f.write(emit_flat("S", vals["S"]) + "\n")

print("wrote %s" % OUT)
