//! The certificate a compilation carries with the kernel it emitted.
//!
//! `proofs/` is checked once, at build time, against the SHIPPED schedule
//! constants. Its theorems are universally quantified over `M`, `N`, `K` and
//! `nthr`, so every shape is covered - but a user who compiles their own
//! `@ZeroDrift` nest gets a fast kernel and no artifact. "Proof-carrying"
//! described the repository, not the output.
//!
//! This module closes that. When `llvm_emitter` substitutes the exact
//! `vpdpwssd` kernel it renders a `.v` file stating, at THIS compilation's
//! numbers, that the emitted kernel computes the source's dot products - by
//! instantiating [`ExactGemmWhole.the_threaded_gemm_holds_the_source_dot_products`]
//! rather than by re-proving anything. The certificate travels with the `.ll`.
//!
//! # Why this is not paperwork
//!
//! The interesting hypothesis is the LICENCE, `2 * Fl * m^2 <= i32::MAX`. Y
//! decides it in [`crate::zero_drift::VnniExact::max_operand_magnitude`] with
//! **floating-point arithmetic** - a `sqrt` and a `floor` on `f64`. The
//! certificate states it as **exact integer arithmetic over `Z`** and hands it
//! to `coqc`. So emitting the certificate makes the compiler's own
//! floating-point reasoning checkable by an independent integer tool, and a
//! certificate that fails to compile where Y said yes is a real finding rather
//! than a formality.
//!
//! Verified at the boundary before this module was written: at the default
//! interval the certificate is ACCEPTED at `m = 4095` and REFUSED at `m = 4096`
//! - the same one-unit edge `tests/exact_gemm_licence_obligations.rs` finds by
//! exhausting the int16 domain, reproduced here by a different tool.
//!
//! # What the certificate does NOT claim
//!
//! Everything the library files already exclude, and nothing new: `vpdpwssd`'s
//! semantics and the little-endian i32 half-order are definitions pinned on
//! hardware by `tests/cpu_gemm_vnni_micro.rs`; the loop nest's structure is
//! partly extracted (`cpu_gemm::Ix`, `cpu_gemm::CountedLoop`) and partly
//! modelled. The certificate inherits those limits and says so in its header,
//! because a certificate that overstates its scope is worse than none.

/// One substituted exact GEMM, and the numbers its certificate is about.
#[derive(Debug, Clone, PartialEq)]
pub struct Certificate {
    /// The operand magnitude the licence was granted against, as `@bounds`
    /// stated it - a real number.
    pub operand_magnitude: f64,
    /// k-pairs accumulated in int32 between flushes into int64.
    pub flush_k_pairs: u32,
    /// The extent names of the recognised nest, for the header only.
    pub extent_m: String,
    pub extent_n: String,
}

/// The integer bound the certificate is stated at, from the real-valued
/// `@bounds` magnitude.
///
/// **Rounded UP, and the direction matters in both of the places it is used.**
/// The certificate's theorem carries `m` in two roles at once:
///
/// - the LICENCE, `2 * Fl * m^2 <= i32::MAX`, which gets HARDER as `m` grows;
/// - the data hypothesis, `|A[i,k]| <= m`, which gets EASIER as `m` grows.
///
/// So `ceil` is the conservative direction for both: a stricter obligation
/// discharged, over every matrix the declared bound admits. `floor` would be
/// wrong twice - it would licence a wider interval than the source justifies
/// AND state the guarantee over fewer matrices than the source declares.
///
/// This cannot disagree with Y's own licence, and the argument is short enough
/// to write down. Y licenses exactly when `m <= L` where
/// `L = floor(sqrt(i32::MAX / (2*Fl)))` is an integer; `m <= L` with `L`
/// integral gives `ceil(m) <= L`, so the certificate's obligation holds
/// whenever Y granted the licence. It is checked rather than trusted: see
/// `tests/exact_gemm_certificate.rs`.
pub fn integer_bound(magnitude: f64) -> u32 {
    if !magnitude.is_finite() || magnitude <= 0.0 {
        return 0;
    }
    magnitude.ceil() as u32
}

/// Render the certificate for one substituted kernel.
///
/// `source` is a label for the header only - it identifies the compilation to
/// a human and is not read by `coqc`. `stem` is the certificate's own file name
/// without its extension, which `coqc` turns into the module's logical name.
pub fn render(cert: &Certificate, source: &str, stem: &str) -> String {
    let m = integer_bound(cert.operand_magnitude);
    let fl = cert.flush_k_pairs;
    format!(
        r#"(** * EXACT-GEMM CERTIFICATE - GENERATED BY THE Y COMPILER, DO NOT EDIT.

    Source      : {source}
    Matmul      : {em} x {en}
    Operands    : |x| <= {mag} as declared by `@bounds`, certified at the
                  integer bound {m} (rounded UP: see
                  `exact_gemm_certificate::integer_bound`, where the direction
                  is argued for both roles `m` plays)
    Flush       : {fl} k-pairs accumulated in int32 between widenings into int64
    Schedule    : `ExactGemmSchedule.v`, generated from `src/cpu_gemm.rs`

    ** What this file asserts.

    [this_kernel_computes_the_source_dot_products]: for ANY A and B respecting
    the bound declared above, ANY M, N, K, ANY positive thread count, and every
    position of C, the kernel Y emitted for this compilation - packing, the
    register tile's routing, the k-pair loop, the int32 flush, the output
    tiling and the K-split across threads - produces exactly

    <<  sum over k < K of  A[r][k] * B[k][c]  >>

    the naive nest's own value, not a value close to it. Integer addition is
    associative and commutative, so this is an EQUALITY rather than a
    tolerance; that is the whole reason the exactness constraint is worth its
    range.

    ** The compilation-specific obligation.

    [the_licence_holds] is the only thing here that depends on this program.
    `vpdpwssd` accumulates into int32, which wraps silently; the emitted kernel
    is safe exactly when one flush interval of products cannot overflow it:

    <<  2 * {fl} * {m}^2 <= 2147483647  >>

    Y decides that in FLOATING POINT (a `sqrt` and a `floor` on `f64`). This
    file states it over `Z` and lets `coqc` check it, so the two derivations
    are independent. At the default interval the edge is one unit wide - `4095`
    is accepted and `4096` is refused - and a bound Y should have rejected
    makes this file fail to compile rather than certifying anything.

    ** What is NOT claimed, inherited from the library and repeated because a
       certificate that overstates its scope is worse than no certificate.

    - `vpdpwssd`'s semantics and the little-endian order of an i32's two halves
      are DEFINITIONS. No proof over `Z` can supply them;
      `tests/cpu_gemm_vnni_micro.rs` pins them on the real instruction.
    - The emitted loop NEST is partly extracted from one description shared
      with these proofs (`cpu_gemm::Ix`, `cpu_gemm::CountedLoop`) and partly
      modelled. Which loops exist, in what order, and what they call is still
      hand-written.
    - Nothing here is a statement about LLVM, about `clang`, or about the
      machine code either of them produces.

    Check with:

    <<  coqc -Q <dir with proofs/*.v> "" {stem}.v  >>
*)

From Stdlib Require Import ZArith Arith Lia.
Require ExactGemmWhole.
Require ExactGemmMicro.
Require ExactGemmPacking.
Open Scope Z_scope.

Module W := ExactGemmWhole.
Module PK := ExactGemmPacking.

(** The flush interval this compilation emitted. *)
Definition Fl : nat := {fl}.

(** The operand bound this compilation was licensed against. *)
Definition m : Z := {m}.

(** *** THE COMPILATION-SPECIFIC OBLIGATION. *)
Theorem the_licence_holds :
  2 * Z.of_nat Fl * m * m <= ExactGemmMicro.I32MAX.
Proof. unfold Fl, m, ExactGemmMicro.I32MAX. lia. Qed.

(** *** THE CERTIFICATE. *)
Theorem this_kernel_computes_the_source_dot_products :
  forall A B M N K nthr r c,
    (forall i k, Z.abs (A i k) <= m) ->
    (forall k j, Z.abs (B k j) <= m) ->
    (0 < nthr)%nat -> (r < M)%nat -> (c < N)%nat ->
    W.thread_sum A B M N K Fl nthr r c nthr
    = PK.sum_k (fun k => A r k * B k c) K.
Proof.
  intros A B M N K nthr r c HA HB Hn Hr Hc.
  apply (W.the_threaded_gemm_holds_the_source_dot_products
           A B M N K Fl m nthr r c); try assumption.
  - unfold Fl. lia.
  - unfold m. lia.
  - exact the_licence_holds.
Qed.

(** *** Non-vacuity.

    A theorem whose hypotheses cannot be satisfied is true and worthless, and
    that is a reachable failure here rather than a hypothetical one: a negative
    `m` makes `|A[i,k]| <= m` unsatisfiable and the certificate above
    vacuously true. So the certificate exhibits a matrix the declared bound
    admits, and EVALUATES the model on it - at two threads over an uneven
    K-split, which is the case `ExactGemmKsplit.bands_tile` exists for. *)
Definition Acert (i k : nat) : Z := m.
Definition Bcert (k j : nat) : Z := m.

Theorem the_declared_bound_admits_this_matrix :
  (forall i k, Z.abs (Acert i k) <= m) /\ (forall k j, Z.abs (Bcert k j) <= m).
Proof. unfold Acert, Bcert, m. split; intros; compute; discriminate. Qed.

Theorem the_certificate_is_not_vacuous :
  W.thread_sum Acert Bcert 2 3 3 Fl 2 1 2 2 = 3 * m * m.
Proof. vm_compute. reflexivity. Qed.

Print Assumptions the_licence_holds.
Print Assumptions this_kernel_computes_the_source_dot_products.
Print Assumptions the_certificate_is_not_vacuous.
"#,
        source = source,
        em = cert.extent_m,
        en = cert.extent_n,
        mag = cert.operand_magnitude,
        m = m,
        fl = fl,
        stem = module_stem(stem),
    )
}

/// A Coq module name for `stem`, which is the certificate's file name without
/// its extension.
///
/// `coqc` derives the logical name from the file name, so it has to be a legal
/// identifier: alphanumerics and underscores, not starting with a digit. A
/// source called `4-bit gemm.ysu` is a perfectly ordinary file name and an
/// illegal module name, so this is a sanitiser rather than an assertion.
pub fn module_stem(stem: &str) -> String {
    let mut out: String = stem
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    if out.is_empty() || out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The rounding direction, at the values where it decides something.
    #[test]
    fn the_integer_bound_rounds_up() {
        assert_eq!(integer_bound(1024.0), 1024);
        assert_eq!(integer_bound(1024.5), 1025);
        assert_eq!(integer_bound(0.0), 0);
        // A magnitude below 1 is refused by `VnniExact::license` before it can
        // reach here; `0` is the honest answer rather than a rounded-up `1`,
        // which would certify a bound the source never stated.
        assert_eq!(integer_bound(f64::NAN), 0);
    }

    /// `ceil` cannot turn a licensed magnitude into an unlicensed integer
    /// bound. The argument is in `integer_bound`'s doc comment; this is the
    /// check, over every interval the scheme admits.
    #[test]
    fn rounding_up_never_breaks_a_licence_y_granted() {
        for shift in 0..12u32 {
            let scheme = crate::zero_drift::VnniExact::new(1u32 << shift).unwrap();
            let limit = scheme.max_operand_magnitude();
            for probe in [limit, limit - 0.5, limit - 1.0, 1.0, 2.5] {
                if probe < 1.0 || scheme.license(probe).is_err() {
                    continue;
                }
                let m = u64::from(integer_bound(probe));
                let fl = u64::from(scheme.flush_k_pairs);
                assert!(
                    2 * fl * m * m <= i32::MAX as u64,
                    "ceil({probe}) = {m} breaks the licence at flush {fl}, which \
                     `integer_bound`'s argument says is impossible"
                );
            }
        }
    }

    #[test]
    fn a_module_stem_is_a_legal_coq_identifier() {
        assert_eq!(module_stem("gemm"), "gemm");
        assert_eq!(module_stem("4bit-gemm"), "_4bit_gemm");
        assert_eq!(module_stem(""), "_");
    }
}
