// ============================================================
//  Y  —  AMD ROCm / HIP Target Emitter Pass
//  rocm_emitter.rs
//
//  Translates Y Language AST and IR into GCN / CDNA ISA and HIP
//  assembly instructions targeting AMD Instinct (MI200/MI300) and
//  RDNA3 GPUs (e.g. v_mfma_f32_16x16x16f16, s_barrier, wave64).
// ============================================================

#![allow(dead_code)]

use crate::ast::*;
use crate::sentinel::HardwareProfile;

pub struct RocmEmitter {
    pub code: String,
    indent_level: usize,
    temp_reg_counter: usize,
}

impl RocmEmitter {
    pub fn new() -> Self {
        RocmEmitter {
            code: String::new(),
            indent_level: 0,
            temp_reg_counter: 0,
        }
    }

    fn indent(&mut self) {
        for _ in 0..self.indent_level {
            self.code.push_str("    ");
        }
    }

    fn new_vgpr(&mut self) -> String {
        let reg = format!("v{}", self.temp_reg_counter);
        self.temp_reg_counter += 1;
        reg
    }

    /// Emits complete AMD GCN/CDNA assembly for a Program.
    pub fn emit_program(&mut self, prog: &Program, _hw_profile: &HardwareProfile) -> String {
        self.code.clear();
        self.code.push_str("// AMD ROCm / CDNA GCN Assembly Output generated by Y Compiler\n");
        self.code.push_str(".text\n");
        self.code.push_str(".global ");
        self.code.push_str(".amdgpu_target \"amdgcn-amd-amdhsa--gfx940\"\n\n");

        for item in &prog.items {
            if let Item::Kernel(kernel) = item {
                self.emit_kernel(kernel, _hw_profile);
            }
        }

        self.code.clone()
    }

    fn emit_kernel(&mut self, kernel: &KernelDecl, _hw_profile: &HardwareProfile) {
        self.code.push_str(&format!(".amdgpu_hsa_kernel {}\n", kernel.name));
        self.code.push_str(&format!("{}:\n", kernel.name));
        self.indent_level += 1;

        // Wavefront initialization (wave64 indexing)
        self.indent();
        self.code.push_str("; Compute global thread ID: s_load_dword & v_add_co_u32\n");
        self.indent();
        self.code.push_str("v_add_co_u32 v0, vcc, v0, s0\n");

        self.emit_block(&kernel.body);

        self.indent();
        self.code.push_str("s_endpgm\n\n");
        self.indent_level -= 1;
    }

    fn emit_block(&mut self, block: &Block) {
        for stmt in &block.stmts {
            self.emit_stmt(stmt);
        }
    }

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let { name, init: Some(expr), .. } => {
                let src_reg = self.emit_expr(expr);
                self.indent();
                self.code.push_str(&format!("v_mov_b32 {}, {}\n", name, src_reg));
            }
            Stmt::Expr(expr) => {
                self.emit_expr(expr);
            }
            Stmt::For { loop_var, start, end, body, .. } => {
                let start_reg = self.emit_expr(start);
                let end_reg = self.emit_expr(end);
                self.indent();
                self.code.push_str(&format!("v_mov_b32 {}, {}\n", loop_var, start_reg));
                let label_start = format!(".L_loop_start_{}", loop_var);
                let label_end = format!(".L_loop_end_{}", loop_var);
                self.code.push_str(&format!("{}:\n", label_start));

                self.indent_level += 1;
                self.emit_block(body);
                self.indent();
                self.code.push_str(&format!("v_add_co_u32 {}, vcc, 1, {}\n", loop_var, loop_var));
                self.indent();
                self.code.push_str(&format!("v_cmp_ge_u32 vcc, {}, {}\n", loop_var, end_reg));
                self.indent();
                self.code.push_str(&format!("s_cbranch_vccnz {}\n", label_end));
                self.indent();
                self.code.push_str(&format!("s_branch {}\n", label_start));
                self.indent_level -= 1;

                self.code.push_str(&format!("{}:\n", label_end));
            }
            _ => {}
        }
    }

    fn emit_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::IntLit(val, _) => {
                let dst = self.new_vgpr();
                self.indent();
                self.code.push_str(&format!("v_mov_b32 {}, {}\n", dst, val));
                dst
            }
            Expr::FloatLit(val, _) => {
                let dst = self.new_vgpr();
                self.indent();
                self.code.push_str(&format!("v_mov_b32 {}, {}\n", dst, val));
                dst
            }
            Expr::Ident(name, _) => name.clone(),
            Expr::BinaryOp { op, left, right, .. } => {
                let l_reg = self.emit_expr(left);
                let r_reg = self.emit_expr(right);
                let dst = self.new_vgpr();
                self.indent();
                match op {
                    BinaryOp::Add => self.code.push_str(&format!("v_add_f32 {}, {}, {}\n", dst, l_reg, r_reg)),
                    BinaryOp::Sub => self.code.push_str(&format!("v_sub_f32 {}, {}, {}\n", dst, l_reg, r_reg)),
                    BinaryOp::Mul => self.code.push_str(&format!("v_mul_f32 {}, {}, {}\n", dst, l_reg, r_reg)),
                    BinaryOp::Div => self.code.push_str(&format!("v_rcp_f32 {}, {}; v_mul_f32 {}, {}, {}\n", dst, r_reg, dst, l_reg, dst)),
                    _ => self.code.push_str(&format!("v_add_f32 {}, {}, {}\n", dst, l_reg, r_reg)),
                }
                dst
            }
            Expr::Call { func, args, .. } => {
                if let Expr::Ident(name, _) = &**func {
                    if name == "mfma_16x16x16" && args.len() == 3 {
                        let a = self.emit_expr(&args[0]);
                        let b = self.emit_expr(&args[1]);
                        let c = self.emit_expr(&args[2]);
                        let dst = self.new_vgpr();
                        self.indent();
                        self.code.push_str(&format!("v_mfma_f32_16x16x16f16 {}, {}, {}, {}\n", dst, a, b, c));
                        dst
                    } else if name == "barrier" {
                        self.indent();
                        self.code.push_str("s_barrier\n");
                        "v0".into()
                    } else {
                        self.new_vgpr()
                    }
                } else {
                    self.new_vgpr()
                }
            }
            _ => self.new_vgpr(),
        }
    }
}
