//! Groth16 on-chain verifier generation.
//!
//! A proof nobody can check is not worth producing, and on Ethereum "check"
//! means a Solidity contract calling the BN254 precompiles. This module turns a
//! verifying key into that contract.
//!
//! It deliberately depends on nothing. The verifying key arrives as decimal
//! strings, so the shipping `Y` binary still links no cryptography, and the
//! same function serves a key produced by arkworks, by snarkjs, or by anything
//! else that can print field elements.
//!
//! ## The G2 coordinate trap
//!
//! An element of `Fq2` is `c0 + c1*u`. Mathematically, and in every library
//! API, `c0` comes first. The EVM's pairing precompile (address `0x08`) takes
//! the **imaginary part first**: a G2 point is encoded `x.c1, x.c0, y.c1,
//! y.c0`.
//!
//! So the generated contract stores G2 constants already swapped, and
//! [`Groth16VerifyingKey`] takes them in normal `(c0, c1)` order and does the
//! swap here, once, where it can be commented. Getting this wrong produces a
//! contract that compiles, deploys, costs full gas and rejects every valid
//! proof - there is no type error and no revert to point at it. It is the
//! single most common bug in hand-written verifiers, which is why
//! `tests/zk_solidity_verifier.rs` runs the generated contract on a real EVM
//! rather than string-matching it.

/// A Groth16 verifying key, every coordinate a decimal string.
///
/// G2 coordinates are in mathematical order - `[c0, c1]` - matching what
/// arkworks and snarkjs hand you. The EVM's reversed order is applied during
/// emission.
#[derive(Clone, Debug)]
pub struct Groth16VerifyingKey {
    /// `alpha` in G1: `[x, y]`.
    pub alpha_g1: [String; 2],
    /// `beta` in G2: `[[x_c0, x_c1], [y_c0, y_c1]]`.
    pub beta_g2: [[String; 2]; 2],
    /// `gamma` in G2.
    pub gamma_g2: [[String; 2]; 2],
    /// `delta` in G2.
    pub delta_g2: [[String; 2]; 2],
    /// `gamma_abc_g1` / `IC`: one G1 point per public input, plus a leading
    /// constant term. Length is therefore `num_public_inputs + 1`.
    pub ic: Vec<[String; 2]>,
}

impl Groth16VerifyingKey {
    /// Number of public inputs this key verifies against.
    pub fn num_public_inputs(&self) -> usize {
        self.ic.len().saturating_sub(1)
    }
}

/// BN254's base field modulus `q`, used to negate a G1 point.
///
/// Note this is `q`, the field the curve coordinates live in - NOT `r`, the
/// scalar field the circuit computes in. They differ, they are both 254 bits,
/// and swapping them yields a verifier that is wrong only sometimes.
const BASE_FIELD_Q: &str =
    "21888242871839275222246405745257275088696311157297823662689037894645226208583";

/// BN254's scalar field modulus `r`. Public inputs must be reduced modulo this.
const SCALAR_FIELD_R: &str =
    "21888242871839275222246405745257275088548364400416034343698204186575808495617";

/// Renders a self-contained Solidity Groth16 verifier for `vk`.
///
/// The contract exposes:
///
/// ```solidity
/// function verifyProof(
///     uint[2] memory a,
///     uint[2][2] memory b,
///     uint[2] memory c,
///     uint[N] memory input
/// ) public view returns (bool)
/// ```
///
/// with `N = vk.num_public_inputs()`, and the same argument shape snarkjs
/// emits, so existing tooling and front-ends work unchanged.
pub fn emit_groth16_verifier(vk: &Groth16VerifyingKey, contract_name: &str) -> String {
    let n = vk.num_public_inputs();
    let mut s = String::new();

    s.push_str("// SPDX-License-Identifier: GPL-3.0\n");
    s.push_str("//\n");
    s.push_str("// Generated by the Y compiler. Do not edit.\n");
    s.push_str("//\n");
    s.push_str("// Groth16 verifier over BN254, using the EVM precompiles at 0x06 (G1 add),\n");
    s.push_str("// 0x07 (G1 scalar multiply) and 0x08 (pairing check).\n");
    s.push_str("//\n");
    s.push_str("// G2 constants below are stored with the IMAGINARY part first, which is the\n");
    s.push_str("// order precompile 0x08 expects. That is the reverse of the (c0, c1) order\n");
    s.push_str("// every library reports them in. It is not a typo.\n");
    s.push_str("pragma solidity >=0.7.0 <0.9.0;\n\n");

    // ---- pairing library ----
    s.push_str("library Pairing {\n");
    s.push_str("    struct G1Point { uint X; uint Y; }\n");
    s.push_str("    // Encoding order is EVM order: X[0] is the imaginary coefficient.\n");
    s.push_str("    struct G2Point { uint[2] X; uint[2] Y; }\n\n");

    s.push_str(&format!("    uint constant Q = {};\n\n", BASE_FIELD_Q));

    s.push_str("    /// The additive inverse of a G1 point.\n");
    s.push_str("    function negate(G1Point memory p) internal pure returns (G1Point memory) {\n");
    s.push_str("        if (p.X == 0 && p.Y == 0) return G1Point(0, 0);\n");
    s.push_str("        return G1Point(p.X, Q - (p.Y % Q));\n");
    s.push_str("    }\n\n");

    s.push_str("    function addition(G1Point memory p1, G1Point memory p2)\n");
    s.push_str("        internal view returns (G1Point memory r)\n    {\n");
    s.push_str("        uint[4] memory input;\n");
    s.push_str("        input[0] = p1.X; input[1] = p1.Y;\n");
    s.push_str("        input[2] = p2.X; input[3] = p2.Y;\n");
    s.push_str("        bool ok;\n");
    s.push_str("        assembly { ok := staticcall(sub(gas(), 2000), 6, input, 0x80, r, 0x40) }\n");
    s.push_str("        require(ok, \"bn254-add-failed\");\n");
    s.push_str("    }\n\n");

    s.push_str("    function scalarMul(G1Point memory p, uint s)\n");
    s.push_str("        internal view returns (G1Point memory r)\n    {\n");
    s.push_str("        uint[3] memory input;\n");
    s.push_str("        input[0] = p.X; input[1] = p.Y; input[2] = s;\n");
    s.push_str("        bool ok;\n");
    s.push_str("        assembly { ok := staticcall(sub(gas(), 2000), 7, input, 0x60, r, 0x40) }\n");
    s.push_str("        require(ok, \"bn254-mul-failed\");\n");
    s.push_str("    }\n\n");

    s.push_str("    /// True when the product of the pairings of each (p1[i], p2[i]) is one.\n");
    s.push_str("    function pairingCheck(G1Point[] memory p1, G2Point[] memory p2)\n");
    s.push_str("        internal view returns (bool)\n    {\n");
    s.push_str("        require(p1.length == p2.length, \"bn254-length-mismatch\");\n");
    s.push_str("        uint n = p1.length;\n");
    s.push_str("        uint[] memory input = new uint[](n * 6);\n");
    s.push_str("        for (uint i = 0; i < n; i++) {\n");
    s.push_str("            input[i * 6 + 0] = p1[i].X;\n");
    s.push_str("            input[i * 6 + 1] = p1[i].Y;\n");
    s.push_str("            input[i * 6 + 2] = p2[i].X[0];\n");
    s.push_str("            input[i * 6 + 3] = p2[i].X[1];\n");
    s.push_str("            input[i * 6 + 4] = p2[i].Y[0];\n");
    s.push_str("            input[i * 6 + 5] = p2[i].Y[1];\n");
    s.push_str("        }\n");
    s.push_str("        uint[1] memory out;\n");
    s.push_str("        bool ok;\n");
    s.push_str("        assembly {\n");
    s.push_str("            ok := staticcall(sub(gas(), 2000), 8, add(input, 0x20), mul(mload(input), 0x20), out, 0x20)\n");
    s.push_str("        }\n");
    s.push_str("        require(ok, \"bn254-pairing-failed\");\n");
    s.push_str("        return out[0] != 0;\n");
    s.push_str("    }\n");
    s.push_str("}\n\n");

    // ---- verifier ----
    s.push_str(&format!("contract {} {{\n", contract_name));
    s.push_str("    using Pairing for *;\n\n");
    s.push_str(&format!("    uint constant SCALAR_FIELD = {};\n\n", SCALAR_FIELD_R));

    s.push_str("    struct VerifyingKey {\n");
    s.push_str("        Pairing.G1Point alpha1;\n");
    s.push_str("        Pairing.G2Point beta2;\n");
    s.push_str("        Pairing.G2Point gamma2;\n");
    s.push_str("        Pairing.G2Point delta2;\n");
    s.push_str("        Pairing.G1Point[] IC;\n");
    s.push_str("    }\n\n");

    s.push_str("    function verifyingKey() internal pure returns (VerifyingKey memory vk) {\n");
    s.push_str(&format!(
        "        vk.alpha1 = Pairing.G1Point({}, {});\n",
        vk.alpha_g1[0], vk.alpha_g1[1]
    ));
    for (name, p) in [
        ("beta2", &vk.beta_g2),
        ("gamma2", &vk.gamma_g2),
        ("delta2", &vk.delta_g2),
    ] {
        // (c0, c1) in, (c1, c0) out - see the module comment.
        s.push_str(&format!(
            "        vk.{} = Pairing.G2Point(\n            [{}, {}],\n            [{}, {}]\n        );\n",
            name, p[0][1], p[0][0], p[1][1], p[1][0]
        ));
    }
    s.push_str(&format!(
        "        vk.IC = new Pairing.G1Point[]({});\n",
        vk.ic.len()
    ));
    for (i, p) in vk.ic.iter().enumerate() {
        s.push_str(&format!(
            "        vk.IC[{}] = Pairing.G1Point({}, {});\n",
            i, p[0], p[1]
        ));
    }
    s.push_str("    }\n\n");

    s.push_str("    /// Returns true when `a`, `b`, `c` prove the statement fixed by `input`.\n");
    s.push_str("    ///\n");
    s.push_str("    /// `b` is the proof's G2 element, and like the verifying key's G2 constants\n");
    s.push_str("    /// it is given IMAGINARY PART FIRST: `[[x.c1, x.c0], [y.c1, y.c0]]`. This is\n");
    s.push_str("    /// the same calldata layout snarkjs produces, so its exported callData and\n");
    s.push_str("    /// front-end helpers work against this contract unchanged.\n");
    s.push_str("    function verifyProof(\n");
    s.push_str("        uint[2] memory a,\n");
    s.push_str("        uint[2][2] memory b,\n");
    s.push_str("        uint[2] memory c,\n");
    s.push_str(&format!("        uint[{}] memory input\n", n));
    s.push_str("    ) public view returns (bool) {\n");
    s.push_str("        VerifyingKey memory vk = verifyingKey();\n");
    s.push_str("        require(vk.IC.length == input.length + 1, \"verifier-bad-ic-length\");\n\n");
    s.push_str("        // vk_x = IC[0] + sum(input[i] * IC[i+1])\n");
    s.push_str("        Pairing.G1Point memory vk_x = vk.IC[0];\n");
    s.push_str(&format!("        for (uint i = 0; i < {}; i++) {{\n", n));
    s.push_str("            // A public input at or above the scalar field modulus is not a\n");
    s.push_str("            // field element; rejecting it stops a caller re-presenting the\n");
    s.push_str("            // same proof under a congruent input.\n");
    s.push_str("            require(input[i] < SCALAR_FIELD, \"verifier-input-out-of-range\");\n");
    s.push_str("            vk_x = Pairing.addition(vk_x, Pairing.scalarMul(vk.IC[i + 1], input[i]));\n");
    s.push_str("        }\n\n");
    s.push_str("        Pairing.G1Point[] memory p1 = new Pairing.G1Point[](4);\n");
    s.push_str("        Pairing.G2Point[] memory p2 = new Pairing.G2Point[](4);\n\n");
    s.push_str("        // e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1\n");
    s.push_str("        p1[0] = Pairing.negate(Pairing.G1Point(a[0], a[1]));\n");
    s.push_str("        p2[0] = Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]);\n");
    s.push_str("        p1[1] = vk.alpha1;    p2[1] = vk.beta2;\n");
    s.push_str("        p1[2] = vk_x;         p2[2] = vk.gamma2;\n");
    s.push_str("        p1[3] = Pairing.G1Point(c[0], c[1]);\n");
    s.push_str("        p2[3] = vk.delta2;\n\n");
    s.push_str("        return Pairing.pairingCheck(p1, p2);\n");
    s.push_str("    }\n");
    s.push_str("}\n");

    s
}

// ───────────────────────── snarkjs verification_key.json ─────────────────────────

use crate::mini_json::{Json, P};

/// Reads a snarkjs `verification_key.json` into a [`Groth16VerifyingKey`].
///
/// snarkjs stores G1 as `[x, y, z]` and G2 as `[[x_c0, x_c1], [y_c0, y_c1],
/// [z_c0, z_c1]]` - affine with a trailing `z` of 1 that is dropped here, and
/// the `Fq2` pairs already in `(c0, c1)` order, which is the order this module
/// wants. The EVM swap happens once, at emission.
///
/// `protocol` and `curve` are checked rather than assumed. A PLONK or
/// BLS12-381 key has the same field names and would otherwise produce a
/// confident, deployable, permanently-broken verifier.
pub fn parse_snarkjs_vkey(json: &str) -> Result<Groth16VerifyingKey, String> {
    let root = P { b: json.as_bytes(), i: 0 }.value()?;

    if let Some(Json::Str(p)) = root.get("protocol") {
        if p != "groth16" {
            return Err(format!(
                "verification key is for protocol {:?}; this generator emits a Groth16 verifier \
                 and would produce a contract that can never verify anything for {:?}",
                p, p
            ));
        }
    }
    if let Some(Json::Str(c)) = root.get("curve") {
        let c_lower = c.to_lowercase();
        if c_lower != "bn128" && c_lower != "bn254" && c_lower != "altbn128" {
            return Err(format!(
                "verification key is over curve {:?}; the EVM precompiles at 0x06/0x07/0x08 \
                 implement BN254 only",
                c
            ));
        }
    }

    let g1 = |key: &str| -> Result<[String; 2], String> {
        let a = root
            .get(key)
            .and_then(Json::arr)
            .ok_or_else(|| format!("missing or malformed {:?}", key))?;
        if a.len() < 2 {
            return Err(format!("{:?} needs at least x and y", key));
        }
        Ok([
            a[0].scalar().ok_or_else(|| format!("{:?}.x is not a scalar", key))?,
            a[1].scalar().ok_or_else(|| format!("{:?}.y is not a scalar", key))?,
        ])
    };

    let g2 = |key: &str| -> Result<[[String; 2]; 2], String> {
        let a = root
            .get(key)
            .and_then(Json::arr)
            .ok_or_else(|| format!("missing or malformed {:?}", key))?;
        if a.len() < 2 {
            return Err(format!("{:?} needs at least x and y", key));
        }
        let pair = |j: &Json, what: &str| -> Result<[String; 2], String> {
            let v = j.arr().ok_or_else(|| format!("{:?}.{} is not a pair", key, what))?;
            if v.len() < 2 {
                return Err(format!("{:?}.{} needs both Fq2 coefficients", key, what));
            }
            Ok([
                v[0].scalar().ok_or_else(|| format!("{:?}.{}.c0 is not a scalar", key, what))?,
                v[1].scalar().ok_or_else(|| format!("{:?}.{}.c1 is not a scalar", key, what))?,
            ])
        };
        Ok([pair(&a[0], "x")?, pair(&a[1], "y")?])
    };

    let ic_raw = root
        .get("IC")
        .and_then(Json::arr)
        .ok_or("missing or malformed \"IC\"")?;
    let mut ic = Vec::with_capacity(ic_raw.len());
    for (i, p) in ic_raw.iter().enumerate() {
        let v = p.arr().ok_or_else(|| format!("IC[{}] is not a point", i))?;
        if v.len() < 2 {
            return Err(format!("IC[{}] needs x and y", i));
        }
        ic.push([
            v[0].scalar().ok_or_else(|| format!("IC[{}].x is not a scalar", i))?,
            v[1].scalar().ok_or_else(|| format!("IC[{}].y is not a scalar", i))?,
        ]);
    }
    if ic.is_empty() {
        return Err("\"IC\" is empty; a Groth16 key always has at least one point".into());
    }

    let vk = Groth16VerifyingKey {
        alpha_g1: g1("vk_alpha_1")?,
        beta_g2: g2("vk_beta_2")?,
        gamma_g2: g2("vk_gamma_2")?,
        delta_g2: g2("vk_delta_2")?,
        ic,
    };

    // Cross-check against the key's own claim, when it makes one.
    if let Some(n) = root.get("nPublic").and_then(Json::scalar) {
        if let Ok(n) = n.parse::<usize>() {
            if n != vk.num_public_inputs() {
                return Err(format!(
                    "key says nPublic = {} but IC has {} points (expected {})",
                    n,
                    vk.ic.len(),
                    n + 1
                ));
            }
        }
    }
    Ok(vk)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dummy_vk(n_public: usize) -> Groth16VerifyingKey {
        let g2 = |a: &str, b: &str, c: &str, d: &str| {
            [[a.to_string(), b.to_string()], [c.to_string(), d.to_string()]]
        };
        Groth16VerifyingKey {
            alpha_g1: ["1".into(), "2".into()],
            beta_g2: g2("3", "4", "5", "6"),
            gamma_g2: g2("7", "8", "9", "10"),
            delta_g2: g2("11", "12", "13", "14"),
            ic: (0..=n_public)
                .map(|i| [format!("{}", 100 + i), format!("{}", 200 + i)])
                .collect(),
        }
    }

    /// The swap is the whole point, so assert on it directly rather than
    /// trusting that a downstream test would notice.
    #[test]
    fn g2_constants_are_emitted_imaginary_part_first() {
        let src = emit_groth16_verifier(&dummy_vk(1), "V");
        // beta_g2 went in as [[3, 4], [5, 6]] and must come out [4, 3], [6, 5].
        assert!(
            src.contains("vk.beta2 = Pairing.G2Point(\n            [4, 3],\n            [6, 5]\n        );"),
            "beta2 was not swapped into EVM order:\n{}",
            src
        );
    }

    #[test]
    fn input_array_is_sized_to_the_public_inputs() {
        for n in [1usize, 2, 5] {
            let src = emit_groth16_verifier(&dummy_vk(n), "V");
            assert!(src.contains(&format!("uint[{}] memory input", n)));
            assert!(src.contains(&format!("vk.IC = new Pairing.G1Point[]({});", n + 1)));
        }
    }

    #[test]
    fn contract_name_is_honoured() {
        let src = emit_groth16_verifier(&dummy_vk(1), "MyCircuitVerifier");
        assert!(src.contains("contract MyCircuitVerifier {"));
    }

    const SNARKJS_VKEY: &str = r#"{
     "protocol": "groth16",
     "curve": "bn128",
     "nPublic": 2,
     "vk_alpha_1": ["11","12","1"],
     "vk_beta_2": [["21","22"],["23","24"],["1","0"]],
     "vk_gamma_2": [["31","32"],["33","34"],["1","0"]],
     "vk_delta_2": [["41","42"],["43","44"],["1","0"]],
     "vk_alphabeta_12": [[["9","9"],["9","9"],["9","9"]]],
     "IC": [["51","52","1"],["53","54","1"],["55","56","1"]]
    }"#;

    #[test]
    fn reads_a_snarkjs_verification_key() {
        let vk = parse_snarkjs_vkey(SNARKJS_VKEY).expect("parse");
        assert_eq!(vk.num_public_inputs(), 2);
        assert_eq!(vk.alpha_g1, ["11".to_string(), "12".to_string()]);
        // snarkjs stores Fq2 as (c0, c1); we keep that order and swap on emit.
        assert_eq!(vk.beta_g2[0], ["21".to_string(), "22".to_string()]);
        assert_eq!(vk.ic.len(), 3);
        assert_eq!(vk.ic[2], ["55".to_string(), "56".to_string()]);

        let src = emit_groth16_verifier(&vk, "V");
        assert!(src.contains("[22, 21]"), "beta2.x should be swapped on emit");
        assert!(src.contains("uint[2] memory input"));
    }

    /// A key for another proof system has the same field names and would
    /// otherwise yield a deployable contract that can never verify anything.
    #[test]
    fn rejects_a_non_groth16_or_non_bn254_key() {
        let plonk = SNARKJS_VKEY.replace("groth16", "plonk");
        let err = parse_snarkjs_vkey(&plonk).expect_err("plonk key must be refused");
        assert!(err.contains("plonk"), "error should name the protocol: {}", err);

        let bls = SNARKJS_VKEY.replace("bn128", "bls12381");
        let err = parse_snarkjs_vkey(&bls).expect_err("bls12-381 key must be refused");
        assert!(err.contains("BN254"), "error should name the supported curve: {}", err);
    }

    /// `nPublic` disagreeing with `IC` means the file is not internally
    /// consistent; guessing which one is right would size `verifyProof`'s input
    /// array wrongly and break every call.
    #[test]
    fn rejects_inconsistent_public_input_count() {
        let bad = SNARKJS_VKEY.replace("\"nPublic\": 2", "\"nPublic\": 5");
        let err = parse_snarkjs_vkey(&bad).expect_err("must reject");
        assert!(err.contains("nPublic"), "{}", err);
    }
}
