/* ============================================== */
/*  Generated by Y Compiler — C11 Backend   */
/* ============================================== */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>

/* ── Y Runtime: String ──────────────────── */
typedef struct {
    char*  data;
    size_t len;
    size_t cap;
} YStr;

static YStr ystr_new(const char* s) {
    size_t len = s ? strlen(s) : 0;
    size_t cap = len + 1;
    char* data = (char*)malloc(cap);
    if (s) memcpy(data, s, len);
    data[len] = '\0';
    return (YStr){ data, len, cap };
}

static YStr ystr_clone(const YStr* s) {
    return ystr_new(s->data);
}

static void ystr_push(YStr* s, char c) {
    if (s->len + 1 >= s->cap) {
        s->cap = s->cap * 2 + 1;
        s->data = (char*)realloc(s->data, s->cap);
    }
    s->data[s->len++] = c;
    s->data[s->len] = '\0';
}

static void ystr_push_str(YStr* s, const YStr* other) {
    size_t olen = other->len;
    while (s->len + olen >= s->cap) {
        s->cap = s->cap * 2 + 1;
        s->data = (char*)realloc(s->data, s->cap);
    }
    memcpy(s->data + s->len, other->data, olen);
    s->len += olen;
    s->data[s->len] = '\0';
}

static bool ystr_eq(const YStr* a, const YStr* b) {
    if (a->len != b->len) return false;
    return memcmp(a->data, b->data, a->len) == 0;
}

static bool ystr_eq_cstr(const YStr* a, const char* b) {
    return strcmp(a->data, b) == 0;
}
static bool ystr_eq_val(const YStr* a, const YStr* b) {
    if (a->len != b->len) return false;
    return memcmp(a->data, b->data, a->len) == 0;
}

static char ystr_char_at(const YStr* s, size_t i) {
    return (i < s->len) ? s->data[i] : '\0';
}

static void ystr_free(YStr* s) {
    free(s->data);
    s->data = NULL;
    s->len = 0;
    s->cap = 0;
}

/* ── Y Runtime: Dynamic Vector ──────────── */
typedef struct {
    void*  data;
    size_t len;
    size_t cap;
    size_t elem_size;
} YVec;

static YVec yvec_new(size_t elem_size) {
    return (YVec){ NULL, 0, 0, elem_size };
}

static void yvec_push(YVec* v, const void* elem) {
    if (v->len >= v->cap) {
        v->cap = v->cap == 0 ? 8 : v->cap * 2;
        v->data = realloc(v->data, v->cap * v->elem_size);
    }
    memcpy((char*)v->data + v->len * v->elem_size, elem, v->elem_size);
    v->len++;
}

static void* yvec_get(const YVec* v, size_t i) {
    return (char*)v->data + i * v->elem_size;
}

static char yvec_get_char(const YVec* v, size_t i) {
    return *((char*)yvec_get(v, i));
}

static size_t yvec_len(const YVec* v) {
    return v->len;
}

static size_t ystr_len(const YStr* s) {
    return s->len;
}

static void yvec_free(YVec* v) {
    free(v->data);
    v->data = NULL;
    v->len = 0;
    v->cap = 0;
}

/* ── Y Runtime: Print ───────────────────── */
static void yprint_str(const YStr* s) {
    printf("%s", s->data);
}

static void yprint_int(int64_t v) {
    printf("%lld", (long long)v);
}

static void yprint_float(double v) {
    printf("%f", v);
}

static void yprintln_str(const YStr* s) {
    printf("%s\n", s->data);
}

/* ── Y Runtime: File I/O ────────────────── */
static YStr yfile_read_to_string(const YStr* path_str) {
    const char* path = path_str->data;
    FILE* f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Error: Cannot open file '%s'\n", path);
        exit(1);
    }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(len + 1);
    fread(buf, 1, len, f);
    buf[len] = '\0';
    fclose(f);
    YStr result = { buf, (size_t)len, (size_t)(len + 1) };
    return result;
}

static void yfile_write(const YStr* path_str, const YStr* content) {
    const char* path = path_str->data;
    FILE* f = fopen(path, "wb");
    if (!f) {
        fprintf(stderr, "Error: Cannot write file '%s'\n", path);
        exit(1);
    }
    fwrite(content->data, 1, content->len, f);
    fclose(f);
}

/* ── User Code ───────────────────────────────── */


void mma_sync_bool_8x8(int32_t a_ptr, int32_t b_ptr, int32_t c_ptr);
void bcp_threshold_kernel(int32_t acc_ptr, int32_t n_clauses);
void main(void);

/* @ptx_emit */
void mma_sync_bool_8x8(int32_t a_ptr, int32_t b_ptr, int32_t c_ptr) {
    /* chisel block — PTX inline assembly */
    #if defined(__NVCC__) || defined(__CUDACC__)
    {
        asm volatile ("wmma.load.a.sync.aligned.row.m16n16k16.s8 {%r0,%r1,%r2,%r3}, [%rd0], 16;");
        asm volatile ("wmma.load.b.sync.aligned.col.m16n16k16.s8 {%r4,%r5,%r6,%r7}, [%rd1], 16;");
        asm volatile ("wmma.load.c.sync.aligned.m16n16k16.s32 {%r8,%r9,%r10,%r11,%r12,%r13,%r14,%r15}, [%rd2], 16;");
        asm volatile ("mma.sync.aligned.m16n8k16.row.col.s32.s8.s8.s32 {%r8,%r9,%r10,%r11}, {%r0,%r1,%r2,%r3}, {%r4,%r5}, {%r8,%r9,%r10,%r11};");
        asm volatile ("wmma.store.d.sync.aligned.m16n16k16.s32 [%rd2], {%r8,%r9,%r10,%r11,%r12,%r13,%r14,%r15}, 16;");
    }
    #else
    /* PTX asm elided on non-CUDA host target */
    /* PTX: wmma.load.a.sync.aligned.row.m16n16k16.s8 {%r0,%r1,%r2,%r3}, [%rd0], 16; */
    /* PTX: wmma.load.b.sync.aligned.col.m16n16k16.s8 {%r4,%r5,%r6,%r7}, [%rd1], 16; */
    /* PTX: wmma.load.c.sync.aligned.m16n16k16.s32 {%r8,%r9,%r10,%r11,%r12,%r13,%r14,%r15}, [%rd2], 16; */
    /* PTX: mma.sync.aligned.m16n8k16.row.col.s32.s8.s8.s32 {%r8,%r9,%r10,%r11}, {%r0,%r1,%r2,%r3}, {%r4,%r5}, {%r8,%r9,%r10,%r11}; */
    /* PTX: wmma.store.d.sync.aligned.m16n16k16.s32 [%rd2], {%r8,%r9,%r10,%r11,%r12,%r13,%r14,%r15}, 16; */
    #endif
    return;
}

/* @ptx_emit */
void bcp_threshold_kernel(int32_t acc_ptr, int32_t n_clauses) {
    /* chisel block — PTX inline assembly */
    #if defined(__NVCC__) || defined(__CUDACC__)
    {
        asm volatile ("mov.u32 %r0, %tid.x;");
        asm volatile ("ld.global.s32 %r1, [%rd0];");
        asm volatile ("setp.gt.s32 %p0, %r1, 0;");
        asm volatile ("selp.s32 %r2, 1, 0, %p0;");
        asm volatile ("st.global.s32 [%rd1], %r2;");
    }
    #else
    /* PTX asm elided on non-CUDA host target */
    /* PTX: mov.u32 %r0, %tid.x; */
    /* PTX: ld.global.s32 %r1, [%rd0]; */
    /* PTX: setp.gt.s32 %p0, %r1, 0; */
    /* PTX: selp.s32 %r2, 1, 0, %p0; */
    /* PTX: st.global.s32 [%rd1], %r2; */
    #endif
    return;
}

void main(void) {
    printf("%s\n", (ystr_new("===================================================")).data);
    printf("%s\n", (ystr_new(" BooledAss — PTX Chisel Emission Test")).data);
    printf("%s\n", (ystr_new("===================================================")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("If this file compiled, the @ptx_emit + chisel pipeline")).data);
    printf("%s\n", (ystr_new("is wired correctly through:")).data);
    printf("%s\n", (ystr_new("  Lexer   -> @ptx_emit token recognized")).data);
    printf("%s\n", (ystr_new("  Parser  -> is_ptx_emit flag stored on FuncDecl")).data);
    printf("%s\n", (ystr_new("  Emitter -> chisel strings emitted as inline asm")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("Check the generated .c or .ll for:")).data);
    printf("%s\n", (ystr_new("  - __asm__ volatile (\"...\") in C output")).data);
    printf("%s\n", (ystr_new("  - call void asm sideeffect in LLVM output")).data);
    printf("%s\n", (ystr_new("  - PTX instructions: mma.sync, wmma.load, setp, selp")).data);
    printf("%s\n", (ystr_new("")).data);
    int32_t and_11 = (1 * 1);
    int32_t or_10 = ((1 + 0) - (1 * 0));
    int32_t not_1 = (1 - 1);
    printf("%s", (ystr_new("  AND(1,1) = ")).data);
    printf("%d\n", (int)and_11);
    printf("%s\n", (ystr_new("  expected: 1")).data);
    printf("%s", (ystr_new("  OR(1,0)  = ")).data);
    printf("%d\n", (int)or_10);
    printf("%s\n", (ystr_new("  expected: 1")).data);
    printf("%s", (ystr_new("  NOT(1)   = ")).data);
    printf("%d\n", (int)not_1);
    printf("%s\n", (ystr_new("  expected: 0")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("===================================================")).data);
    printf("%s\n", (ystr_new(" PTX Chisel Test COMPLETE")).data);
    printf("%s\n", (ystr_new("===================================================")).data);
    return;
}

