/* ============================================== */
/*  Generated by Y Compiler — C11 Backend   */
/* ============================================== */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>

/* ── Y Runtime: String ──────────────────── */
typedef struct {
    char*  data;
    size_t len;
    size_t cap;
} YStr;

static YStr ystr_new(const char* s) {
    size_t len = s ? strlen(s) : 0;
    size_t cap = len + 1;
    char* data = (char*)malloc(cap);
    if (s) memcpy(data, s, len);
    data[len] = '\0';
    return (YStr){ data, len, cap };
}

static YStr ystr_clone(const YStr* s) {
    return ystr_new(s->data);
}

static void ystr_push(YStr* s, char c) {
    if (s->len + 1 >= s->cap) {
        s->cap = s->cap * 2 + 1;
        s->data = (char*)realloc(s->data, s->cap);
    }
    s->data[s->len++] = c;
    s->data[s->len] = '\0';
}

static void ystr_push_str(YStr* s, const YStr* other) {
    size_t olen = other->len;
    while (s->len + olen >= s->cap) {
        s->cap = s->cap * 2 + 1;
        s->data = (char*)realloc(s->data, s->cap);
    }
    memcpy(s->data + s->len, other->data, olen);
    s->len += olen;
    s->data[s->len] = '\0';
}

static bool ystr_eq(const YStr* a, const YStr* b) {
    if (a->len != b->len) return false;
    return memcmp(a->data, b->data, a->len) == 0;
}

static bool ystr_eq_cstr(const YStr* a, const char* b) {
    return strcmp(a->data, b) == 0;
}
static bool ystr_eq_val(const YStr* a, const YStr* b) {
    if (a->len != b->len) return false;
    return memcmp(a->data, b->data, a->len) == 0;
}

static char ystr_char_at(const YStr* s, size_t i) {
    return (i < s->len) ? s->data[i] : '\0';
}

static void ystr_free(YStr* s) {
    free(s->data);
    s->data = NULL;
    s->len = 0;
    s->cap = 0;
}

/* ── Y Runtime: Dynamic Vector ──────────── */
typedef struct {
    void*  data;
    size_t len;
    size_t cap;
    size_t elem_size;
} YVec;

static YVec yvec_new(size_t elem_size) {
    return (YVec){ NULL, 0, 0, elem_size };
}

static void yvec_push(YVec* v, const void* elem) {
    if (v->len >= v->cap) {
        v->cap = v->cap == 0 ? 8 : v->cap * 2;
        v->data = realloc(v->data, v->cap * v->elem_size);
    }
    memcpy((char*)v->data + v->len * v->elem_size, elem, v->elem_size);
    v->len++;
}

static void* yvec_get(const YVec* v, size_t i) {
    return (char*)v->data + i * v->elem_size;
}

static char yvec_get_char(const YVec* v, size_t i) {
    return *((char*)yvec_get(v, i));
}

static size_t yvec_len(const YVec* v) {
    return v->len;
}

static size_t ystr_len(const YStr* s) {
    return s->len;
}

static void yvec_free(YVec* v) {
    free(v->data);
    v->data = NULL;
    v->len = 0;
    v->cap = 0;
}

/* ── Y Runtime: Print ───────────────────── */
static void yprint_str(const YStr* s) {
    printf("%s", s->data);
}

static void yprint_int(int64_t v) {
    printf("%lld", (long long)v);
}

static void yprint_float(double v) {
    printf("%f", v);
}

static void yprintln_str(const YStr* s) {
    printf("%s\n", s->data);
}

/* ── Y Runtime: File I/O ────────────────── */
static YStr yfile_read_to_string(const YStr* path_str) {
    const char* path = path_str->data;
    FILE* f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Error: Cannot open file '%s'\n", path);
        exit(1);
    }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(len + 1);
    fread(buf, 1, len, f);
    buf[len] = '\0';
    fclose(f);
    YStr result = { buf, (size_t)len, (size_t)(len + 1) };
    return result;
}

static void yfile_write(const YStr* path_str, const YStr* content) {
    const char* path = path_str->data;
    FILE* f = fopen(path, "wb");
    if (!f) {
        fprintf(stderr, "Error: Cannot write file '%s'\n", path);
        exit(1);
    }
    fwrite(content->data, 1, content->len, f);
    fclose(f);
}

/* ── User Code ───────────────────────────────── */


int32_t arith_and(int32_t a, int32_t b);
int32_t arith_or(int32_t a, int32_t b);
int32_t arith_not(int32_t a);
int32_t align_to_tile(int32_t dim, int32_t tile);
void main(void);

int32_t arith_and(int32_t a, int32_t b) {
    return (a * b);
}

int32_t arith_or(int32_t a, int32_t b) {
    return ((a + b) - (a * b));
}

int32_t arith_not(int32_t a) {
    return (1 - a);
}

int32_t align_to_tile(int32_t dim, int32_t tile) {
    int32_t rem = (dim % tile);
    if ((rem == 0)) {
        return dim;
    }
    return (dim + (tile - rem));
}

void main(void) {
    printf("%s\n", (ystr_new("===================================================")).data);
    printf("%s\n", (ystr_new(" BooledAss -- CPU Smoke Test")).data);
    printf("%s\n", (ystr_new(" GF(2) arithmetic + BCP threshold")).data);
    printf("%s\n", (ystr_new("===================================================")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("-- Test 1: OR truth table (A+B-A*B) --")).data);
    printf("%s", (ystr_new("  OR(0,0) = ")).data);
    printf("%d\n", (int)arith_or(0, 0));
    printf("%s\n", (ystr_new("  expected: 0")).data);
    printf("%s", (ystr_new("  OR(1,0) = ")).data);
    printf("%d\n", (int)arith_or(1, 0));
    printf("%s\n", (ystr_new("  expected: 1")).data);
    printf("%s", (ystr_new("  OR(0,1) = ")).data);
    printf("%d\n", (int)arith_or(0, 1));
    printf("%s\n", (ystr_new("  expected: 1")).data);
    printf("%s", (ystr_new("  OR(1,1) = ")).data);
    printf("%d\n", (int)arith_or(1, 1));
    printf("%s\n", (ystr_new("  expected: 1")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("-- Test 2: AND truth table (A*B) --")).data);
    printf("%s", (ystr_new("  AND(0,0) = ")).data);
    printf("%d\n", (int)arith_and(0, 0));
    printf("%s\n", (ystr_new("  expected: 0")).data);
    printf("%s", (ystr_new("  AND(1,0) = ")).data);
    printf("%d\n", (int)arith_and(1, 0));
    printf("%s\n", (ystr_new("  expected: 0")).data);
    printf("%s", (ystr_new("  AND(0,1) = ")).data);
    printf("%d\n", (int)arith_and(0, 1));
    printf("%s\n", (ystr_new("  expected: 0")).data);
    printf("%s", (ystr_new("  AND(1,1) = ")).data);
    printf("%d\n", (int)arith_and(1, 1));
    printf("%s\n", (ystr_new("  expected: 1")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("-- Test 3: NOT truth table (1-A) --")).data);
    printf("%s", (ystr_new("  NOT(0) = ")).data);
    printf("%d\n", (int)arith_not(0));
    printf("%s\n", (ystr_new("  expected: 1")).data);
    printf("%s", (ystr_new("  NOT(1) = ")).data);
    printf("%d\n", (int)arith_not(1));
    printf("%s\n", (ystr_new("  expected: 0")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("-- Test 4: A AND (B OR C) with A=B=C=1 --")).data);
    int32_t a1 = 1;
    int32_t b1 = 1;
    int32_t c1 = 1;
    int32_t or_bc = arith_or(b1, c1);
    int32_t coeff1 = arith_and(a1, or_bc);
    printf("%s", (ystr_new("  OR(B,C)        = ")).data);
    printf("%d\n", (int)or_bc);
    printf("%s\n", (ystr_new("  expected: 1")).data);
    printf("%s", (ystr_new("  AND(A, OR_BC)  = ")).data);
    printf("%d\n", (int)coeff1);
    printf("%s\n", (ystr_new("  expected: 1 (SAT)")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("-- Test 5: NOT(A) AND B with A=1, B=1 --")).data);
    int32_t a2 = 1;
    int32_t b2 = 1;
    int32_t not_a = arith_not(a2);
    int32_t coeff2 = arith_and(not_a, b2);
    printf("%s", (ystr_new("  NOT(A)         = ")).data);
    printf("%d\n", (int)not_a);
    printf("%s\n", (ystr_new("  expected: 0")).data);
    printf("%s", (ystr_new("  AND(NOT_A, B)  = ")).data);
    printf("%d\n", (int)coeff2);
    printf("%s\n", (ystr_new("  expected: 0 (UNSAT)")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("-- Test 6: NOT(A) AND B with A=0, B=1 --")).data);
    int32_t a3 = 0;
    int32_t b3 = 1;
    int32_t not_a3 = arith_not(a3);
    int32_t coeff3 = arith_and(not_a3, b3);
    printf("%s", (ystr_new("  NOT(A)         = ")).data);
    printf("%d\n", (int)not_a3);
    printf("%s\n", (ystr_new("  expected: 1")).data);
    printf("%s", (ystr_new("  AND(NOT_A, B)  = ")).data);
    printf("%d\n", (int)coeff3);
    printf("%s\n", (ystr_new("  expected: 1 (SAT)")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("-- Test 7: BCP Threshold simulation --")).data);
    int32_t row0 = coeff1;
    int32_t row1 = coeff2;
    printf("%s", (ystr_new("  Clause 0 (A AND (B OR C)): sum=")).data);
    printf("%d\n", (int)row0);
    if ((row0 > 0)) {
        printf("%s\n", (ystr_new(" --> SAT")).data);
    } else {
        printf("%s\n", (ystr_new(" --> UNSAT (conflict!)")).data);
    }
    printf("%s", (ystr_new("  Clause 1 (NOT(A) AND B):   sum=")).data);
    printf("%d\n", (int)row1);
    if ((row1 > 0)) {
        printf("%s\n", (ystr_new(" --> SAT")).data);
    } else {
        printf("%s\n", (ystr_new(" --> UNSAT (conflict!)")).data);
    }
    printf("%s\n", (ystr_new("  Expected: Clause 0 SAT, Clause 1 UNSAT")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("-- Test 8: Padding alignment (align_to_tile) --")).data);
    printf("%s", (ystr_new("  align(3,  16) = ")).data);
    printf("%d\n", (int)align_to_tile(3, 16));
    printf("%s\n", (ystr_new("  expected: 16")).data);
    printf("%s", (ystr_new("  align(13, 16) = ")).data);
    printf("%d\n", (int)align_to_tile(13, 16));
    printf("%s\n", (ystr_new("  expected: 16")).data);
    printf("%s", (ystr_new("  align(16, 16) = ")).data);
    printf("%d\n", (int)align_to_tile(16, 16));
    printf("%s\n", (ystr_new("  expected: 16")).data);
    printf("%s", (ystr_new("  align(17, 16) = ")).data);
    printf("%d\n", (int)align_to_tile(17, 16));
    printf("%s\n", (ystr_new("  expected: 32")).data);
    printf("%s", (ystr_new("  align(5,   8) = ")).data);
    printf("%d\n", (int)align_to_tile(5, 8));
    printf("%s\n", (ystr_new("  expected: 8")).data);
    printf("%s", (ystr_new("  align(33, 16) = ")).data);
    printf("%d\n", (int)align_to_tile(33, 16));
    printf("%s\n", (ystr_new("  expected: 48")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("-- Test 9: GF(2) OR cannot exceed 1 --")).data);
    int32_t x = 1;
    int32_t y = 1;
    int32_t z2 = arith_or(x, y);
    int32_t w = arith_or(z2, 1);
    printf("%s", (ystr_new("  OR(1,1)       = ")).data);
    printf("%d\n", (int)z2);
    printf("%s\n", (ystr_new("  expected: 1")).data);
    printf("%s", (ystr_new("  OR(OR(1,1),1) = ")).data);
    printf("%d\n", (int)w);
    printf("%s\n", (ystr_new("  expected: 1 (no overflow)")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("===================================================")).data);
    printf("%s\n", (ystr_new(" BooledAss CPU Smoke Test COMPLETE")).data);
    printf("%s\n", (ystr_new(" All tests use only I32 arithmetic -- no GPU needed")).data);
    printf("%s\n", (ystr_new("===================================================")).data);
    return;
}

